### ISSUE TITLE
[ADR]: Shared Calendar

### ISSUE THREAD

**Issue by widal001** [HHS/simpler-grants-gov#100]
### Description

Determine the platform that we want to manage calendar events and availability.

### Options

- [Confluence](https://www.atlassian.com/software/confluence/team-calendars)
- [Google Calendar](https://support.google.com/calendar/answer/37083?hl=en)
- [Nextcloud Calendar](https://apps.nextcloud.com/apps/calendar)
- Others as suggested by dev team

#### Must Have

- **HHS Network Access:** Users on the HHS network can access this shared calendar
- **Private Calendar Events:** Users can create and share calendar events that are only visible to designated groups of users
- **Public Calendar Events:** Users can create and share calendar events that are visible to members of the public
- **Video Conference Integration:** Users can add the details for a video conference to the calendar invite, and preferably create a new meeting-specific video conference link directly from the event creation page.
-  **Authority to Operate (ATO):** The platform must be covered under the Grants.gov Authority to Operate (ATO)

#### Nice to Have

- **Open Source:** The code used to host and run the calendar is open source
- **Booking Link:** Users can create and share a link through which other users can view their availability and schedule a meeting

### Definition of Done

- [x] The approvers for this decision have been identified (ideally before work on the ADR starts)
- [x] The ADR is created and stored in documentation/decisions/adr with status "Accepted"
- [x] The ADR has been reviewed and approved by the approvers listed above
- [x] The ADR satisfies requirements that are outlined in the ADR template
- [x] Any follow-up tickets have been created (if necessary)
- [ ] The tool selected satisfies the following decision criteria (or there is a plan to cover the gaps):
  - [ ] HHS Network Access
  - [ ] Private Calendar Events
  - [ ] Public Calendar Events
  - [ ] Video Conference Integration
  - [ ] Authority to Operate

**Comment by sumiat** [comment]
Reassigning to @EOKENAVA since Esther and @sarahknoppA6 have been discussing as part of the Recurring Meetings milestone. Thanks!

**Comment by widal001** [comment]
Closing because issue was marked as 'Done' in https://github.com/orgs/HHS/projects/13
