### ISSUE TITLE
[Task]: Determine scope of Search MVP 

### ISSUE THREAD

**Issue by andycochran** [HHS/simpler-grants-gov#1000]
### Summary

- Who: Will MVP be for a public release or is it an internal milestone upon which we'll iterate? 
- What: What's minimally viable for the defined audience? 
- When: If launch is an MVP goal, is there a desired date, and how does a comms plan affect scope?

### Acceptance criteria

- [ ] Have all the information to create the scope of the Search MVP work

**Comment by sumiat** [comment]
Meeting set for 1/25

**Comment by acouch** [comment]
I've met internally with team members to better define this and flush it out. We've broken this work up into https://app.gitbook.com/o/cFcvhi6d0nlLyH2VzVgn/s/Pm7UEzeiS1tbLCV1SFRu/planning/deliverables/specifications/search-mvp-page and https://app.gitbook.com/o/cFcvhi6d0nlLyH2VzVgn/s/Pm7UEzeiS1tbLCV1SFRu/planning/deliverables/specifications/search-mvp-extended-data-model
