### ISSUE TITLE
Draft for review the API v1 public launch 30k

### ISSUE THREAD

**Issue by sumiat** [HHS/simpler-grants-gov#1002]
### Acceptance criteria

- [x] Create a draft of the deliverable spec for the API v1 public launch 30k 
- [x] Send to Billy/Sarah for review

**Comment by sumiat** [comment]
Drafted the specs here: https://app.gitbook.com/o/cFcvhi6d0nlLyH2VzVgn/s/Pm7UEzeiS1tbLCV1SFRu/planning/deliverables/specifications/opportunity-extended-data-model and https://app.gitbook.com/o/cFcvhi6d0nlLyH2VzVgn/s/Pm7UEzeiS1tbLCV1SFRu/planning/deliverables/specifications/opportunity-endpoint-api-limited-announcement. Need to talk through if these should be combined and/or how to handle a public launch. Will be discussing with Billy and Aaron on 1/25

**Comment by EOKENAVA** [comment]
Considering you've completed the DoD by drafting the doc, we can consider this closed

**Comment by sumiat** [comment]
I have sent to Billy @EOKENAVA and we reviewed but we are meeting again on 1/25 to discuss how best to break up the work and discussing if the announcements are necessary.

**Comment by sumiat** [comment]
closing, will create a follow on task for incorporating review feedback.
