### ISSUE TITLE
[Task]: Analytics - Create `SprintBurnup` metric

### ISSUE THREAD

**Issue by widal001** [HHS/simpler-grants-gov#1018]
### Summary

Create a new `BaseMetric` subclass called `SprintBurnup` that calculates the number of open and closed points/issues on each day of the sprint and visualizes those counts as a stacked area chart.

### Acceptance criteria

- [ ] Running `poetry run calculate sprint_burnup --sprint @current --unit points` calculates the sprint burnup by points
- [ ] Running `poetry run calculate sprint_burnup --sprint @current --unit issues` calculates the sprint burnup by issues

**Comment by AlexanderStephensonUSDS** [comment]
For openness, for the purpose of this burnup metric am I correct that the total points are within sprints and not across sprints?

**Comment by widal001** [comment]
Correct! Here's an example of the automated sprint burnup report from GitHub (screenshot below)

The reason we want to replicate this with custom reporting is because currently only members of the HHS org can see "historical charts.

<img width="1440" alt="Screenshot 2024-01-23 at 12 57 34 PM" src="https://github.com/HHS/simpler-grants-gov/assets/21350331/d230b3c9-9040-445a-983e-9b4aededfdf5">


In terms of approach, if we factor out some of common steps in calculating burndown into a separate `utils.py` we can probably re-use a bunch of them in burnup then just add running total of closed as well.
