### ISSUE TITLE
[Task]: Analytics - Move dataset transformations to an `analytics.etl` package

### ISSUE THREAD

**Issue by widal001** [HHS/simpler-grants-gov#1022]
### Summary

A number of the dataset classes in `analytics.dataset` have a `load_from_json_files()` class method that creates a new dataset instance from a set of source files. Instead of loading and applying the transformations to the source files in this class method, they should be pulled out into a separate function or class that is stored in an `analytics.etl` sub-package.

### Acceptance criteria

- [ ] An `analytics.etl` sub-package has been created
- [ ] The `SprintBoard.load_from_json_files()` and `DeliverableTask.load_from_json_files()` have been replaced with ETL functions (or classes) that load data from json files and return an instance of `SprintBoard` and `DeliverableTask` respectively
- [ ] These new ETL functions or classes can be invoked from the CLI

**Comment by widal001** [comment]
We're currently prioritizing the following tasks, but will pick this up this week if we have time:

- #1018 
- #1184 
- #1186

**Comment by acouch** [comment]
@widal001 I don't think we need this for the upcoming work, as most of the querying can be done by the BI tool and we just need to get the data over to storage from github for the initial round of work. Happy to discuss, move to a different body of work, or bring back in if appropriate
