### ISSUE TITLE
[Task]: Update Infrastructure Renovate process

### ISSUE THREAD

**Issue by SammySteiner** [HHS/simpler-grants-gov#1029]
### Summary

Renovate creates pull requests to update outdated Go modules in our Infra directory.
Describe the process for reviewing and approving the renovate pull request for the Infrastructure: https://app.gitbook.com/o/cFcvhi6d0nlLyH2VzVgn/s/v1V0jIH7mb7Yb3jlNrgk/engineering/draft-renovate-pr-playbook-and-workflow

### Acceptance criteria

Infra section filled out with relevant steps

**Comment by coilysiren** [comment]
o7

**Comment by coilysiren** [comment]
Process:

- check the release notes to look for significant changes
- check our terraform configuration against the release notes
- ensure the every instance of a given terraform provider is being updated to the same version, see this PR for an example where renovate _**does not**_ initially do this: https://github.com/HHS/simpler-grants-gov/pull/1102
- run `terraform init -upgrade` in every folder to generate updated lockfiled
- run `terraform plan` in every folder to check for diffs, flag and diffs that look like they were generated by the version upgrade
