### ISSUE TITLE
[Task]: Create Alert for Errors in API Application Logs

### ISSUE THREAD

**Issue by acouch** [HHS/simpler-grants-gov#1033]
### Summary

There are not currently alerts for errors in the API applications logs. The application is currently logged in `service/api-prod`

This can be implemented using an [anomaly detector](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch_Anomaly_Detection.html) in Cloudwatch. **EDIT: note [options below](https://github.com/HHS/simpler-grants-gov/issues/1033#issuecomment-1894476462)**

Errors status is captured in the `levelname` field:

```json

{
    "name": "src.logging.flask_logger",
    "msg": "end request",
    "args": [],
    "levelname": "ERROR",
    "levelno": 20,
    "pathname": "/api/src/logging/flask_logger.py",
    "filename": "flask_logger.py",
    "module": "flask_logger",
    "exc_info": null
...

```

There are steps for this ticket:

- [ ] Identify the threshold for errors that would be required for an alert
- [ ] Create alert for the specified threshold

### Acceptance criteria

- [ ] Alert created for errors in the API log
- [ ] The alerting mechanism can handle when we log @ Error level
- [ ] The alerts are sent to our emails, slack, or similar. _**We do not have to go searching for them!**_

### Open questions / notes
- Why were we not notified when the health check was failing? 
- How is the frontend failures handled? API and frontend are handled in the same way
- Synthetic alerts are set up for the frontend but are not set up for the API

### Stretch Goals

- [ ] The alerting mechanism can handle unstructured exceptions, like this one:

<img width="882" alt="image" src="https://github.com/HHS/simpler-grants-gov/assets/5768468/0a0ae01a-9092-4720-91d7-f84124fea027">

The above exception is "unstructured" because its not being logged as JSON with the exception on one line with level=ERROR. Instead it is being spread across multiple lines. The only way you can tell its an error is via noticing the `sqlalchemy.exc.OperationalError` or similar via a regex.

**Comment by coilysiren** [comment]
Some options here:

1. we make sure we always emit _**metrics**_ (instead of just logs) and use cloudwatch anamoly detection: https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch_Anomaly_Detection.html
2. we monitor cloudwatch logs with a lambda: https://docs.aws.amazon.com/lambda/latest/dg/services-cloudwatchlogs.html
3. we use a metrics filter for the logs group: https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/CreateMetricFilterProcedure.html

**Comment by coilysiren** [comment]
Here's a situation that I would like to have been caught by a potential error logging lambda:

https://nava.slack.com/archives/C057K146W8H/p1705960305556179

(nava slack)

**Comment by coilysiren** [comment]
Here's the error log for the issue above:

<img width="448" alt="image" src="https://github.com/HHS/simpler-grants-gov/assets/5768468/b0a54e84-cf0b-42ff-8991-61f4ad668513">

Note that it doesn't have a log level, or any similar indicator

**Comment by acouch** [comment]
sub / related task: #1066 . We could close that one if it makes more sense to roll it into this one.

**Comment by aplybeah** [comment]
We have code for synthetic canary which is supposed to track the kind of metrics we want to capture. However it looks like the module itself isn't actually called anywhere and any resources created by it have long since disappeared. I'm going to call the module somewhere it can be deployed and hope that this is our fix

**Comment by aplybeah** [comment]
Update: will move forward with updating where the canary module is called which should cover the unstructured errors from the API side (it's only monitoring the front end). Will plan on setting up anomaly detector to catch the rest of the errors

**Comment by aplybeah** [comment]
update: created test alarm which mirrors the  `high_app_response_time" ` alarm (high latency).
This is what the boundaries for the anomaly detection would look like. However, it is important to note that according to the docs, the actual anomaly detection will need a little time to calibrate, which may delay findings on whether or not the alarm is tracking useful data. Still looking to see if there's a way to use preexisting data as a way to train it.
```
# upper band for anomaly detection
  metric_query {
    id          = "q1"
    label       = "expectedLevel(m1)"
    return_data = "true"
    expression  = "ANOMALY_DETECTION_BAND(m1)"
  }

  metric_query {
    id          = "m1"
    return_data = "true"

    metric {
      metric_name = "TargetResponseTime"
      namespace   = "AWS/ApplicationELB"
      period      = 60
      stat        = "Average"
      unit        = "Count"
    }
  }
```

**Comment by aplybeah** [comment]
Update: Working on a metric filter which will look for the errors in the logs. Ideally this should work with unstructured errors as well
