### ISSUE TITLE
[Task]: Deploy DMS module to default networking configuration in us-east-1

### ISSUE THREAD

**Issue by coilysiren** [HHS/simpler-grants-gov#1038]
### Summary

After @coilysiren deploying the staging networking configuration in https://github.com/HHS/simpler-grants-gov/issues/1037, @aplybeah needs to start configuring the DMS to be deployed via that new configuration.

**Comment by acouch** [comment]
Tracking that #501 will be captured in this ticket the DMS module is part of the networking setup!

**Comment by aplybeah** [comment]
Functionally, this work is done and currently in the console. The only thing left is to finish writing it in terraform. 
Work completed so far:
- moved DMS endpoints and DMS replication instance from us-east-2 to us-east-1 (including relevant certificates)
- add new security group that allows inbound requests to the database from DMS
- Deleted DMS resources from us-east-2
- Successfully tested the endpoints

**Comment by aplybeah** [comment]
Update: 
PR: https://github.com/HHS/simpler-grants-gov/pull/1099
- Applying some feedback from the linked PR
-Added the DB secrets to AWS to prevent terraform from storing them in plaintext
