### ISSUE TITLE
[Task]: Upgrade Terraform in CI/CD test

### ISSUE THREAD

**Issue by SammySteiner** [HHS/simpler-grants-gov#1041]
### Summary

We're currently using terraform version 1.2.1, while the current terraform version is 1.7.x. 
The Platform repo is using version 1.4.6, so we could upgrade to that version.
This is blocking #960 as the terraform function being used was added in version 1.3.x.

### Acceptance criteria

Terraform version is upgraded past version 1.3.x.

**Comment by coilysiren** [comment]
Are we taking votes? I vote for upgrading to terraform 1.7

**Comment by SammySteiner** [comment]
I spent a few minutes with this, this morning and discovered that we're using 1.4.6 almost everywhere, except for our CI/CD pipeline tests. So I'm going to make a small PR to fix that, since it shouldn't require any testing.

Going from 1.4.6 to 1.7 is definitely a bigger question and something I'd suggest posting about in the platform channel, or maybe search to see if it's already been discussed. I'd be surprised if they haven't already looked into it.
