### ISSUE TITLE
[Task]: PAC discovery

### ISSUE THREAD

**Issue by sumiat** [HHS/simpler-grants-gov#1064]
In sprint 15, we did some research around Participant Advisory Council goals for the project and research into the Nava approach to PACs. In this effort, we want to start planning for how to implement the PAC(s) for this project. 

Things to consider: How will they be established? What type of participants should be recruited? How regularly will meetings operate? Goals? Obligations/expectations of participants? Compensation? 

### Acceptance criteria

- [x] Create a space in the internal wiki for PAC documentation (can begin by identify the goals we've identified) 

### Out of scope in this sprint, to be added in separate tickets
Discovery work: 
- Meet with stakeholders to understand priorities 
- Begin gathering potential contacts
- Meet with product managers to review roadmap and opportunities for research
- Begin ideating on alternative group naming(s), based on diversions from typical Nava PAC model
- Identify additional community feedback strategies that should be considered (e.g. Is PAC a single tool in our belt?)
-  Work with product to draft 30k for PAC so that it's ready for review by Luca

**Comment by andycochran** [comment]
This can maybe be broken down a lot. Each of the "Discovery work" items above could be its own ticket.
