### ISSUE TITLE
[Task]: Add Brett Rosenblatt to MAINTAINERS.md

### ISSUE THREAD

**Issue by acouch** [HHS/simpler-grants-gov#1079]
### Summary

Add @bretthrosenblatt to https://github.com/HHS/simpler-grants-gov/blob/main/MAINTAINERS.md#engineering

### Acceptance criteria

- [ ] @bretthrosenblatt added to the project

**Comment by acouch** [comment]
@bretthrosenblatt The tasks is to add yourself to a PR https://github.com/HHS/simpler-grants-gov/pull/1013 . Apologies if that was not clear.

**Comment by sumiat** [comment]
missing PR
