### ISSUE TITLE
[Task]: Review Search UI Figma draft

### ISSUE THREAD

**Issue by sumiat** [HHS/simpler-grants-gov#1104]
### Summary
Get minimal review on the first draft of the Search UI Figma draft

### Acceptance Criteria
- [x] Review with @chouinar and @SammySteiner 
- [x] Review with Emily and Kevin
- [x] Incorporate changes into Figma

**Comment by crystabelrangel** [comment]
Initial call with Emily, Kevin, and Lucas took place today 2/20.

- [Draft - V3](https://www.figma.com/file/Zm7oIeBpwjrsXcmjV3K7HR/Search?type=design&node-id=4577%3A3099&mode=design&t=i0bqMzJ9zJN9YFau-1) has their initial feedback from the call.

- [Draft - V4](https://www.figma.com/file/Zm7oIeBpwjrsXcmjV3K7HR/Search?type=design&node-id=4698%3A2671&mode=design&t=3B3VWOx8bYaQ2uUw-1) has the changes incorporated

They will review and provide additional feedback, which we can address in the following sprint.
