### ISSUE TITLE
[Task]: Draft voice and tone guide

### ISSUE THREAD

**Issue by sumiat** [HHS/simpler-grants-gov#1109]
### Summary

Create a draft guide for voice and tone. 

### Open questions
- It seems like we may want to create separate tickets for each round, yes? @senongo 

### Acceptance criteria

- [ ] Round 1: Draft voice and tone guide, share with stakeholders for feedback. 
- [ ] Write key message drafts
- [ ] Finalize both value prop and key messages, with examples of how to apply them across channels

**Comment by meghscase** [comment]
This description is not quite right. The value prop and messages are part of the brand and comms strategy, not the voice and tone guide. 

As for voice and tone, it is approved by Adriana and Emily and will be going to Julius -- waiting for confirmation on whether I should send it or they will.

**Comment by sumiat** [comment]
@meghscase - do you mind updating this ticket? These were created back in January so are definitely out of date!

**Comment by meghscase** [comment]
We are currently waiting for @itsemilyianacone and Adriana to let me know if I should forward to Julius or if one o them will.

**Comment by meghscase** [comment]
Sent this to Julius this morning.

**Comment by widal001** [comment]
Closing because issue was marked as 'Done' in https://github.com/orgs/HHS/projects/13

**Comment by margaretspring** [comment]
Received approval from Julius 4/29
