### ISSUE TITLE
[Task]: Create an initial technical review of a metric dashboard and platform

### ISSUE THREAD

**Issue by acouch** [HHS/simpler-grants-gov#1118]
### Summary

This task is to create an initial technical review of the proposed Sprint and Delivery dashboard and metrics platform.

The draft deliverable is available: https://app.gitbook.com/o/cFcvhi6d0nlLyH2VzVgn/s/Pm7UEzeiS1tbLCV1SFRu/planning/deliverables/specifications/sprint-and-delivery-dashboard

The internal place to create an technical review is https://app.gitbook.com/o/cFcvhi6d0nlLyH2VzVgn/s/v1V0jIH7mb7Yb3jlNrgk/engineering/data-engineering

This can take the form that the implementer desires (ie table or document or both) and should be time-boxed to several days of effort. 

### Steps

- [ ] Review the current documents
- [ ] Setup a time with the Eng lead to discuss initial questions and thoughts
- [ ] Create an outline of the technical review
- [ ] Create document and share for review

### Acceptance criteria

- [ ] Create a technical review in Gitbook

**Comment by EOKENAVA** [comment]
Awaiting resource from MH to assist with the delivery dashboard initiative

**Comment by mxk0** [comment]
This is now tracked elsewhere: https://github.com/HHS/simpler-grants-gov/issues/2347
