### ISSUE TITLE
[Task]: Get prod approval from MH

### ISSUE THREAD

**Issue by sumiat** [HHS/simpler-grants-gov#1128]
### Summary

An SIA has been submitted for final approval to HHS. Once that SIA has been accepted/signed by HHS, we need approval from Curtis at MH to access prod. 

- MH gives us their prod account address
- Nava puts the MH prod account address into Simpler AWS
- MH approves peering connection generated by Simpler 
- Nava tests/confirms peering connection

### Acceptance criteria

- [ ] Approval from Curtis at MH for prod access
- [ ] Peering connection success between MH prod account and Simpler AWS

**Comment by coilysiren** [comment]
With respect to the peering connnection, there's actually 3 components detailed here:

https://betagrantsgov.slack.com/archives/C05UJJNKN3B/p1706729294371359

**Comment by acouch** [comment]
Approval has been granted.
