### ISSUE TITLE
[Task]: Email marketing personas

### ISSUE THREAD

**Issue by sumiat** [HHS/simpler-grants-gov#1139]
### Summary
- Email marketing synthesis is completed; 
- There is an email audience list and this work will identify the personas based on that list

### Acceptance criteria

- [ ] Identify personas for email marketing 
- [ ] Share with Adriana / @CarleyKimball

**Comment by widal001** [comment]
Closing because issue was marked as 'Done' in https://github.com/orgs/HHS/projects/13
