### ISSUE TITLE
[Task]: Dev Tools Onboarding Process for Internal Users

### ISSUE THREAD

**Issue by btabaska** [HHS/simpler-grants-gov#1153]
### Summary

Establish a documented process for adding and removing internal users from development tools.

### Acceptance criteria

- A step-by-step guide is created, detailing the process for adding and removing internal users from development tools.
- The guide includes specific instructions for each tool used by the development team.
- Procedures for handling user permissions and access levels are clearly defined.
- The document is reviewed for accuracy and ease of use

**Comment by sumiat** [comment]
Checking with security to see if we can collect PII in google forms

**Comment by btabaska** [comment]
Duplicate
