### ISSUE TITLE
[Task]:  Dev Tools Onboarding Process for Public Users

### ISSUE THREAD

**Issue by btabaska** [HHS/simpler-grants-gov#1154]
### Summary

Develop a clear onboarding process for public users to access and use development tools.

### Acceptance criteria

- A public-facing document is created, outlining how external contributors can get access to necessary development tools.
- We have a system for tracking the onboarding process for all new members, ensuring that they have agreed to the terms of use (such as community agreements and content sensitivity guidelines) and completed all necessary onboarding steps.
- The process includes verification steps to ensure secure access.
- Guidelines on acceptable use and contributions are included.
- Feedback from external users is solicited to ensure the process is user-friendly.

**Comment by btabaska** [comment]
https://docs.google.com/forms/d/127hYL8ZrWoOwu2jVwxz0cFtqASbFqaVzXrWnjrDIMp0/prefill

**Comment by btabaska** [comment]
Developed a Google Form to onboard members of the public. Added to the wiki.

**Comment by widal001** [comment]
Closing because issue was marked as 'Done' in https://github.com/orgs/HHS/projects/13
