### ISSUE TITLE
[Task]: Scan and Remove Sensitive Information

### ISSUE THREAD

**Issue by btabaska** [HHS/simpler-grants-gov#1156]
### Summary

Implement a process to scan and remove sensitive information from Slack, Zoom, and the Wiki before inviting public users.

### Acceptance criteria

- Automated tools or manual procedures are put in place to identify and remove sensitive information.
- A log of actions taken to remove sensitive data is maintained for auditing purposes.
- Staff are trained on how to prevent the future posting of sensitive information.
- A review process is established to regularly check for sensitive information.

**Comment by btabaska** [comment]
Channels to Scan:
- # all-grants-gov
-  # all-introduction
-  # all-welcome
-  # topic-communications
-  # topic-design
-  # topic-engineering
-  # topic-gitbook-updates
-  # topic-help
-  # topic-open-source
-  # topic-participatory-process
- # topic-product
- # topic-reference-shelf
-  # topic-scrum-team

Information to scan for:
- Personally Identifiable Information
-- Phone Numbers
-- Personal Email Addresses (@gmail.com, @yahoo.com, @iCloud.com)
-- Addresses
--Sensitive Information (SSN, etc)

- Content in violation of Code of Conduct
-- Swear Words

**Comment by widal001** [comment]
Closing because issue was marked as 'Done' in https://github.com/orgs/HHS/projects/13
