### ISSUE TITLE
[Task]: Create GitBook Onboarding Process Wiki Page

### ISSUE THREAD

**Issue by btabaska** [HHS/simpler-grants-gov#1158]
### Summary

Document the onboarding process for GitBook, making it easy for new contributors to start using the platform.

### Acceptance criteria

- A detailed guide is published on the wiki, outlining the steps to get started with GitBook.
- The guide includes information on accessing resources, editing content, and publishing updates.

**Comment by sumiat** [comment]
Not needed - Public users will not be editing the wiki in this first iteration. We also have the public wiki intro page that users can join that shows them how to get started.
