### ISSUE TITLE
[Task]: Review taxonomy of filters (content design)

### ISSUE THREAD

**Issue by andycochran** [HHS/simpler-grants-gov#1168]
### Summary

Audit the filter options and determine whether they're optimal for users. Look for opportunities to improve scannability, legibility, readability, comprehension. The eligibility filters seem to be most confusing — e.g. `Nonprofits that do not have a 501(c)(3) status with the IRS, other than institutions of higher education`. This will also influence/help with improving the the naming of API fields (`nonprofits_non_higher_educating_without_501c3`).

##### OPPORTUNITY STATUS
- Forecasted
- Posted
- Closed
- Archived 

##### FUNDING INSTRUMENT TYPE
- Cooperative Agreement 
- Grant 
- Other 
- Procurement Contract

##### ELIGIBILITY
- City or township governments
- County governments 
- For profit organizations other than small businesses 
- Independent school districts 
- Individuals 
- Native American tribal governments (Federally recognized) 
- Native American tribal organizations (other than Federally recognized tribal governments) 
- Nonprofits having a 501(c)(3) status with the IRS, other than institutions of higher education 
- Nonprofits that do not have a 501(c)(3) status with the IRS, other than institutions of higher education 
- Others (see text field entitled "Additional Information on Eligibility" for clarification) 
- Private institutions of higher education 
- Public and State controlled institutions of higher education 
- Public housing authorities/Indian housing authorities 
- Small businesses 
- Special district governments 
- State governments 
- Unrestricted (i.e., open to any type of entity above), subject to any clarification in text field entitled "Additional Information on Eligibility" 

##### CATEGORY
- Affordable Care Act 
- Agriculture 
- Arts (see "Cultural Affairs" in CFDA) 
- Business and Commerce 
- Community Development Consumer Protection 
- Disaster Prevention and Relief 
- Education 
- Employment, Labor and Training 
- Energy 
- Environment 
- Food and Nutrition Health 
- Housing 
- Humanities (see "Cultural Affairs" in CFDA) 
- Income Security and Social Services 
- Information and Statistics 
- Infrastructure Investment and Jobs Act (IIJA) 
- Law, Justice and Legal Services 
- Natural Resources 
- Opportunity Zone Benefits 
- Other (see text field entitled "Explanation of Other Category of Funding Activity" for clarification) 
- Recovery Act 
- Regional Development 
- Science and Technology and other Research and Development 
- Transportation 

##### AGENCY
(Not including this list. Assuming these are all correctly-listed agency names.)

### Acceptance criteria

- [ ] Analyze the existing taxonomy of filters on grants.gov (labeling, organization, and functionality).
- [ ] Note any areas of confusion, inconsistency, or inefficiency in the current taxonomy.
- [ ] Reference previous research conducted to incorporate any findings on user needs, preferences, and interactions with search filters.
- [ ] Document the initial findings and provide any recommendations for improvements and next steps

### Out of Scope
Conduct Usability Tests

### Notes
- We could reach out to USDR as they may have created a taxonomy

**Comment by chouinar** [comment]
In my PR - I took a first pass at the values: https://github.com/HHS/simpler-grants-gov/pull/1187

**Comment by crystabelrangel** [comment]
Here is the sheet for the [Review of filter taxonomy](https://docs.google.com/spreadsheets/d/1M14vX-kDakn0QHhYkUnIasBnTFUfU73BKXXxAfCxtzQ/edit#gid=0)

We will be sharing with Emily and can also reach out to USDR if they have any additional insights on research conducted on their end.
