### ISSUE TITLE
[30k]: Community engagement dashboard

### ISSUE THREAD

**Issue by widal001** [HHS/simpler-grants-gov#1173]
### Key links

- Deliverable specification
- [Simpler Grants.gov full roadmap](https://github.com/orgs/HHS/projects/12)
- [10k milestones](https://github.com/orgs/HHS/projects/13/views/11?sliceBy%5Bvalue%5D=Community+engagement+dashboard)

### Description

- **What:** Publish a dashboard with metrics about our level of community engagement across channels like Slack, email, and GitHub
- **Why:** Demonstrates the team’s commitment to actively engaging the public and fostering a collaborative environment for the project
- **Who**
  - Public stakeholders
  - Internal stakeholders

> [!NOTE]
> For more information about this deliverable, please refer to the deliverable specification linked above.

**Comment by margaretspring** [comment]
@widal001 @sumiat - Was looking over the prioritized queued up 30Ks as I'm roughing out proposal items for the May-Aug PoP. Can't help noticing that we're fulfilling (be if VERY manually just now) a good chunk of the community engagement reporting within the scope of [Open Source Metrics](https://app.gitbook.com/o/cFcvhi6d0nlLyH2VzVgn/s/Pm7UEzeiS1tbLCV1SFRu/analytics/simpler-grants.gov-analytics/open-source-community-metrics/~/overview). Would need to check the level of integration into tools like Slack that we're considering for the Co-Design Group, but this reporting, esp if we automate the OS reporting... will be accomplished? May be worth discussing how this 30K is/should be addressed? Will add to the 30K review topics. Thanks!
