### ISSUE TITLE
[Task]: Create a SQL user for DMS

### ISSUE THREAD

**Issue by coilysiren** [HHS/simpler-grants-gov#1175]
### Summary

Right now the DMS is using the master username + password, but that's not tenable because those rotate. We should create new normal SQL users inside the database for 

### Acceptance criteria

- [ ] terraform configuration created that creates a SQL user with the right permissions (all of them?)
- [ ] user credentials copied into dev secret
- [ ] user credentials copied into staging secret
- [ ] user credentials copied into prod secret

### Notes
- @chouinar has commands that could be used
- Separate user for each env because there's a separate db for each env

**Comment by aplybeah** [comment]
Progress: 
- Still working on creating users
- Had a minor error with the script when trying to create the migration

**Comment by sumiat** [comment]
@coilysiren and @aplybeah - should we cancel this ticket?

**Comment by coilysiren** [comment]
Yeah, we are canceling everything about DMS
