### ISSUE TITLE
[30k]: Grants pipeline dashboard

### ISSUE THREAD

**Issue by widal001** [HHS/simpler-grants-gov#1178]
### Key links

- Deliverable specification
- [Simpler Grants.gov full roadmap](https://github.com/orgs/HHS/projects/12)
- [10k milestones](https://github.com/orgs/HHS/projects/13/views/11?sliceBy%5Bvalue%5D=Grants+pipeline+dashboard)

### Description

- **What:** Publish a dashboard with summary-level metrics about the grants pipeline, such as number of applications by location
- **Why:** Demonstrates the team’s commitment to making data about the grants pipeline more transparent and accessible to the public
- **Who**
  - Public stakeholders
  - Internal stakeholders

> [!NOTE]
> For more information about this deliverable, please refer to the deliverable specification linked above.

**Comment by sumiat** [comment]
**Weekly Update 5/8**

**What has been done?**
- Deliverable spec reviewed internally by Nava and MH. 
- Reviewed by Billy and Sarah
- Tech spec drafted and planning started 

**Status**
- Planning

**Risk**
- None so far, just working through scope 

**Deliverable Date**
- TBD

**What will be done?**
- Align on scope of work with A6
- If scope is aligned then determine the delivery date and publish the first draft of the tech specvv

**Comment by widal001** [comment]
Replacing our old deliverable tickets with a new ticket format
