### ISSUE TITLE
[Task]: Search Page SEO

### ISSUE THREAD

**Issue by SammySteiner** [HHS/simpler-grants-gov#1180]
### Summary

Search Page has relevant SEO attributes including a meta-title, and meta-description

### Acceptance criteria

- Design provides content for description
- New translation block for search page in locales folder
- meta tags on /search page visible in browser elements

**Comment by acouch** [comment]
The search page currently has these attributes: 
![Image](https://github.com/user-attachments/assets/55010084-61c8-4cdc-ad2a-a2442ca3de75)
