### ISSUE TITLE
[Task]: Analytics - Create a `DeliverableBurnup` metric

### ISSUE THREAD

**Issue by widal001** [HHS/simpler-grants-gov#1184]
### Summary

Create a new `DeliverableBurnup` metric that inherits from the `BaseMetric` class that produces a burnup chart for a given deliverable.

The result should look something like this:
<img width="1054" alt="Screenshot 2024-02-07 at 12 37 03 PM" src="https://github.com/HHS/simpler-grants-gov/assets/21350331/086bc9f7-8a22-4091-84cb-e0d1857db5dc">

### Notes

It would be helpful to look at #1018 for a reference implementation. Ideally both metrics would either inherit from a shared `BurnupBase` class or at least reuse a shared `calculate_burnup()` method.

### Acceptance criteria

- [ ] A `DeliverableBurnup` sub-class has been created which inherits from `BaseMetric`
- [ ] This metric can be calculated using the following CLI entrypoint: `poetry run analytics calculate deliverable_burnup --deliverable "Search UI"`
- [ ] Additional information about `DeliverableBurnup` has been added to the `documentation/analytics/metrics/` docs

**Comment by acouch** [comment]
Closing for now as we are tracking doing the calculation required for this work within the BI tool.
