### ISSUE TITLE
[Task]: Analytics - Create a `SprintPercentComplete` metric

### ISSUE THREAD

**Issue by widal001** [HHS/simpler-grants-gov#1185]
### Summary

Create a `SprintPercentComplete` sub-class that inherits from the `BaseMetric` class and can be used to calculate percentage complete by sprint.

### Notes

Check out the `DeliverablePercentComplete` code for a reference implementation. Ideally this class and that class would either inherit from a shared `PercentCompleteBase` class or at least use `calculate_percent_complete()` function from a shared utils module.

### Acceptance criteria

- [ ] A `SprintPercentComplete` sub-class has been created and it inherits from `BaseMetric`
- [ ] This metric can be calculated using the following CLI entrypoint: `poetry run analytics calculate sprint_percent_complete` or a similar CLI command
- [ ] Additional information about `SprintPercentComplete` has been added to the `documentation/analytics/metrics/` docs

**Comment by acouch** [comment]
Closing for now as we are tracking doing the calculation required for this work within the BI tool.
