### ISSUE TITLE
[Task]: Spike Feature Flags

### ISSUE THREAD

**Issue by SammySteiner** [HHS/simpler-grants-gov#1190]
### Summary

Nava has implemented feature flags on other projects like mass-pfml and NJUI. Speak with those teams about their implementations and best practices

### Acceptance criteria

Update the feature flag ADR ticket #1191 with the lessons learned

**Comment by sumiat** [comment]
#1191 ticket

**Comment by acouch** [comment]
This was completed but not closed. Closing now.
