### ISSUE TITLE
[Task]: Feature Flag to request Mock Data from API

### ISSUE THREAD

**Issue by SammySteiner** [HHS/simpler-grants-gov#1194]
### Summary

Create a feature flag set in the url that tells the api whether to use mock data or real data from the database. This flag will set a parameter in the query to the api.

**Comment by SammySteiner** [comment]
Need to coordinate value with @chouinar.

**Comment by acouch** [comment]
This was completed in: https://github.com/HHS/simpler-grants-gov/issues/1454
