### ISSUE TITLE
[Task]: Technical Planning for Delivery Dashboard 30K

### ISSUE THREAD

**Issue by acouch** [HHS/simpler-grants-gov#1195]
### Summary

This task is to create / review tasks for the https://app.gitbook.com/o/cFcvhi6d0nlLyH2VzVgn/s/Pm7UEzeiS1tbLCV1SFRu/planning/deliverables/specifications/delivery-dashboard. This will take place in the 30K planning sheet.

The scope for this ticket is limited to a review technical review and proposed updates to the 30k.

### Acceptance criteria

- [ ] 30K tasks and estimates updated in the 30k planning book

**Comment by acouch** [comment]
This is currently under discussion internally.

**Comment by acouch** [comment]
Currently researching Nava's internal Looker setup, and will make a recommendation in the form of a project plan in the "30K rough planning" worksheet that includes Andy's #1367

**Comment by acouch** [comment]
In order to test and look at one of the options I stood up a metabase install locally and created a dashboard:



![Image](https://github.com/HHS/simpler-grants-gov/assets/512243/af2e503b-f946-4187-863e-81a48afc53f4)



That could be shared:
![Image](https://github.com/HHS/simpler-grants-gov/assets/512243/88521afa-53ef-435c-b7ec-1bd936b63f40)

Using the json data exports from the analytics folder in this repo (`make issue-data-export` and `make sprint-data-export`)

Will a little more effort (hour or so?) this could be converted to the burndown and other required charts.

The basic steps to do this:

1. `docker run -d -p 3000:3000 --mount type=bind,source=$PWD/plugins,destination=/plugins --name metabasearm bobblybook/metabase` spins up metabase
2. `make issue-data-export` and `make sprint-data-export` exports the data which I converted to CSV `echo "closed,created,number,title" > data/issue-data.csv && jq -r '.[] | [.closedAt, .createdAt, .number, .title] | @csv' data/issue-data.json >> data/issue-data.csv`
3. For testing purposes the CSV can be uploaded directly into metabase and a dashboard created

This validated the metabase could be a nice open-source solution for connecting to data sources and creating no-code dashboards that can easily be shared and embedded.

**Comment by acouch** [comment]
I created "Delivery Dashboard Alternate" and "Simpler Metric Dashboard" 30ks rough drafts in the [30k planning doc](https://docs.google.com/spreadsheets/d/1lck9avmfQnmxoI9Q1u8c3VfuvgX_uUTTAQZ91SvmpHo/edit#gid=1759959202). 

I'd propose piping the delivery dashboard data into S3 (or Postgres or Redshift) and using a BI tool like Metabase or Quicksight to make it easy to create internal and external dashboards. Some of the delivery dashboards could be embedded in Gitbook.

A separate 30K "Simpler Metric Dashboard" or something similarly named could create the first metric dashboard and public metric API that is part of the Simpler site. This data could include real-time 30k delivery progress, Simpler site and API usage, and perhaps grants.gov usage as well.

**Comment by acouch** [comment]
Closing this and will discuss internally what the best follow-up ticket would be.

**Comment by widal001** [comment]
> I'd propose piping the delivery dashboard data into S3 (or Postgres or Redshift) and using a BI tool like Metabase or Quicksight to make it easy to create internal and external dashboards. Some of the delivery dashboards could be embedded in Gitbook.

Cool! I think that aligns with the general strategy/tasks proposed in these two milestones:

- [Delivery dashboard - Metrics](https://github.com/HHS/simpler-grants-gov/milestone/81) (corresponding 10k: #303)
- [Delivery dashboard - ETL](https://github.com/HHS/simpler-grants-gov/milestone/136) (corresponding 10k: #1269)

And @AlexanderStephensonUSDS is pretty close to finishing a good chunk of burnup/burndown metric tickets.

But I like the idea of setting up a metabase or quicksight dashboard that reads from S3 as the UI instead of jumping straight to a custom built dashboard application. There are some details that I'd love to talk through, but excited for this approach!
