### ISSUE TITLE
[Task]: Analytics - Add `BaseMetric.to_s3()` method

### ISSUE THREAD

**Issue by widal001** [HHS/simpler-grants-gov#1202]
### Summary

Create a `BaseMetric.to_s3()` method that can be used to post the results of a metric to an S3 bucket.

### Notes

Rather than initializing the S3 connection in this method, it should probably accept an `S3Connection` dependency or something similar which would be created and stored in the `analytics.integrations` sub-package.

We'll also need to think through if/how we want to preserve existing data in the s3 bucket when writing new data to it.

### Acceptance criteria

- [ ] An `S3Connection` or similar method has been created in `analytics.integrations` to manage the connection to S3 and the mechanics of writing data to an S3 bucket
- [ ] A `BaseMetric.to_s3()` class has been created which can post the results of a metric to S3 using an `S3Connection` dependency

**Comment by acouch** [comment]
Closing this as we have a similar approach but for postgres!
