### ISSUE TITLE
[Task]: Search Result Component

### ISSUE THREAD

**Issue by SammySteiner** [HHS/simpler-grants-gov#1221]
### Summary

Each opportunity returned by a search should be displayed in a reusable search result component that combines USWDS components and custom html.

Fields include (but may change):
* Title
* Opportunity number
* Agency
* Estimated funding
* Posting date
* Close date
* Status ( one of: Forecasted, Posted, Closed, Archived)

![image](https://github.com/HHS/simpler-grants-gov/assets/25465464/c5bca637-681b-4a53-a012-9396fc263d7a)

[Figma](https://www.figma.com/file/Zm7oIeBpwjrsXcmjV3K7HR/Search?type=design&node-id=4501-4952&mode=design&t=3Yo3tXNJKqgbI0av-4)

### Acceptance criteria

- Component for search results is visible in Storybook
- Tests

**Comment by SammySteiner** [comment]
I pointed this as a 5 because I'm assuming the design may change a bit in the next few weeks so that ambiguity increases the complexity for me.

**Comment by rylew1** [comment]
@chouinar - Low priority at the moment - but just looking ahead at tickets. Do we have all these fields in a somewhat ok shape if I was calling the real api?

**Comment by chouinar** [comment]
@rylew1 Of these values, opportunity status _could_ change, but that is something we'd need to run by a lot of people, several weeks out for that if it does change.
