### ISSUE TITLE
[Task]: Search Results List Component

### ISSUE THREAD

**Issue by SammySteiner** [HHS/simpler-grants-gov#1223]
### Summary

Create a component that takes the result data returned by the api and displays the results components in a list.

![image](https://github.com/HHS/simpler-grants-gov/assets/409279/1219d79e-a130-4fad-9368-d7ae47ae1758)

![image](https://github.com/HHS/simpler-grants-gov/assets/409279/59215748-5fde-4cb2-ba38-1771c62d7209)

**Comment by andycochran** [comment]
Closing this. I'll open new tickets for the remaining details.
