### ISSUE TITLE
[Task]: Search Results Pagination

### ISSUE THREAD

**Issue by SammySteiner** [HHS/simpler-grants-gov#1224]
### Summary

The search only shows a limited number of results at a time. The pagination is responsible for showing the user which "page" of the results are displayed and allow the user to query a different page from the API. Clicking on any number in the pagination component queries the API and when the query is returned the pagination component should show the updated page number.

Each request to the API must contain pagination information. Coordinate the data structure with @chouinar.

Use the uswds truss [pagination component](https://trussworks.github.io/react-uswds/?path=/story/components-pagination--sandbox)

<img width="550" alt="image" src="https://github.com/HHS/simpler-grants-gov/assets/25465464/7f6bdbdc-bec0-472d-82ae-54b1c0c02ceb">

[Figma](https://www.figma.com/file/lpKPdyTyLJB5JArxhGjJnE/simpler.grants.gov?type=design&node-id=2385-1056&mode=design&t=ENxZQAn2Yq3nqM9P-4)

**Comment by rylew1** [comment]
Completed as part of https://github.com/HHS/simpler-grants-gov/pull/1480
