### ISSUE TITLE
[Task]: Search Results Count

### ISSUE THREAD

**Issue by SammySteiner** [HHS/simpler-grants-gov#1226]
### Summary

Inform the user how many results came back from their search.

<img width="348" alt="image" src="https://github.com/HHS/simpler-grants-gov/assets/25465464/d644c4a4-a811-4809-8d9d-b8cfd5596a7d">

[Figma](https://www.figma.com/file/lpKPdyTyLJB5JArxhGjJnE/simpler.grants.gov?type=design&node-id=2476-2615&mode=design&t=67znx0U9hcWP0Yvm-4)

**Comment by sumiat** [comment]
done
