### ISSUE TITLE
[Task]: Search Results 0 Results

### ISSUE THREAD

**Issue by SammySteiner** [HHS/simpler-grants-gov#1227]
### Summary

Notify the user when their search returned zero results proactively, so they're not wondering if there was an error.

<img width="702" alt="image" src="https://github.com/HHS/simpler-grants-gov/assets/25465464/f4d415ee-7ab0-41ec-9f9a-15ae7a7b1937">

[Figma](https://www.figma.com/file/Zm7oIeBpwjrsXcmjV3K7HR/Search?type=design&node-id=4501-5043&mode=design&t=QILKn0LKOMlPikU3-4)

**Comment by sumiat** [comment]
related to #1492 and PR #1501
