### ISSUE TITLE
[Task]: Update Loader to Look Like Design

### ISSUE THREAD

**Issue by SammySteiner** [HHS/simpler-grants-gov#1228]
### Summary

Indicate to the user that we've sent a request to the api and are waiting on results.

Followup with design if:
* Include a delay so we're not constantly switching back and forth between results and loading?
* Loading while typing each character in the search bar?
* What icon/animation should we use?

<img width="466" alt="image" src="https://github.com/HHS/simpler-grants-gov/assets/25465464/d3231086-e55d-466e-8e63-b630bd0e9fe2">

[Figma](https://www.figma.com/file/Zm7oIeBpwjrsXcmjV3K7HR/Search?type=design&node-id=4501-4983&mode=design&t=QILKn0LKOMlPikU3-4)

**Comment by rylew1** [comment]
@crystabelrangel @andycochran - do we want to use the loader that's actually in figma?

**Comment by andycochran** [comment]
Oh, I left a note about this in an oooold version of the Figma… 

![image](https://github.com/HHS/simpler-grants-gov/assets/409279/60640613-2aa5-472a-a05d-cee12c69e3fb)

But I actually have another idea. I'll Slack you…

**Comment by acouch** [comment]
@andycochran can we move this to: https://github.com/HHS/simpler-grants-gov/milestone/155 since it is not a blocker?
