### ISSUE TITLE
[Task]: Analytics - Add ETL sub-commands to CLI

### ISSUE THREAD

**Issue by widal001** [HHS/simpler-grants-gov#1245]
### Summary

Update the `analytics` CLI to include entry points for the ETL functions created in this ticket #1022

### Notes

- We'll also probably want to re-work the other CLI commands that are "downstream" of the ETL commands so that they simply accept an input path to the file written by the ETL command which contains the input dataset
- Once these CLI changes are made we'll also need to update the commands in the [`Makefile`](https://github.com/HHS/simpler-grants-gov/blob/main/analytics/Makefile) and in the [GitHub action that runs the analytics pipeline](https://github.com/HHS/simpler-grants-gov/blob/main/.github/workflows/run-analytics.yml)

### Acceptance criteria

- [ ] Each of the ETL functions can be invoked from a CLI command, something like `poetry run analytics etl <etl_func_name>`
- [ ] These CLI commands accept paths to the source data and to the output location as inputs to the command
- [ ] Other CLI commands have been updated to use the output of the ETL commands instead of the paths to the source data (e.g. `poetry run analytics calculate sprint_burndown --dataset sprint-board.csv --sprint @current`)
- [ ] The `Makefile` and the GitHub action which runs the analytics pipeline have been updated to use these new commands

**Comment by acouch** [comment]
Closing this as we might not add the ETL part of the app in this body of work. Happy to discuss and reopen or move!
