### ISSUE TITLE
[Task]: Analytics - Add `BaseReport.export_to_s3()` method

### ISSUE THREAD

**Issue by widal001** [HHS/simpler-grants-gov#1246]
### Summary

Create a method that allows users to export the results and source data of a given `BaseReport` subclass to an S3 bucket, so that it can be used to populate the dashboard UI.

### Notes

- The person working on this should coordinate with the people working on #1234 and #1235 to make sure the structure of the S3 bucket adheres to a specific structure that the dashboard UI depends on.
- The person working on this should also coordinate with the person working on #1202 in order to identify the boundary between the export work handled at the report vs at the metric level

### Acceptance criteria

- [ ] Any sub-class of `BaseReport` can invoke an `export_to_s3()` method in order to export report data to an S3 bucket
- [ ] This method writes the following data elements to S3:
  - [ ] The results of metrics calculated in the report
  - [ ] The source data used to calculate those metrics
  - [ ] Summary statistics calculated about those metrics

**Comment by acouch** [comment]
Closing this as we have a similar approach but for postgres!
