### ISSUE TITLE
[ADR]: Dashboard UI web framework

### ISSUE THREAD

**Issue by widal001** [HHS/simpler-grants-gov#1249]
### Description

Evaluate and select a framework to build the user interface for the delivery dashboard. For context, we only anticipate needing to refresh the data in this dashboard 1-2 times per day. Because the dashboard will be public, we don't anticipate needing to support a logged in experience for the foreseeable future. 

### Approvers

- @acouch 
- @lucasmbrown-usds 
- @SammySteiner 

### Options

- Jupyter notebook
- Static site built with Next.js
- Static site built with Astro
- Dashboard app built with Dash
- Building a public dashboard using a BI tool like Looker (or open source alternative)
- Publishing the charts and metrics on a page on [simpler.grants.gov](http://simpler.grants.gov/) reading directly from the GitHub API or from pre-computed metrics written to S3
- Hosting a standalone dashboard static site in a separate repo on GitHub pages that reads pre-computed metrics from S3.

### Decision Criteria

- Building the dashboard UI requires minimal upfront investment
- The dashboard UI requires minimal ongoing maintenance and support
- We can scale the scope and complexity of the content in the dashboard without switching to a new tool
- We have control over the presentation, structure, and format of the dashboard UI
- The dashboard UI is built using frameworks that are similar to or compatible with other parts of our frontend stack

### Definition of Done

- [ ] The approvers for this decision have been identified (ideally before work on the ADR starts)
- [ ] The ADR is created and stored in `documentation/decisions/adr` with status "Accepted"
- [ ] The ADR has been reviewed and approved by the approvers listed above
- [ ] The ADR satisfies requirements that are outlined in the ADR template
- [ ] Any follow-up tickets have been created (if necessary)

**Comment by acouch** [comment]
We've chosen to use the existing frontend for https://github.com/HHS/simpler-grants-gov/issues/1367 and a BI tool for certain high-context visualizations.
