### ISSUE TITLE
[Task]: Search Results Filter Component

### ISSUE THREAD

**Issue by SammySteiner** [HHS/simpler-grants-gov#1250]
### Summary

This component contains a group of checkboxes to filter results returned by the search. 
Selecting a checkbox sends a new request to the search api for results.
Each group can be hidden.
Each group has a button to select all and to clear selection.

![image](https://github.com/HHS/simpler-grants-gov/assets/25465464/3e1e540b-1a8c-4f1b-8718-560c2ef8f16e)

[Figma](https://www.figma.com/file/Zm7oIeBpwjrsXcmjV3K7HR/Search?type=design&node-id=4501-4921&mode=design&t=6PtMDuf3Xb2rDeX8-4)

**Comment by rylew1** [comment]
Merged with this PR https://github.com/HHS/simpler-grants-gov/pull/1480
