### ISSUE TITLE
E: Add max width to 404

### ISSUE THREAD

**Issue by andycochran** [HHS/simpler-grants-gov#1254]
### Summary

The message on the 404 page has a very long line length which makes the text difficult to read and the layout seem unintentional. We should put a max width on that content so that the text wraps to multiple lines at a decent line length. 

Some USWDS guidance: 
>Most lines of text should be 45–90 characters. The current standard range for readable line length is 45 ([measure 1](https://designsystem.digital.gov/design-tokens/typesetting/measure/)) to 90 characters per line ([measure 5](https://designsystem.digital.gov/design-tokens/typesetting/measure/)). A good target for long texts is 66 characters ([measure 2](https://designsystem.digital.gov/design-tokens/typesetting/measure/)).
- https://designsystem.digital.gov/components/typography/#measure-line-length-2
- https://designsystem.digital.gov/design-tokens/typesetting/measure/

**Comment by emilycnava** [comment]
Picking up this
