### ISSUE TITLE
[Bug]: Feature flag page should be hidden in prod

### ISSUE THREAD

**Issue by SammySteiner** [HHS/simpler-grants-gov#1255]
### Summary

simpler.grants.gov/dev/feature-flags should route the user to the 404 page. 
this is attempted here: https://github.com/HHS/simpler-grants-gov/blob/5256754e3dbdd0ce8c980f165f214d608803b0f8/frontend/src/pages/dev/feature-flags.tsx#L12
But it's not working properly.

**Comment by acouch** [comment]
The FF page is hidden in prod, but keeping this open since that flag still exists in the code.
