### ISSUE TITLE
[Task]: Dashboard - Architecture diagram

### ISSUE THREAD

**Issue by widal001** [HHS/simpler-grants-gov#1265]
### Summary

Create an architecture diagram for the workflow used to calculate metrics and refresh the data in the dashboard.

### Acceptance criteria

- [ ] An architecture diagram has been added to the [`documentation/architecture/README.md`](https://github.com/HHS/simpler-grants-gov/tree/main/documentation/architecture) page
- [ ] This architecture diagram also is accompanied by a brief written summary of the steps involved in refreshing and publishing the dashboard.
- [ ] The relevant dashboard ADRs are also linked to the architecture section.

**Comment by coilysiren** [comment]
This sounds like a different diagram than the one mentioned here: https://github.com/HHS/simpler-grants-gov/issues/1558.

**Comment by coilysiren** [comment]
![Grants gov system architecture](https://github.com/HHS/simpler-grants-gov/assets/5768468/644960a2-f4d4-4b2d-859e-60ed95d19e78)

**Comment by coilysiren** [comment]
![Grants gov system architecture (1)](https://github.com/HHS/simpler-grants-gov/assets/5768468/15ac8a1e-f68c-4cdb-9a1b-e1e6c7302539)

**Comment by coilysiren** [comment]
pull request https://github.com/HHS/simpler-grants-gov/pull/1980
