### ISSUE TITLE
[Task]: Update Architecture Diagram

### ISSUE THREAD

**Issue by acouch** [HHS/simpler-grants-gov#1276]
### Summary

The [current architecture diagram](https://github.com/HHS/simpler-grants-gov/tree/main/documentation/architecture#architecture) is out of date (does not include database replication, contains a-z failover, among other issues). This task is to update it.

The original diagram was created in mermaid. The Nava template has a [lucid template that we may want to use moving forward](https://github.com/navapbc/template-infra/blob/main/docs/system-architecture.md#system-architecture). A diagram in lucid can better represent the architecture and easier to update as things get more complicated, though we can discuss as a group.

### Acceptance criteria

- [ ] Update diagram using mermaid or lucid

**Comment by coilysiren** [comment]
I definitely want to do this in LucidChart. Mermaid becomes unwieldy and frankly kind of ugly when used for an AWS infrastructure diagram

**Comment by coilysiren** [comment]
platform has an architecture diagram that can be used as a baseline: https://github.com/navapbc/template-infra/blob/main/docs/system-architecture.md

**Comment by coilysiren** [comment]
Working on this now

**Comment by coilysiren** [comment]
https://lucid.app/lucidchart/8d0fb4b2-fe85-4460-8df9-1255a506c5b6/edit?viewport_loc=-177%2C-500%2C3107%2C2505%2C0_0&invitationId=inv_a5fd77d9-d546-4b02-925a-6c3e254ccce7

**Comment by coilysiren** [comment]
![Grants gov system architecture - v1 0 0 (current) (2)](https://github.com/HHS/simpler-grants-gov/assets/5768468/c20a78e5-6a1d-4971-9632-0189152ebc77)

**Comment by coilysiren** [comment]
![Grants gov system architecture - v1 0 0 (current) (3)](https://github.com/HHS/simpler-grants-gov/assets/5768468/f3296ba5-61dd-4813-bdde-518577d7500b)

**Comment by coilysiren** [comment]
![Grants gov system architecture - v1 0 0 (current) (4)](https://github.com/HHS/simpler-grants-gov/assets/5768468/a7e8adb5-5e23-4623-9bda-66e34f437079)

**Comment by coilysiren** [comment]
![Grants gov system architecture - v1 0 0 (current) (5)](https://github.com/HHS/simpler-grants-gov/assets/5768468/619c46f2-3c38-4d46-a955-5ec938a9944a)

**Comment by coilysiren** [comment]
![Grants gov system architecture - v1 0 0 (current) (6)](https://github.com/HHS/simpler-grants-gov/assets/5768468/66f60cbe-fa91-45cb-80cf-47e4757cb54a)

![Grants gov system architecture - v1 0 0 (current) (7)](https://github.com/HHS/simpler-grants-gov/assets/5768468/75f9c471-61d3-4558-bb62-eb2625fb08b1)

**Comment by coilysiren** [comment]
FYI - these images are best viewed via downloading them first. That way you can zoom in, etc etc
