### ISSUE TITLE
Collect information for service blueprint of grants.gov grantor posting process

### ISSUE THREAD

**Issue by sumiat** [HHS/simpler-grants-gov#1284]
### Summary
This is going to be a large effort so we will want to limit the time we spend on it in this sprint. 

**What are we trying to learn:** 
- Get a better understanding of the current workflow of the existing grants.gov flow 
- What are the intended stages of the grantor posting process from HHS: how a grantor gets funding, draft state, official posting, editing a posting
- Understand the business logic and the legal requirements of posting an opportunity and/or what policies impact the business logic?
- What are the rules that are used for opportunity, synopsis, and forecast?

- Did Huge already do this?  

### Acceptance Criteria
- [x] Documentation of information collected from stakeholder interviewers or past research

### Notes
- Design can help collect or add information into documentation like a mural but this is a collaborative effort from product, design, engineering
- We don't know all the details of what's happening right now, and this work would help us understand how the workflow is currently used

### Out of scope
- How are people _actually_ using these rules/restrictions on how to post?

**Comment by crystabelrangel** [comment]
@sumiat I've started collecting info in this [Mural](https://app.mural.co/t/nava4113/m/nava4113/1708646488937/9a74d86ee8ea7b1304e05c04faa5137eb6167efa?sender=u0bc4965ce49cc21ca48b5266) and this [Doc](https://docs.google.com/document/d/1_hpZSF15wPsKOLMFGHq7VTgChu0tsEqP2erYFVaEt4U/edit?usp=sharing)

**Comment by crystabelrangel** [comment]
@sumiat I think we're at a point where it would be good to have a stakeholder interview. I've gathered what I could find from past research. Any thoughts on who to reach out to?

**Comment by sumiat** [comment]
Thanks @crystabelrangel - let me take a look at this! I'll let you know who we should connect with

**Comment by crystabelrangel** [comment]
Next steps is we need to have SME identified so we can move forward with next steps.

**Comment by sumiat** [comment]
AC is complete. Julius has mentioned that other members of the Grants PMO team would be good to talk to (Marc, Oscar). We could consider them for future interviews/input. We could complete that in a future follow on ticket and I can get a little tighter on scope for the business rules and logic we might need to understand as well.
