### ISSUE TITLE
[Task]:  Create cd-{app}-infra.yml which deploy from infra/{app}/**

### ISSUE THREAD

**Issue by coilysiren** [HHS/simpler-grants-gov#1288]
### Summary

Right now we have `cd-frontend` and `cd-api`, which deploy `frontend/**` and `api/**`. We should create an additional `cd-{app}-infra` that deploys on `infra/{app}/**` changes. This file should deploy its changes to `staging` and `prod`.

{app} is a variable that corresponds to the 3 applications we have defined in our infrastructure. Those applications are `api`, `frontend`, and `analytics`. That means we need the following new files:

- `cd-api-infra.yml`, which deploys on changes to `infra/api/`
- `cd-frontend-infra.yml`, which deploys on changes to `infra/frontend`
- `cd-analytics-infra.yml`, which deploys on changes to `infra/analytics`

### Acceptance criteria

- [ ] Github actions files created and tested
- [ ] The Github actions files account for deployments to **dev**, **staging**, and **prod**

**Comment by margaretspring** [comment]
@aplybeah - Is this still in review? Please update to Done or move to Sprint 22. Thank you!

**Comment by widal001** [comment]
Closing because issue was marked as 'Done' in https://github.com/orgs/HHS/projects/13
