### ISSUE TITLE
[Task]: Update `cd-*` scripts to deploy staging

### ISSUE THREAD

**Issue by coilysiren** [HHS/simpler-grants-gov#1291]
### Summary

The existing `cd-api`, `cd-frontend`, `cd-analytics` scripts should also deploy staging.

~Discuss with the team around whether or not they should _**also**_ continue to deploy dev.~ done!

### Acceptance criteria

- [ ] the `cd-*` scripts have been updated to deploy staging

**Comment by coilysiren** [comment]
Determination:

We want to deploy dev via a different Github Actions CD file than we deploy staging. This is because we want to be able to conditionally disable dev deploys in order to test scripts in a live environment.

**Comment by aplybeah** [comment]
Update: 
Working on adjusting some of the logic that deploys to a particular environment
aka this line &darr;
```      environment: ${{ inputs.environment || (github.event_name == 'release' && 'prod') || 'dev' }}```

Most likely will need to do something similar to the method used in the `*-ci-infra` PR

**Comment by aplybeah** [comment]
Moving back to `in progress` to test something
