### ISSUE TITLE
[Task]: Setup flow for API calls part 2

### ISSUE THREAD

**Issue by sumiat** [HHS/simpler-grants-gov#1294]
### Summary

Part 1 => #1282 (setup the basic flow for API calls)

Part 2 will continue this work (separating the two PRs to keep things smaller):

- Connect mock data to page => `frontend/src/api/mock/APIMockResponse.json`

- Make sure frontend to API URL is being called and generated correctly if using `APISearchFetcher`

- Investigate using real interface for search response data, or continue to use a generic type to allow for API response revisions/updates. Some current types we have from part 1:
```export interface JSONRequestBody {
  [key: string]: unknown;
}
export interface JSONRequestBody {
  [key: string]: unknown;
}

    export interface SearchResponseData {
         opportunities: unknown[];
    }
```

- Add version property to `BaseApi` (currently `0.1`) 
- Cleanup any TODO comments from part 1

### Acceptance criteria
- Mock data showing in results (demo)
- Local to local API working 
      - stretch => demo local to local call in PR
 -  All todo comments tied

**Comment by rylew1** [comment]
@chouinar we need to generate auth keys as part of calling the api in this ticket. Not sure if you want a ticket for this or if its just kind of a quick thing we do async

as I understand we just pass a header `X-Auth <token>`
