### ISSUE TITLE
[Task]: Add API URL to frontend

### ISSUE THREAD

**Issue by sumiat** [HHS/simpler-grants-gov#1295]
### Summary

follows from #1294:

- Investigate whether we want to use next.js env variable files `.env.local` , `.env.development` 
    - Or use  new files created in `frontend/config/<env-name>.js`
- New env specific files should have `apiURL`

`apiUrl`:
- Dev: http://api-dev-1839587515.us-east-1.elb.amazonaws.com/docs
- Staging: http://api-staging-770293556.us-east-1.elb.amazonaws.com/docs
- Prod - load balancer is currently giving a 502, but that might be intentional (there might be a ticket open to name to something using the actual grants.gov website

### Acceptance criteria

- [ ] Loading env specific API url 
- [ ] Stretch: ADR documenting choice

**Comment by coilysiren** [comment]
Prod is http://api-prod-342430507.us-east-1.elb.amazonaws.com/docs
