### ISSUE TITLE
[30k]: Collaborative code challenge

### ISSUE THREAD

**Issue by widal001** [HHS/simpler-grants-gov#130]
### Key links

- Deliverable specification
- [Simpler Grants.gov full roadmap](https://github.com/orgs/HHS/projects/12)
- [10k milestones](https://github.com/orgs/HHS/projects/13/views/11?sliceBy%5Bvalue%5D=Opportunity+listing+hackathon)

### Description

- **What:** Host a public event in which open source contributors are invited to submit code for an updated opportunity listing page
- **Why:** Builds excitement within the open source community and allows us to incorporate new ideas and code from members of the public
- **Who:**
  - Open source contributors
  - Prospective applicants

> [!NOTE]
> For more information about this deliverable, please refer to the deliverable specification linked above.

**Comment by widal001** [comment]
Updated the ticket format to reduce discrepancies with the deliverable spec.

**Comment by sumiat** [comment]
**Weekly Update 5/8**

**What has been done?**
- Code challenge deliverable spec has been drafted, reviewed by Nava internal and by Sarah and Billy 
- Code challenge tech spec has been drafted
- Tech spec reviewed in 30k review session

**Status**
- Planning

**Risk**
- We want to start work on this asap as the event is planned for July. Risk would be any delay in deciding on scope and budget


**Deliverable Date**
- TBD - planning for the event to be in july and 2 sprints more to complete the retro and future engagements documentation

**What will be done?**
- HHS / A6 to review the tech spec doc: https://docs.google.com/document/d/1vvoMQ7M7ajKQPA6SaNOVytsjluev1Xpc9m-y8JLtTFs/edit
- Get a more ready / approved state of the tech spec 
- Get a budget amount to Lucas, after aligning if internal travel costs need to be accounted for

**Comment by widal001** [comment]
Replacing our old deliverable tickets with a new ticket format
