### ISSUE TITLE
Search UI – research participant recruiting with internal HHS stakeholders

### ISSUE THREAD

**Issue by andycochran** [HHS/simpler-grants-gov#1302]
### Summary

Screen and schedule internal HHS participants for usability test sessions.

### Acceptance criteria

- [ ] A number of internal HHS participants have been scheduled for tests, according to the research plan

Blocked by #891

**Comment by crystabelrangel** [comment]
Waiting to find out more about when Search Index will be implemented to move forward with user testing.
