### ISSUE TITLE
Search usability testing with HHS internal stakeholders

### ISSUE THREAD

**Issue by andycochran** [HHS/simpler-grants-gov#1303]
### Summary

Conduct usability test sessions with 2-4 HHS internal stakeholders. These sessions would be about 60 min per session and there would need to be 2 people (a notetaker and facilitator)

### Acceptance criteria

- [x]  A number of tests have been conducted with HHS internal stakeholders, according to the research plan

### Out of scope
- Plan and synthesis are in separate tickets

### Notes
- This ticket will be split into multiple tickets for each interview

**Comment by sumiat** [comment]
Kamino cloned this issue to [HHS/grants-equity](https://github.com/HHS/simpler-grants-gov/issues/1878)

**Comment by andycochran** [comment]
All of the Search UI usability testing falls under the "Engagement sessions" deliverable. We do not need user feedback to meet the AC of the "Search" deliverable.
