### ISSUE TITLE
[Task]: Desk research against evaluation criteria: dbt

### ISSUE THREAD

**Issue by jamesbursa** [HHS/simpler-grants-gov#1306]
### Summary

Research dbt https://docs.getdbt.com/ and document how it meets the criteria in #1299.

### Acceptance criteria

 - [ ] Document the evaluation of DBT

**Comment by acouch** [comment]
We detailed in our internal doc what the dbt incremental modeling looks like and how we would apply it to our use case:

![image](https://github.com/HHS/simpler-grants-gov/assets/512243/e85f22bd-73a5-40a7-ad90-4963392ff30c)
