### ISSUE TITLE
[10k]: API security documentation

### ISSUE THREAD

**Issue by widal001** [HHS/simpler-grants-gov#131]
### Description

Develop a plan for securing the public API. While the broader AuthN and AuthZ framework will be designed and implemented in a different set of milestones, this plan should account for applying basic security measures to the initial set of endpoints we will be deploying.

### Business Value & Goals

The purpose of this body of work is to:

- Ensure that our proposed infrastructure for the API satisfies the conditions necessary to be approved under a security impact analysis (SIA) with HHS
- Develop a short and long-term strategy for implementing security measures, such as rate limiting and incident response
- Evaluate and determine if there's a need for basic authentication mechanisms, such as API keys, in the interim while a more robust AuthN/AuthZ strategy is being developed

### Sub-Tasks

Sub-tasks for this 10k can be tracked in [this milestone](https://github.com/HHS/simpler-grants-gov/milestone/104).

### Definition of Done

- [x] Our API infrastructure has undergone an SIA with the HHS security team and incorporated the feedback from that review
- [x] Existing documentation on our security measures and incident response has been updated to reflect the details related to our API

**Comment by acouch** [comment]
There is a milestone for helping to create a plan here https://github.com/HHS/grants-equity/milestone/63

**Comment by sumiat** [comment]
Have a question on https://github.com/HHS/simpler-grants-gov/issues/624 - will discuss on 12/20

**Comment by sumiat** [comment]
@acouch will split this out more

**Comment by sarahknoppA6** [comment]
We acknowledge security review and approval may take more time than planned.

**Comment by widal001** [comment]
The security control implementation was broken out into its own 10k deliverable: #971

**Comment by acouch** [comment]
The documents have been sent and are being reviewed. Leaving this one open for now until that process has been completed.

**Comment by sumiat** [comment]
This work can be closed!
