### ISSUE TITLE
[Task]: Unblock Pending Alerts Email

### ISSUE THREAD

**Issue by acouch** [HHS/simpler-grants-gov#1312]
### Summary

The alerts email is stuck in confirmation.

It is confirmed that this email works internally. However we aren't receiving the email from AWS:

![image](https://github.com/HHS/simpler-grants-gov/assets/512243/6b41c6fe-1812-46c1-9bd3-e7e8fe9d080f)

### Acceptance criteria

- [ ] Unblock alerts email so it can be received

**Comment by aplybeah** [comment]
@acouch confirming that I received emails
