### ISSUE TITLE
[Task]: SME interview with Amanda Aguirre for PAC

### ISSUE THREAD

**Issue by rishalee** [HHS/simpler-grants-gov#1315]
### Summary

Risha and Lucas to meet with Amanda Aguirre to discuss PAC plans and participant candidates

### Acceptance criteria

- Notes from meeting
- Meeting logged in SME spreadsheet

**Comment by widal001** [comment]
Closing because issue was marked as 'Done' in https://github.com/orgs/HHS/projects/13
