### ISSUE TITLE
Set the backend's load balancer URLs as environment variables on the frontend container

### ISSUE THREAD

**Issue by coilysiren** [HHS/simpler-grants-gov#1327]
### Summary

Configure terraform so that the output for the frontend's load balancer URL is input into the frontend's environment variables

Here's a guide on how to do this: https://developer.hashicorp.com/terraform/language/state/remote-state-data. The guide includes some alternatives you may want to consider, such as using an AWS SSM Parameter.

### Acceptance criteria

- [ ] output for the backend's load balancer URL in `infra/api/service`
- [ ] import it into the state in `infra/frontend/service`
- [ ] set the load balancer URL as an environment variable on the frontend container

**Comment by rylew1** [comment]
@coilysiren  Interesting - are we doing this currently for any other env variables? I would guess I'm just calling `process.env.apiUrl` from javascript then

**Comment by coilysiren** [comment]
@rylew1 

> are we doing this currently for any other env variables?

No, but we are using SSM parameters for something similar enough. It would be a new pattern for this repo, but isn't fundamentally complex.

> This would be dynamic apiUrl if the LB URL changed?

Yes. That's why I want to set it up this way.

**Comment by lorenyu** [comment]
My 2️⃣ cents is that using remote state or SSM is a bit over engineered for this use case. I’d just hard code it as a config value. I can show you how we do this on another project but won’t link here since that project isn’t public.
