### ISSUE TITLE
[Task]: Obtain tool for storing participant PII

### ISSUE THREAD

**Issue by rishalee** [HHS/simpler-grants-gov#1341]
### Summary

- We finalized the tool for viewing and storing PAC member contact information and affiliation in this ADR: https://github.com/HHS/simpler-grants-gov/blob/1abd0c39a73a6ad876d573e52f3ee89339dc644b/documentation/decisions/adr/2023-11-14-design-research-tools.md. We need to procure the tool now so that we can start using it

### Acceptance criteria

- Tool has been procured and ready for the team to start using

**Comment by sumiat** [comment]
@kw-MH assigning this ticket to you

**Comment by widal001** [comment]
Closing because issue was marked as 'Done' in https://github.com/orgs/HHS/projects/13
