### ISSUE TITLE
[Task]: Public Dashboard Design Discovery

### ISSUE THREAD

**Issue by andycochran** [HHS/simpler-grants-gov#1367]
### Summary

Create a Figma mockup for a dashboard page on simpler.grants.gov. 

Consider including: 

- Roadmap (data pulled from GitHub Project)
  - Done
  - Current
  - Upcoming 
- Site Usage (from Google Analytics)
- API data
  - Opportunity counts: forecasts, accepting apps, closed/archived
  - e.g. Most popular opportunities returned 
- Search UI metrics 
  - popular Keywords
  - Filters used
  - pagination 
  - etc
- Basic G.gov analytics for reference (from GA) 
- Count of newsletter subs

### Acceptance criteria

- [ ] Define what's included in the dashboard and understand what information the public is interested in seeing
- [ ] Collect information around what should be included in the dashboard

### Notes
- Consider talking to stakeholders/internal team like engineers to understand what's possible, Grants PMO, 
- @chouinar has information around opportunity/forecast data that would be 
- Follow on ticket to create a rough draft dashboard Figma mockup for review

**Comment by andycochran** [comment]
Noting that there'll likely be a more nascent version of a delivery dashboard to address more immediate needs, and this issue is intended to put more design thinking into the longer-term solution.

**Comment by widal001** [comment]
@andycochran In terms of the main metrics we (i.e. the P&D team) need I've included them in the following tickets:

**Visual examples of these metrics:**

- [Dashboard - Sprint details dashboard page](https://github.com/HHS/simpler-grants-gov/issues/1207)
- [Dashboard - Deliverable details dashboard page](https://github.com/HHS/simpler-grants-gov/issues/1210)
- [Dashboard - Sprint details dashboard page](https://github.com/HHS/simpler-grants-gov/issues/1207)

**Tickets to calculate the metrics:**

- [Analytics - Sprint burnup](https://github.com/HHS/simpler-grants-gov/issues/1018)
- [Analytics - Deliverable burndown](https://github.com/HHS/simpler-grants-gov/issues/1186)
- [Analytics - Deliverable burnup](https://github.com/HHS/simpler-grants-gov/issues/1184)
- [Analytics - Sprint percent complete](https://github.com/HHS/simpler-grants-gov/issues/1185)

**Plus the existing metrics we already have**

- [Sprint Burndown](https://github.com/HHS/simpler-grants-gov/blob/main/documentation/analytics/metrics/burndown.md)
- [Deliverable percent complete](https://github.com/HHS/simpler-grants-gov/blob/main/documentation/analytics/metrics/percent-complete.md)

**Comment by crystabelrangel** [comment]
Created lo-fi wireframes of dashboard ideas - see [Figma file](https://www.figma.com/file/OyK3MhVf4TH0YHCif03VQG/Dashboard?type=design&node-id=0%3A1&mode=design&t=9Gv03LqEp92J2h0G-1)
Next steps: work with Emily to identify internal HHS staff/stakeholders to discuss options, followed by identifying external participants to identify the most important metrics.
