### ISSUE TITLE
[Task]: Set up custom domain for public wiki

### ISSUE THREAD

**Issue by btabaska** [HHS/simpler-grants-gov#1375]
### Summary

 Configure a custom domain for our public wiki to reinforce brand identity and improve accessibility for users, replacing the default domain provided by GitBook.

### Acceptance criteria

- Domain Selection and Registration: Identify and register a suitable custom domain that aligns with the project's branding and is easy for users to remember.
- Platform Configuration: Update the wiki hosting platform settings to recognize and use the custom domain, ensuring seamless access to the wiki content.
- Redirection Setup: Implement redirects from the old default domain to the new custom domain to prevent access issues and maintain search engine rankings.
- Testing and Validation: Conduct thorough testing to verify that the custom domain is correctly pointing to the wiki, that secure connections are established, and that redirects function as intended.
- Update External Links: Identify and update external links and references to the wiki to use the new custom domain, ensuring consistency across communications.

**Comment by widal001** [comment]
@btabaska I can support on this when you get to it! We set up a custom domain for our HHS comms site in GitBook and the most involved step is getting the HHS team to configure the DNS record correctly.

**Comment by widal001** [comment]
Closing because issue was marked as 'Done' in https://github.com/orgs/HHS/projects/13
