### ISSUE TITLE
[Task]: Evaluate pushing from Oracle to Postgres

### ISSUE THREAD

**Issue by acouch** [HHS/simpler-grants-gov#1388]
### Summary

There is a proposal to push form Oracle to Postgres instead of using the foreign data wrapper. There are a few benefits of having this synchronization process within the MH environment:

Simplified Security: removes external access into the [Grants.gov](http://grants.gov/) Production environment
Less work on the Simpler side: by synchronizing the data internally into Aurora we can use logical replication to automatically push table changes to their database (AWS blocks this ability on Oracle)
Better logging on the production side: we have better visibility into the metrics and can adjust for performance on a per table basis
We can start with this simple synch for a small number of tables, then simply switch to DMS if the need increases, implementing it as a replication (push) process rather than pulling data externally

### Acceptance criteria

- [ ] evaluate proposal and comment in this ticket

**Comment by acouch** [comment]
This is still on progress for this sprint. Working on #1299 first

**Comment by bretthrosenblatt** [comment]
The reason I suggested this approach is because it makes it much easier for Simpler to replicate the rest of grants.gov much more easily. It's much harder to migrate from the outside.

**Comment by acouch** [comment]
We discussed this this morning and decided to focus on the pull approach as we own that part of the pipeline but can revisit in the future.
