### ISSUE TITLE
[Bug]: Chevron icon accessibility 

### ISSUE THREAD

**Issue by andycochran** [HHS/simpler-grants-gov#1396]
### Summary

On the [Process page](https://simpler.grants.gov/process), under the "The high-level roadmap" section, the headings… 

> Find › Milestone 1

> Find › Milestone 2

…use icons for the "›" (right-facing chevron) with `aria-label="launch"`.  This alt text lead assistive technology to reach the line as "Find Launch Milestone [1, 2]." 

Possible solutions: 
- Hide the icon from screen readers
- Change the alt text to ":" or "›" or a dash or something that makes sense (consult w/ design on this)

### Acceptance criteria

- [ ] The icons have been marked as decorative, or the alt text has been updated so that it makes sense for screen readers

**Comment by doug-s-nava** [comment]
It looks like this is no longer an issue and was likely fixed here

https://github.com/HHS/simpler-grants-gov/commit/3df946263718a5bc13c0e11990911e4c9586e674#diff-a328510138157a8496f3c1c382129dbb281adc1dfc4030bc225b1741c9c11561L93

Closing
