### ISSUE TITLE
[Task]:  Add New Relic Infrastructure Diagram

### ISSUE THREAD

**Issue by coilysiren** [HHS/simpler-grants-gov#1404]
### Summary

Add New Relic to the existing Infrastructure Diagram: https://github.com/HHS/simpler-grants-gov/tree/main/documentation/architecture#aws-hosted-infrastructure

### Acceptance criteria

- [ ] New Relic is in the diagram :)

**Comment by acouch** [comment]
This would be a sub-section of #365

**Comment by acouch** [comment]
This is was completed in #1276

**Comment by acouch** [comment]
Never-mind, there was a draft in #1276 that had New Relic in it, but the current one (rightly so, doesn't have it as we haven't implemented it yet). The work is staged.

**Comment by widal001** [comment]
Closing because issue was marked as 'Done' in https://github.com/orgs/HHS/projects/13
