### ISSUE TITLE
[Task]: Delivery Dashboard discovery - deploy AWS Quicksight

### ISSUE THREAD

**Issue by coilysiren** [HHS/simpler-grants-gov#1410]
### Summary

We want to evaluate using [AWS QuickSight](https://aws.amazon.com/quicksight) as a BI tool for both internal and external facing dashboards.

Data to test with: [issue-pr-data.zip](https://github.com/HHS/simpler-grants-gov/files/14513684/issue-pr-data.zip)

## Steps

1. Create an instance of QuickSight in our dev environment
2. Notify the `#topic-security` channel that this may be flagged in our scanning
3. Upload the attached CSV files
4. Create a sprint burndown chart (see `analytitcs` folder for query details)
5. Create a chart for 30k planning (see `analytitcs` folder for query details)
6. Add charts to dashboard and share publicly (or whatever combo of features this entails in QuickSight) 
7. Share dashboard and demo tool if requested
8. Destroy instance

### Acceptance criteria
- [x] Instance created
- [x] Dashboard (or equivalent created and shared)
- [ ] Instance destroyed (if we don't use it permanently)

**Comment by acouch** [comment]
I created a Quicksight account and uploaded the attached datasets
