### ISSUE TITLE
Define Co-Design Group term duration and number of participants

### ISSUE THREAD

**Issue by widal001** [HHS/simpler-grants-gov#1415]
### Summary

- Define how long the first cohort will last
- Define how many participants there will be

### Acceptance criteria

- [x] Numbers have been suggested by Nava
- [ ] HHS/MH have agreed to the amount, considering budget and staff capacity

**Comment by rishalee** [comment]
- 12-24 participants have been suggested for first cohort
- duration of time between 6-12 months has been suggested

**Comment by widal001** [comment]
Lucas suggested starting with 12-24 participants for 6 months (then reassessing for the second cohort) in [this slack thread](https://betagrantsgov.slack.com/archives/C05T74HRWRL/p1715182121415389?thread_ts=1715181676.039999&cid=C05T74HRWRL)

**Comment by margaretspring** [comment]
@rishalee Please loop me in as I'll need to get budgeting approved by Julius. Thank you!

**Comment by andycochran** [comment]
Approved by Lucas 9/25
