### ISSUE TITLE
Draft requirements for budget and compensation strategy for participants

### ISSUE THREAD

**Issue by widal001** [HHS/simpler-grants-gov#1416]
### Summary

We have determined an initial range for the budget. We want to have a budget and compensation strategy for the PAC engagement. 

### Acceptance criteria

- [ ] Determine what are the requirements from leadership for a compensation budget for the PAC

### Open questions / notes
- Are there any other groups that we need to compensate? For example, our assumption is that we would not compensate API consumers and grantors

**Comment by rishalee** [comment]
Item is clarified elsewhere
