### ISSUE TITLE
Budget approval requirements for HHS approval

### ISSUE THREAD

**Issue by widal001** [HHS/simpler-grants-gov#1417]
### Summary

A budget range has been determined. We want to send the budget to HHS for approval. We need to determine if there is anything required from HHS and send the budget request to HHS for approval. 

### Acceptance criteria

- [ ] Determine if there is any information/proposal detail requirements that are required for the budget
- [ ] If so, create a ticket for the budget proposal that needs to be created.

**Comment by rishalee** [comment]
Item has been clarified elsewhere
