### ISSUE TITLE
PAC names sent for approval

### ISSUE THREAD

**Issue by widal001** [HHS/simpler-grants-gov#1420]
### Summary

- Create a list of names for the PAC
- Relevant stakeholders are sent the PAC name for voting

### Acceptance criteria

- [x] List of final options for the PAC
- [x] Sent to leadership and relevant stakeholders to approve

**Comment by rishalee** [comment]
New name: Co-Design Group approved by Lucas Brown on 4/8/24 @margaretspring

**Comment by margaretspring** [comment]
@rishalee This appears to not be totally closed as MH indicated a preference for User Feedback Group during the 4/8 Comms mtg. I'll re-open & assign to myself to follow up on at the 4/11 SGG Leads mtg.
