### ISSUE TITLE
Determine tools participants will need to participate and associated costs

### ISSUE THREAD

**Issue by widal001** [HHS/simpler-grants-gov#1423]
### Summary

See what tools have been used for the open source community and determine what tools should be used for the Co-Design Group. 

Open source community uses the following: 
- Slack - for chat
- Zoom - for meeting
- GitHub - for repo
- GitBook/Public wiki - for documentation 
- Google Groups - quasi-email 

### Acceptance criteria

- [ ] TODO add acceptance criteria

**Comment by mxk0** [comment]
This was discussed last week; participants either won't need the same tools as the open source community, and if they do they can use the free version.
