### ISSUE TITLE
Check NDA requirement

### ISSUE THREAD

**Issue by widal001** [HHS/simpler-grants-gov#1425]
### Summary

Check if the NDA is required for the PAC

### Acceptance criteria

- [x] validate if NDA is required for the PAC
- [ ] create a ticket to draft an NDA, if needed

**Comment by sumiat** [comment]
I checked here: https://betagrantsgov.slack.com/archives/C06KSF8RTS6/p1709768090649329; Determined that NDA is not necessary as far as we know now.
