### ISSUE TITLE
Define PAC involvement in participatory budgeting

### ISSUE THREAD

**Issue by widal001** [HHS/simpler-grants-gov#1429]
### Summary

TODO add summary

### Acceptance criteria

- [ ] TODO add acceptance criteria

**Comment by rishalee** [comment]
@lucasmbrown-usds is this ticket still needed?

**Comment by rishalee** [comment]
Closing based on @lucasmbrown-usds directive over slack: 

i think, based on the feedback from the onsite that we've crosspollinated too many things that are still starting up, we're going to decouple these.
[@Elizabeth Crews](https://betagrantsgov.slack.com/team/U06F9U9NME0)
 -- any thoughts on this? do you want to officially decouple risha's co-design group (formerly called the PAC) from the nascent participatory budgeting efforts?

cf: https://betagrantsgov.slack.com/archives/C05T74HRWRL/p1712948553334539
