### ISSUE TITLE
Security for PII for Ethnio tool

### ISSUE THREAD

**Issue by widal001** [HHS/simpler-grants-gov#1439]
### Summary

Understand if there are any security or SIA requirements for storing PII in Ethnio

### Acceptance criteria

- [x] Understand if there are any security requirements for Ethnio to be used on the project
- [x] SIA/security approval for storing PII data in Ethnio ticket created

**Comment by sumiat** [comment]
checking here https://betagrantsgov.slack.com/archives/C05T74HRWRL/p1709758123220399?thread_ts=1709743422.609749&cid=C05T74HRWRL

**Comment by sumiat** [comment]
Lucas and Julius are checking on this

**Comment by sumiat** [comment]
SIA is needed and will be added tracked separately
