### ISSUE TITLE
Draft Statement of expectations for participants - describe expectations for involvement in the PAC

### ISSUE THREAD

**Issue by widal001** [HHS/simpler-grants-gov#1441]
### Summary

The first draft of the statement of expectations that we send to PAC participants is created and ready to send the first draft to execs to start the approval process. 

### Acceptance criteria

- [ ] Statement of expectations for involvement in the PAC drafted - leave placeholders for information we do not currently know

**Comment by rishalee** [comment]
@margaretspring this document is ready to be passed to MH

**Comment by margaretspring** [comment]
@rishalee - I'm guessing there's nothing confidential in the statement that needs approval (Pls correct if I'm wrong). Please link here & advise on who from MH would approve so we can get it on their radar. 

@CarleyKimball @alexis-bunc - please advise if you have any guidance. Thank you!

**Comment by alexis-bunc** [comment]
@margaretspring Carley and I can both take a look at this! @rishalee are you able to send over to us? Thank you!

**Comment by rishalee** [comment]
Shared directly with @alexis-bunc and @CarleyKimball https://docs.google.com/document/d/1sMsvH6nUbs9sGraXWCI1fv9lM37IMpk2RxB5jDDWL9M/edit#heading=h.c64if89c36as

**Comment by CarleyKimball** [comment]
Added some comments that will need addressed prior to distribution @rishalee
