### ISSUE TITLE
[Task]: Implement query filtering to the search endpoint

### ISSUE THREAD

**Issue by chouinar** [HHS/simpler-grants-gov#1455]
### Summary

As part of the search endpoint we are building out, we want to support a generic text box that a user can populate and it queries several different fields in the database. However, exactly how this works has to be sorted out and then implemented.

From the designs, it seems we want it to roughly query against the following (but I want to confirm this):
* Assistance listing numbers (formerly CFDAs) -exact
* Assistance listing program names?
* Opportunity title - contains
* Opportunity number - contains
* Summary description - contains
* Agency code - contains
* Agency name - not sure - might not have the right value to query against
* Anything else?

Additionally, do we need to consider anything regarding how the queries work against the DB?
* Only support contains / exact match (case-insensitive)?
* Something with regexes?
* What happens if a user enters `health 05.005` - this likely means they want to search health against one field (like the description), but search the numeric value against the assistance listing. Is this something we need to support now?

I'd prefer to keep this somewhat simple now, as a search index in the future _just does a lot of this_ and it likely is better to build that out than spend too much time on this approach.

### Acceptance criteria

- [ ] Query filtering is implemented as agreed

**Comment by chouinar** [comment]
It might also be good to get some product thought on this - there are technically some very elaborate ways of building out a query approach in a Postgres database, _but_ they would require a lot of setup. Is it better to go very simple now so that we can get to building out a search index sooner, or build something more elaborate here now?

**Comment by crystabelrangel** [comment]
Assistance listing numbers (formerly CFDAs) - exact match. Partial may not make sense for now e.g. if someone searches 01 then they may get too many
Assistance listing program names - contains
Opportunity title - contains
Opportunity number - contains
Summary description - contains
Agency code - partial
Anything else?
Will not have Agency name
if someone types [keyword] [opp num] it will not return anything. This will be handled with search index
