### ISSUE TITLE
[Task]: Disable select all when all selected. Disable clear all when none selected. 

### ISSUE THREAD

**Issue by rylew1** [HHS/simpler-grants-gov#1491]
### Summary

Disable select all when all selected. Disable clear all when none selected.  Can likely set the `disabled` prop (or attribute) here.

### Acceptance criteria

- You can't `Select All` twice in succession
- You can't `Clear All` twice in succession

**Comment by rylew1** [comment]
cc @crystabelrangel @andycochran

**Comment by andycochran** [comment]
You should be able to just add the `disabled` attribute (prop?) to the button component.
