### ISSUE TITLE
[Task]: Stakeholder interview prep for the dashboard

### ISSUE THREAD

**Issue by sumiat** [HHS/simpler-grants-gov#1496]
We started to explore different dashboards that would be useful to the general public on the simpler.grants.gov site. We want to understand which "dashboards" would be most useful with users. 

### Acceptance Criteria

- [x] Create a template or questions for stakeholder interviews with users to understand what metrics and information about the grants process is most instructive for applicants
- [x] List of 3-5 users to interview (must be less than 9 to be PRA compliant), list of a couple stakeholders to interview
- [x] Approved by MH
- [x] Approved by HHS
- [x] ~Schedule interviews~ Moving to #1608 
- [x] ~Create tickets for the interviews~ Moving to #1608 

### Notes
- @itsemilyianacone will provide list of people to interview from the Simpler NOFO effort
- will be using the low-fi dashboards that were created in #1367

**Comment by crystabelrangel** [comment]
@andycochran @rishalee here is the draft of the interview questions for the dashboard. [Dashboard research doc](https://docs.google.com/document/d/1dniLaJHv8uaIU2BiZXTp_biRtdGZCp809Dcyv4nLYFI/edit?usp=sharing)
Take a look and feel free to make any edits/suggestions.

Up next we need to have a list of people we will reach out to to send to MH for their approval. Then we can move forward with scheduling interviews.

**Comment by andycochran** [comment]
This ticket was for prep. Created #1608 for scheduling/conducting

**Comment by crystabelrangel** [comment]
Sent to Emily for review/approval today, 4/8/2024.

**Comment by widal001** [comment]
Closing because issue was marked as 'Done' in https://github.com/orgs/HHS/projects/13
