### ISSUE TITLE
Revise the Process page to remove or update stale roadmap elements

### ISSUE THREAD

**Issue by sumiat** [HHS/simpler-grants-gov#1497]
Once we release the search experience, we will want to update the roadmap information on the simpler.grants.gov process page: https://simpler.grants.gov/process as the current milestones will become outdated.

Considerations: 
- We may want to consider how this roadmap could be more easily updated in the future, how the general public can get involved in the roadmap. 
- This roadmap content could be its own page separate from the current "process" page  

### Acceptance Criteria
- [ ] Decision made on what to do with the roadmap information on the website

**Comment by mxk0** [comment]
Closing in favor of #2865
