### ISSUE TITLE
[Task]: Refactor useSearchFilter logic 

### ISSUE THREAD

**Issue by rylew1** [HHS/simpler-grants-gov#1498]
### Summary

- Started a class in #1491 `SearchFilterManager` that should keep track of the total checked count, the checked count in each section

- maybe rename it to `useSearchFilterAccordion` to be more accurate

- Should the class be in the same file as the custom hook?

### Acceptance criteria

- code in `useSearchFilter` is more organized

**Comment by acouch** [comment]
@rylew1 is this a launch blocker or "nice to have?" Can we move it to https://github.com/HHS/simpler-grants-gov/milestone/155 if it is the latter?

**Comment by acouch** [comment]
The search filter was changed dramatically with [#2067](https://github.com/HHS/simpler-grants-gov/issues/2067) . Closing. We can reopen later if desired.
