### ISSUE TITLE
[Task]: Setup design with local to local search UI

### ISSUE THREAD

**Issue by rylew1** [HHS/simpler-grants-gov#1504]
### Summary

Design needs to UAT/verify the search as we're building this  (since we don't have the search setup in one of the lower envs or prod to test - and the API is still on `v0` in stage/prod - we have to test local to local)

Design already has the frontend running with mock data, but we want to set them up with the frontend pointing to the local API.

### Acceptance criteria

- Design is able to see local to local search

**Comment by rylew1** [comment]
cc @sumiat @andycochran

**Comment by crystabelrangel** [comment]
Sure! I'd be interested @andycochran !

**Comment by widal001** [comment]
Closing because issue was marked as 'Done' in https://github.com/orgs/HHS/projects/13
