### ISSUE TITLE
[Task]: Fix pagination reset issue

### ISSUE THREAD

**Issue by rylew1** [HHS/simpler-grants-gov#1505]
### Summary

**Problem:** If the number of pages reduces when query parameters are changed, it is possible for the currently viewed page number to be higher than the new query's max number of pages. 

**Solution:** Regardless of which page number the user is currently viewing, when they change any status, filter, query terms, or sorting option, the UI should:

- Search the API with the new criteria but `page_offset` reset to 1
- Reset the pagination's current page to 1
- Clear the pagination query param (if it exists / they were viewing a page >1 before changing their query)

Secondary problem: The pagination state also has to be lifted to fix the top and bottom pagination being out of sync

### Acceptance criteria

- Pagination properly "reset" to page 1 when new results 
- Top and bottom pagination in sync

**Comment by rylew1** [comment]
cc @andycochran - if you have a moment, double check that the criteria above makes sense for a "pagination reset". Note that the API call for search results will be grabbing page 1 of the new results if we see this condition (not the page that was previously selected)

**Comment by andycochran** [comment]
Refined this a bit. Lemme know if it makes sense to you.

**Comment by rylew1** [comment]
@andycochran if `?page=1` already and we hit another filter/query/dropdown - you don't want it to clear the pagination?

**Comment by andycochran** [comment]
> @andycochran if `?page=1` already and we hit another filter/query/dropdown - you don't want it to clear the pagination?

IDK if that really matters. Aren't `?page=1` and the `page` param being nonexistent virtually the same thing from a UX perspective? I do like the idea of clearing query params that don't do anything, but not sure if it really matters.
