### ISSUE TITLE
[ADR]: Business Intelligence Tool for Dashboards

### ISSUE THREAD

**Issue by acouch** [HHS/simpler-grants-gov#1507]
### Description

This project aims to be as metric-driven and transparent as possible. Toward that end a public analytics page, similar to https://analytics.usa.gov/ is [being planned](https://github.com/HHS/simpler-grants-gov/issues/1367) which is directed toward the general public and will be designed and implemented with simpler.grants.gov branding in mind.

There is also a need to create public reports that can be quickly created and updated. It would be useful to be able to initially make some of those reports private in order to quickly iterate, get feedback from key stakeholders, and stage reports for data that is not publicly yet available. To this end, a business intelligence tool should be evaluated for the project.

### Approvers

@widal001 @lucasmbrown-usds @acouch @coilysiren @sumiat @jamesbursa 

### Options

* Metabase #1457 
* AWS quicksight #1410 
* Tableau
* Redash
* Apache Superset

### Decision Criteria

* Can share public dashboards
* Can show private dashboards to selected users
* Can connect to common data sources (S3, Redshift, Postgres, Snowflake)
* Allows technical users to create ad hoc queries to create graphs
* Easy-to-use UI for non-coders
* Cost of ownership
* Replicable for users outside of the project

### Definition of Done

- [ ] The approvers for this decision have been identified (ideally before work on the ADR starts)
- [ ] The ADR is created and stored in `documentation/decisions/adr` with status "Accepted"
- [ ] The ADR satisfies requirements that are outlined in the ADR template
- [ ] Any follow-up tickets have been created (if necessary)

### Out of scope
- [ ] The ADR has been reviewed and approved by the approvers listed above. The final decision will be made when the new data engineer has joined the team

## Notes

- 30k Spec: https://app.gitbook.com/o/cFcvhi6d0nlLyH2VzVgn/s/Pm7UEzeiS1tbLCV1SFRu/product/deliverables/specifications/delivery-dashboard
- 30k ticket: https://github.com/HHS/simpler-grants-gov/issues/65

**Comment by coilysiren** [comment]
I don't think this is 3 points, its more like 5 or 8

**Comment by acouch** [comment]
@coilysiren agreed, updated the points!
