### ISSUE TITLE
[Task]: Add env vars for the Search API

### ISSUE THREAD

**Issue by acouch** [HHS/simpler-grants-gov#1521]
### Summary

This task is to add the [API_URL](https://github.com/HHS/simpler-grants-gov/blob/main/frontend/.env.development#L17) and [API_AUTH_TOKEN](https://github.com/HHS/simpler-grants-gov/blob/main/frontend/.env.development#L21C1-L21C15) to the dev and stage and prod [ECS task env vars](https://github.com/HHS/simpler-grants-gov/blob/main/infra/frontend/service/main.tf#L140) so that the dev and stage search pages can connect to the dev and stage  and prod APIs.

Without the transformation work, there will be no data to read the data. 

### Acceptance criteria

- [ ] search page can connect to the search api

**Comment by rylew1** [comment]
You might add a dependency for dev data to be seeded with data? If the schema is actually setup in dev with blank tables, I think it would work and show 0 results on the search page. 

I'm not sure if stag or prod have a dependency for some kind of release to bump them to API v0.1 ?

**Comment by coilysiren** [comment]
Use the new pattern added in https://github.com/HHS/simpler-grants-gov/pull/1516, https://github.com/HHS/simpler-grants-gov/pull/1526 when doing this

**Comment by coilysiren** [comment]
Ryan DMed me to say that he wanted to work on this
