### ISSUE TITLE
[10k]: Simpler Metric Dashboard Discovery

### ISSUE THREAD

**Issue by sumiat** [HHS/simpler-grants-gov#1537]
### Definition

The Simpler Metric Dashboard will be a user-focused designed dashboard that provides the public with transparent access to key metics, data, and information that matter to the end users. To ensure that we create a dashboard that provides value to our users, we aim to do some discovery to understand what information is most instructive to our public users coming to the simpler.grants.gov site. We ultimately aim to provide meaningful insights and data that are relevant to our users. 

### Business Goals

- We aim to complete discovery on and provide transparent communication of Simpler metrics, data, information that is important to the public through validated user input so that we can improve the user experience for our end users.

### In scope

- Planning and initial designs of the simpler metric dashboard
- Stakeholder interviews and incorporation of feedback into the dashboard design

### Out of scope

- Development, infra, new endpoint

**Comment by sumiat** [comment]
**Weekly Update - IN DRAFT**

**What has been done?**
- Dashboards reviewed with Emily/MH for feedback 
- Stakeholder interview prep for the dashboard 

**Status**
In progress

**Risk**
None

**Deliverable Date**
TBD 

**What will be done?**
- Interview guide reviewed with MH and Emily
- Schedule sessions with users, depending on list that Emily sends

**Comment by andycochran** [comment]
**Weekly Update**

**What has been done?**
- Stakeholder interview script/questions prepped, approved by MicroHealth
- Determine with Emily, list of SMEs we might speak with, approved by MicroHealth

**Status**
In progress

**Risk**
None

**Deliverable Date**
TBD 

**What will be done?**
- Schedule/conduct sessions with users

**Comment by margaretspring** [comment]
**Weekly Update 4/11**

**What has been done?**
- 

**Status**
In progress 

**Risk**
None

**Deliverable Date**
TBD 

**What will be done?**
- Schedule/conduct sessions with users

**Comment by sumiat** [comment]
**Weekly Update 4/17**

**What has been done?**
- 2 interviews conducted with stakeholders

**Status**
In progress 

**Risk**
None — Interviews and findings should be completed. However, planning and initial designs will likely carry over past 5/15

**Deliverable Date**
TBD — Still too early to determine a date. Research findings will tell us more about the scope of this work. 

**What will be done?**
We may conduct 1 interview but this work is on hold for this sprint as the Search UI is higher priority and Crystabel will be OOO for half the sprint.

**Comment by widal001** [comment]
Replacing our old 10k ft issues with a new Epic format

**Comment by widal001** [comment]
Reopening for review during sprint planning
