### ISSUE TITLE
Investigate relevency scoring in search endpoint

### ISSUE THREAD

**Issue by chouinar** [HHS/simpler-grants-gov#1544]
### Summary

One thing we eventually want to support is the ability to do a relevancy sort in our search endpoint. When we add a search index, this will be a lot more flexible, and easier to support, but we want to see if there is some basic version we can create now for our first iteration of search that just queries against our database.

This ticket is to just do a bit of research and testing to find if there's a way to modify our current queries to support a very basic relevancy sort. Even if the scoring is just counting the number of matches, that would be fine.

A few ideas:
* textsearch in Postgres: https://www.postgresql.org/docs/current/textsearch.html - although from testing this a bit earlier, this didn't end up working well with many columns across several tables
* text similarity in Postgres: https://www.postgresql.org/docs/current/pgtrgm.html
* Some sort of counting approach?

Note that our current query looks something like:
```sql
SELECT
	opportunity.opportunity_id,
	opportunity.opportunity_number,
	opportunity.opportunity_title,
	opportunity.agency,
	opportunity.opportunity_category_id,
	opportunity.category_explanation,
	opportunity.is_draft,
	opportunity.revision_number,
	opportunity.modified_comments,
	opportunity.publisher_user_id,
	opportunity.publisher_profile_id,
	opportunity.created_at,
	opportunity.updated_at
FROM
	opportunity
	JOIN current_opportunity_summary ON opportunity.opportunity_id = current_opportunity_summary.opportunity_id
	JOIN opportunity_summary ON current_opportunity_summary.opportunity_summary_id = opportunity_summary.opportunity_summary_id
WHERE
	opportunity.opportunity_id in( SELECT DISTINCT
			opportunity.opportunity_id FROM opportunity
			JOIN current_opportunity_summary ON opportunity.opportunity_id = current_opportunity_summary.opportunity_id
			JOIN opportunity_summary ON current_opportunity_summary.opportunity_summary_id = opportunity_summary.opportunity_summary_id
			JOIN link_opportunity_summary_funding_instrument ON opportunity_summary.opportunity_summary_id = link_opportunity_summary_funding_instrument.opportunity_summary_id
			JOIN link_opportunity_summary_funding_category ON opportunity_summary.opportunity_summary_id = link_opportunity_summary_funding_category.opportunity_summary_id
			JOIN link_opportunity_summary_applicant_type ON opportunity_summary.opportunity_summary_id = link_opportunity_summary_applicant_type.opportunity_summary_id
			LEFT JOIN opportunity_assistance_listing ON opportunity.opportunity_id = opportunity_assistance_listing.opportunity_id
		WHERE
			opportunity.is_draft IS FALSE
			AND(EXISTS (
					SELECT
						1 FROM current_opportunity_summary
					WHERE
						opportunity.opportunity_id = current_opportunity_summary.opportunity_id))
				AND(opportunity.opportunity_title ILIKE '%example%'
					OR opportunity.opportunity_number ILIKE '%example%'
					OR opportunity.agency ILIKE '%example%'
					OR opportunity_summary.summary_description ILIKE '%example%'
					OR opportunity_assistance_listing.assistance_listing_number = 'example'
					OR opportunity_assistance_listing.program_title ILIKE '%example%'))
ORDER BY
	opportunity_summary.post_date DESC nulls LAST
LIMIT 25 OFFSET 25
```
Which won't quite support any of the above approaches

### Acceptance criteria

- [ ] Determine if there is a reasonable approach to modifying our existing query to support calculating a score

**Comment by widal001** [comment]
@chouinar Echoing Brett's comments above, do you have the SQLAlchemy query that generates this? I have a feeling some of the (potential) inefficiencies might be stemming from some of the translation that happens as a result of the ORM.

**Comment by widal001** [comment]
@chouinar Gotcha!! Thanks for linking this

> Definitely worth discussing the queries a bit more. I'll admit I'm not an expert when it comes to these very complex types of queries. I'll look to setup some time when I start working on this to figure out how we want to build out the queries. From what Brett put above, I think he'll have a much better idea for how to build some of this out than I would come up with.

Would it be helpful for me to noodle on optimizing/simplifying this query with you to try to incorporate some of Brett's suggestions? Or are you excited to dig into this further yourself?

**Comment by chouinar** [comment]
@widal001 - Sure I'd be happy to chat through some ideas

**Comment by widal001** [comment]
@chouinar Sounds great! I'll give this a bit more thought over the next couple of days and see if I can share an updated query with you that we can work on translating back to SQLAlchemy

**Comment by chouinar** [comment]
@widal001 - happy to pair on it, or if you want to look a bit on your own, one tip I can give when running the DB locally: If yo want a lot of data locally, I recently updated the seed script to take in an iteration count to produce more data easily. `make db-seed-local args="--iterations 300"` will generate ~10k opportunities (and records across several other tables), although be warned this takes like 10 minutes to run.

**Comment by chouinar** [comment]
Been chatting in a separate thread, pulling a few ideas together, a current work-in-progress query idea for scoring.

I know it has a few issues (needs some coalesces for null values), but putting this here for discussion.

```sql
WITH RECURSIVE summary_scores AS (
	SELECT
		opportunity_id,
		word_similarity ('health',
			summary_description) AS summary_score
	FROM
		opportunity_summary
),
opportunity_scores AS (
	SELECT
		opportunity_id,
		word_similarity ('health',
			opportunity_title) AS title_score,
		word_similarity ('health',
			opportunity_number) AS number_score,
		word_similarity ('health',
			agency) AS agency_score
	FROM
		opportunity
),
assistance_listing_scores AS (
	SELECT
		opportunity_id,
		word_similarity ('health',
			assistance_listing_number) AS al_number_score,
		word_similarity ('health',
			program_title) AS program_title_score
	FROM
		opportunity_assistance_listing
),
agg_assistance_listing_scores AS (
	SELECT
		opportunity_id,
		SUM(al_number_score) AS al_number_score,
		SUM(program_title_score) AS program_title_score
	FROM
		assistance_listing_scores
	GROUP BY
		opportunity_id
),
score_sum AS (
	SELECT
		summary_scores.opportunity_id,
		(summary_scores.summary_score + opportunity_scores.title_score + opportunity_scores.number_score + opportunity_scores.agency_score + agg_assistance_listing_scores.al_number_score + agg_assistance_listing_scores.program_title_score) AS total_score
	FROM
		summary_scores
	LEFT JOIN opportunity_scores ON summary_scores.opportunity_id = opportunity_scores.opportunity_id
	LEFT JOIN agg_assistance_listing_scores ON summary_scores.opportunity_id = agg_assistance_listing_scores.opportunity_id
)
SELECT
	opportunity.opportunity_id,
	opportunity.opportunity_title,
	opportunity.agency,
	opportunity_summary.summary_description,
	score_sum.total_score
FROM
	opportunity
	JOIN current_opportunity_summary ON opportunity.opportunity_id = current_opportunity_summary.opportunity_id
	JOIN opportunity_summary ON current_opportunity_summary.opportunity_summary_id = opportunity_summary.opportunity_summary_id,
	score_sum
WHERE
	opportunity.opportunity_id = score_sum.opportunity_id
ORDER BY
	score_sum.total_score DESC nulls LAST
LIMIT 25 OFFSET 1
```

**Comment by bretthrosenblatt** [comment]
Here's the query with scores and counts (overall and per id) from the chats
with recursive summa as
(select opportunity_id, opportunity_summary_id, summary_description, word_similarity('hydra solar', summary_description) as dif, 
 'hydra' <-> summary_description  as dist, count(*) over () as cnt, count(*) over (partition by opportunity_id) as cnt_per_id 
from opportunity_summary )
select opportunity.opportunity_id,
        opportunity.opportunity_title,
        opportunity.agency,
		summa.summary_description, summa.dif as matching_factor, 
		summa.dist as distance, 
		summa.cnt,
		summa.cnt_per_id
from opportunity, summa
where opportunity.opportunity_id = summa.opportunity_id;

<img width="808" alt="results" src="https://github.com/HHS/simpler-grants-gov/assets/20070645/0d2d00a6-7e77-452c-85e1-2c4cb2b36197">

**Comment by chouinar** [comment]
Here's an update to my above query, still missing a few things like coalesces/null handling for the scoring.

I added a `filter_query` which handles the filters (eg. you want just `forecasted` and `posted` opportunity statuses). I also made it so the score queries all reference it, which I actually think is required. Because the score queries are just going against a particular table like the opportunity summary, they may be calculating scores for past summaries, or ones that aren't the current. When we aggregate the scores, that could cause the score to be higher for something with a lot of revisions, which we wouldn't want, so those queries need to either have the logic that joins them to the current opportunity table, or instead just against the query that already handles that.

```sql
WITH RECURSIVE 
filter_query AS (
	SELECT
		opportunity.opportunity_id, opportunity_summary.opportunity_summary_id
	FROM
		opportunity
		JOIN current_opportunity_summary ON opportunity.opportunity_id = current_opportunity_summary.opportunity_id
		JOIN opportunity_summary ON current_opportunity_summary.opportunity_summary_id = opportunity_summary.opportunity_summary_id
		JOIN link_opportunity_summary_funding_instrument ON opportunity_summary.opportunity_summary_id = link_opportunity_summary_funding_instrument.opportunity_summary_id
		JOIN link_opportunity_summary_funding_category ON opportunity_summary.opportunity_summary_id = link_opportunity_summary_funding_category.opportunity_summary_id
		JOIN link_opportunity_summary_applicant_type ON opportunity_summary.opportunity_summary_id = link_opportunity_summary_applicant_type.opportunity_summary_id
	WHERE
		opportunity.is_draft IS FALSE
		AND(EXISTS (
				SELECT
					1 FROM current_opportunity_summary
				WHERE
					opportunity.opportunity_id = current_opportunity_summary.opportunity_id))
		AND link_opportunity_summary_funding_instrument.funding_instrument_id in(1)
		AND current_opportunity_summary.opportunity_status_id in (1, 2)
), summary_scores AS (
	SELECT
		opportunity_id,
		word_similarity ('health',
			summary_description) AS summary_score
	FROM
		opportunity_summary
	WHERE opportunity_summary.opportunity_summary_id in (select opportunity_summary_id from filter_query)
),
opportunity_scores AS (
	SELECT
		opportunity_id,
		word_similarity ('health',
			opportunity_title) AS title_score,
		word_similarity ('health',
			opportunity_number) AS number_score,
		word_similarity ('health',
			agency) AS agency_score
	FROM
		opportunity
	
	WHERE opportunity.opportunity_id in (select opportunity_id from filter_query)
),
assistance_listing_scores AS (
	SELECT
		opportunity_id,
		word_similarity ('health',
			assistance_listing_number) AS al_number_score,
		word_similarity ('health',
			program_title) AS program_title_score
	FROM
		opportunity_assistance_listing

	WHERE opportunity_assistance_listing.opportunity_id in (select opportunity_id from filter_query)

),
agg_assistance_listing_scores AS (
	SELECT
		opportunity_id,
		SUM(al_number_score) AS al_number_score,
		SUM(program_title_score) AS program_title_score
	FROM
		assistance_listing_scores
	GROUP BY
		opportunity_id
),
score_sum AS (
	SELECT
		summary_scores.opportunity_id,
		(summary_scores.summary_score + opportunity_scores.title_score + opportunity_scores.number_score + opportunity_scores.agency_score + agg_assistance_listing_scores.al_number_score + agg_assistance_listing_scores.program_title_score) AS total_score
	FROM
		summary_scores
	LEFT JOIN opportunity_scores ON summary_scores.opportunity_id = opportunity_scores.opportunity_id
	LEFT JOIN agg_assistance_listing_scores ON summary_scores.opportunity_id = agg_assistance_listing_scores.opportunity_id
)

SELECT
	opportunity.opportunity_id, opportunity.opportunity_title, opportunity.agency, opportunity_summary.summary_description, score_sum.total_score
FROM
	opportunity
	JOIN current_opportunity_summary ON opportunity.opportunity_id = current_opportunity_summary.opportunity_id
	JOIN opportunity_summary ON current_opportunity_summary.opportunity_summary_id = opportunity_summary.opportunity_summary_id, score_sum
WHERE
	opportunity.opportunity_id = score_sum.opportunity_id
	AND opportunity.opportunity_id in(
		SELECT
			opportunity_id FROM filter_query)
	AND score_sum.total_score > 0.3
ORDER BY
	score_sum.total_score DESC nulls LAST
LIMIT 25 OFFSET 1

```

**Comment by mxk0** [comment]
@chouinar is this ticket still relevant, or is OpenSearch the answer?

**Comment by chouinar** [comment]
@mxk0 - with the search index approach agreed on, I think we're good to close this ticket.
