### ISSUE TITLE
[Task]: Document sam.gov APIs

### ISSUE THREAD

**Issue by sumiat** [HHS/simpler-grants-gov#1552]
### Summary

We looked into the user journey flow in #1063. We did not have access to the codebase when we started/completed #1063. We determined that there is an API to get the UEI data both daily, monthly, and as needed. We believe that this is happening at the “verify step”. We want to document the APIs provided by sam.gov that expose its services. We aim to identify steps in the journey map where manual processes could potentially be replaced or improved by utilizing APIs. 

### Acceptance criteria

- [ ] Document the APIs offered/used by sam.gov in the current grants.gov workflow. 
- [ ] Document APIs that sam.gov offers that we may not be using that could improve the experience

### Open questions / notes
- There are other APIs that sam.gov offers that we may not be using https://open.gsa.gov/api/entity-api/
- Continue to use the current documentation documents we have: https://docs.google.com/document/d/18vlm4r8P0MvGQO3PaV8Y8pixkrxRYEoWwbcF4QUFgzs/edit#heading=h.mtc4swvlio8d and https://app.mural.co/t/nava4113/m/nava4113/1706317271420/72444fee3c691fcb68fad9f96302825131091214?sender=sumithaiveettil7756
- Will need some support from Design to work through user flow
- Can you request a UEI from the endpoint? Mostly all read-only endpoints. There is no registration endpoint. 
- Could more to document around fetching
- USDR created a spreadsheet on checking the status of UEI and we might be able reuse some of that information https://www.usdigitalresponse.org/grant/uei-lookup
- Slack thread with more context: https://nava.slack.com/archives/C057K146W8H/p1711746794933379
- Sam might have registration statuses https://www.fsd.gov/gsafsd_sp?id=kb_article_view&sysparm_article=KB0029911

**Comment by chouinar** [comment]
@sumiat - I updated a section at the end of the [google doc](https://docs.google.com/document/d/18vlm4r8P0MvGQO3PaV8Y8pixkrxRYEoWwbcF4QUFgzs/edit). Focused on what the API/extracts that the current system uses contain. I'll be out next week, but if there are any other questions or issues you'd like me to investigate when I get back, just let me know. I'll put this in-review for now and check back in a week.

**Comment by sumiat** [comment]
Thanks @chouinar! I'll review on Thursday.

**Comment by acouch** [comment]
assigning to myself for review as well, thanks @chouinar

**Comment by sumiat** [comment]
I reviewed and left some comments in the doc. @acouch would be interesting to get your input as well! There are a couple things we may want to meet about. I may put a hold to meet on monday so we can wrap up this ticket before the sprint closes.

**Comment by sumiat** [comment]
Reviewed the doc and process with @chouinar and @acouch. Next steps: will set up time with Lucas to discuss and share
