### ISSUE TITLE
Metabase - connect to postgres

### ISSUE THREAD

**Issue by coilysiren** [HHS/simpler-grants-gov#1554]
### Summary

Configure Metabase to allow it to access Postgres. There are two ways to do this:

1. Configure the ECS task definition to allow it to use Postgres to store user information and other Metadata: https://www.metabase.com/docs/latest/installation-and-operation/configuring-application-database#postgres
2. Configure the Metabase application itself to enable it to use Postgres as a data source: https://www.metabase.com/docs/latest/databases/connections/postgresql

### Acceptance criteria

- [ ] Metabase ECS service is utilizing Postgres
- [ ] Metabase application can view Postgres data

**Comment by mxk0** [comment]
Closing in favor of https://github.com/HHS/simpler-grants-gov/issues/2391.
