### ISSUE TITLE
Make search sidebar sticky

### ISSUE THREAD

**Issue by andycochran** [HHS/simpler-grants-gov#1562]
Make the search sidebar use the sticky class so that it can be scrolled independently of the results when stuck. 

See https://codepen.io/andycochran/pen/BabejWq?editors=1100 

This is blocked by [ issue ??? ] to implement the beta alert banner, which also uses sticky. It needs to be in place first to make sure these can both work together.

**Comment by rylew1** [comment]
@andycochran Do we still think this is worth doing or wait until usability testing?

**Comment by emilycnava** [comment]
@andycochran what beta banner were you referring to in the og issue desc? Has that been done already?

**Comment by andycochran** [comment]
> … to implement the beta alert banner, which also uses sticky

This was referring to the "Attention! Go to www.grants.gov…" alert (sorry, _banner_ is a loaded term in USWDS): 

![Image](https://github.com/user-attachments/assets/043e9392-2d8a-4169-b7c1-7b4133ff55b1)

I think this has already been implemented. However, I don't think this Issue is a priority. We might not even want to implement it. It would require also setting the sidebar to overflow when sticky. This is possible, but can get messy w/ custom CSS. And it's likely the Search UI will change quite a bit after usability testing. I'd suggest we punt on this until we know more or have a real/verified user need to address.

**Comment by andycochran** [comment]
I'm going to close this for now. We'll reopen if it's still relevant after Search UI usability testing. I just suspect the Search UX may change quite a lot and this may not be necessary.
