### ISSUE TITLE
Collapse sidebar/filters on small screens (mobile view)

### ISSUE THREAD

**Issue by andycochran** [HHS/simpler-grants-gov#1563]
### Summary

On small screens, the search sidebar (status, filters) should be collapsed by default, as to not take up so much screen real estate. A "Show/Hide filters" button will toggle this state. 

<img width="764" alt="image" src="https://github.com/HHS/simpler-grants-gov/assets/409279/f0ee5968-3d0f-40e6-820f-71569691f0f4">

### Open Q: 
Should this also include a count (as the accordions/sections do) of all enabled filters, so that it's obvious how many filters are applied while the sidebar is collapsed? 

<img width="200" alt="image" src="https://github.com/HHS/simpler-grants-gov/assets/409279/94a8b33c-7c55-4401-8467-9c826bd560f3">

### Acceptance criteria

- [ ] User can toggle the visibility of the filters

**Comment by acouch** [comment]
@andycochran  can we move this to: https://github.com/HHS/simpler-grants-gov/milestone/155 since it is something we want to do before closing this line of work but is not blocking users from testing the search page?

**Comment by andycochran** [comment]
Yeah. I think so. The research plan doesn't currently include tests explicitly for mobile. We'll be sure to thoroughlyinternally QA the mobile layout internally.
