### ISSUE TITLE
[Task]: Review analytics proposal 

### ISSUE THREAD

**Issue by sumiat** [HHS/simpler-grants-gov#1575]
### Summary

I brought up in a thread: https://betagrantsgov.slack.com/archives/C05TGEN1J7N/p1708477362863309 that it would be good to get some baseline metrics set up for grants.gov. It was suggested that we would need to ask the PMO team to get the OK to work on this. Attached is the drafted proposal for review by MH. 

### Acceptance criteria

- [x] Review and provide any feedback to the analytics proposal and provide feedback by EOD 4/2: https://docs.google.com/document/d/1W1dQcW-pG6BxiaKQifcJG3TyVTbFUIHQlK3GDxAtJXY/edit#heading=h.zh5e3t414igu

**Comment by sumiat** [comment]
hi @bretthrosenblatt - do you mind reviewing this proposal? let me know if there would be someone better to review. I would have asked @kw-MH but he's OOO. Thanks so much!

**Comment by bretthrosenblatt** [comment]
Sure, get on if first thing tomorrow.

**Comment by bretthrosenblatt** [comment]
I've gotten no further than last week. Still trying to find out who would approve of and make these changes. Doesn't appear to be engineering and operations.

**Comment by widal001** [comment]
Closing because issue was marked as 'Done' in https://github.com/orgs/HHS/projects/13
