### ISSUE TITLE
[Task] Update simpler incident response plan include response for performance standard availability window

### ISSUE THREAD

**Issue by acouch** [HHS/simpler-grants-gov#1576]
### Notes

* [Existing Contingency Response Plan](https://app.gitbook.com/o/cFcvhi6d0nlLyH2VzVgn/s/v1V0jIH7mb7Yb3jlNrgk/~/changes/342/engineering/security/contingency-response-plan)
* [Existing Incident Response Plan](https://app.gitbook.com/o/cFcvhi6d0nlLyH2VzVgn/s/v1V0jIH7mb7Yb3jlNrgk/~/changes/342/engineering/security/incident-response-plan)
* Create a document that explains the flow/steps when an issue occurs. It could be an error or failure or security issue. 

### Acceptance criteria

- [ ] Document the severity levels, steps to go through when an issue occurs and how to handle an issue based on a severity level. 
- [ ] Send to MH for review

### Open questions
- @acouch - could you confirm who from MH needs to review this before we send to HHS?

**Comment by sumiat** [comment]
Sent to internal nava for review and a follow on ticket is created to incorporate feedback, if needed. #1582
