### ISSUE TITLE
[Task]: : Add Margaret Spring to MAINTAINERS.md

### ISSUE THREAD

**Issue by acouch** [HHS/simpler-grants-gov#1581]
### Summary

Add @margaretspring   to https://github.com/HHS/simpler-grants-gov/blob/main/MAINTAINERS.md and remove Esther Oke. 

This is an oppportunity reinstitute alpha order by last name.

We can also perhaps clean up the "Product and Project Management" and "Product and Delivery" 

### Acceptance criteria

- [x] @margaretspring   added to the project
- [x] Other cleanup like ordering or categories identified and done

**Comment by margaretspring** [comment]
@acouch - Who should this be assigned to for moving forward?
