### ISSUE TITLE
[Task]: Switch api to use ruff instead of flake8 (and maybe black)

### ISSUE THREAD

**Issue by chouinar** [HHS/simpler-grants-gov#1587]
### Summary

Ruff is an alternative / better performing linter than flake8 which we currently use in the API: https://github.com/astral-sh/ruff

From some brief testing in the past, we can easily switch to ruff as flake8 rules are re-implemented in ruff, although a bit of reconfiguring may be necessary: https://docs.astral.sh/ruff/faq/#how-does-ruffs-formatter-compare-to-black

Note that we may also be able to replace our usage of black which handles code formatting

### Acceptance criteria

- [ ] Ruff is used instead of flake8
- [ ] We've looked into whether we can also replace our usage of black at the same time
- [ ] The number of changes after running the linter is very small / inconsequential (a handful of lines being slightly adjusted is fine)
- [ ] The [alembic configuration](https://github.com/HHS/simpler-grants-gov/blob/main/api/src/db/migrations/alembic.ini#L43) is updated to auto-use ruff. See: https://github.com/astral-sh/ruff/discussions/8949

**Comment by coilysiren** [comment]
I would recommend that we keep `black`. Everytime I've used them both (eg. both `black` and `ruff`) I end up with them finding different changes. That makes me inclined to keep them both.
