### ISSUE TITLE
[Task]: Update Twitter / X logo

### ISSUE THREAD

**Issue by andycochran** [HHS/simpler-grants-gov#1588]
### Summary

Swap the `Twitter` logo in the site footer to the new `X` logo

(The logo already exists in USWDS (and [Truss](https://github.com/trussworks/react-uswds/blob/main/src/components/Icon/Icons.ts#L239)): 

![image](https://github.com/HHS/simpler-grants-gov/assets/409279/a24c4435-9846-491b-bc6e-d0f58c67a375)

### Acceptance criteria

- [ ] Footer is using the new X logo

**Comment by emilycnava** [comment]
Picking up this one
