### ISSUE TITLE
[Task]: Create a public sprint dashboard

### ISSUE THREAD

**Issue by coilysiren** [HHS/simpler-grants-gov#1592]
### Summary

Create a public sprint dashboard that looks like the dashboards @widal001 and @acouch have demoed prior.

Note: text explanations of the dashboards will be conducted in #1237.

### Acceptance criteria

The dashboard should have the following:

- [ ] Sprint velocity: Number of tickets/points completed per sprint
- [ ] Sprint burndown: Number of open tickets/points remaining in a sprint per day
- [ ] Sprint burnup: Number of tickets/points opened and closed in a sprint per day
- [ ] Sprint allocation: Number of tickets/points per deliverable in a given sprint

**Comment by coilysiren** [comment]
example: 
<img width="1042" alt="image" src="https://github.com/HHS/simpler-grants-gov/assets/5768468/2e187c3f-4978-49e6-ab97-e82712120ae4">

**Comment by acouch** [comment]
This was the query I created in Metabase for the burndown:

```sql
SELECT 
    "story_points",
    "sprint_data_20240307190617"."title",
    "created",
    sum("story_points") over() as total,
    sum("story_points") over() - sum("story_points") over(order by "closed") as remainder,
    "closed"
FROM "sprint_data_20240307190617"
LEFT JOIN "issue_data_20240307190609" ON "content__number" = "number" 
WHERE "sprint__title" = {{sprint__title}}
ORDER BY "closed"
```

This is the query for the number of points per sprint:

```sql


SELECT 
    "sprint__title" as sprint,
    "sprint__start",
    sum("story_points") as points
FROM "sprint_data_20240307190617"
WHERE "sprint__start" < now()
GROUP BY "sprint__title"
ORDER BY "sprint__start" DESC
LIMIT 5
```

**Comment by mxk0** [comment]
This is now tracked elsewhere: https://github.com/HHS/simpler-grants-gov/issues/2347
