### ISSUE TITLE
[Task]: Add Analytics to Vulnerability Scans

### ISSUE THREAD

**Issue by acouch** [HHS/simpler-grants-gov#1596]
### Summary

We are deploying the analytics service(#1574). While the service itself is only internally facing, we want to run the vulnerability scans on it.

This task would involve running the scans:
* (is as simple as adding "analytics" here: https://github.com/HHS/simpler-grants-gov/blob/main/.github/workflows/ci-vulnerability-scans.yml#L19 ?)
* and updating the container to pass scans. currently tracking [a number to fix](https://microhealth.sharepoint.com/teams/SimplerSecurity-SecurityDocuments/Shared%20Documents/Forms/AllItems.aspx?id=%2Fteams%2FSimplerSecurity%2DSecurityDocuments%2FShared%20Documents%2FSecurity%20Documents%2FSimpler%20Security%20Scans%2F1APR24%20Simpler%20Weekly%20Scan%2FSimpler%20Analytics%201Apr%2Epdf&viewid=bd15fba0%2D1443%2D40ef%2Dabbf%2D3f12d94c7695&parent=%2Fteams%2FSimplerSecurity%2DSecurityDocuments%2FShared%20Documents%2FSecurity%20Documents%2FSimpler%20Security%20Scans%2F1APR24%20Simpler%20Weekly%20Scan).

or this could be pulled out into separate tasks.

### Acceptance criteria

- [ ] add CI scanning to analytics folder
- [ ] update the container image so it passes

**Comment by coilysiren** [comment]
Already done the CI part: https://github.com/HHS/simpler-grants-gov/pull/1603

**Comment by coilysiren** [comment]
^ I'm not specifically planning on doing the "make scans pass" part right now

**Comment by coilysiren** [comment]
Update, I'm working on this entire ticket and almost done
