### ISSUE TITLE
[Task]: Add postgres integration to analytics.integrations

### ISSUE THREAD

**Issue by acouch** [HHS/simpler-grants-gov#1599]
### Summary

Add postgres integration so that a database can be connected to. After #1597 and #1598 are done, this should allow for the connection to a local analytics database.

The client connection code in the API is a good example of a client and could be copy/pasted: https://github.com/HHS/simpler-grants-gov/tree/main/api/src/adapters/db/clients

The integration should provide a client to connect to a database that accepts configuration from environment variables in  #1598

### Acceptance criteria

- [ ] integration created that connects to local database
- [ ] file added that can be run in the script initialization

### Notes
- Combine with #1610 
- For the https://github.com/HHS/simpler-grants-gov/issues/65 we have the analytics container that needs to be able to push data from github to the postgres database. We want a way to make sure the correct tables are created and schema in place.

This needs to support schema changes.

This should be a single file that checks if the tables exist and create them if they don't
similar to: https://github.com/HHS/simpler-grants-gov/blob/main/api/src/db/migrations/setup_local_postgres_db.py

This should be part of the script initialization.

This will likely removed for another tool or strategy down the road.

**Comment by widal001** [comment]
We might be taking a different approach for delivery reporting. Will re-open if this becomes relevant again.

**Comment by acouch** [comment]
This was actually completed over the break https://github.com/HHS/simpler-grants-gov/issues/2080
