### ISSUE TITLE
[Task]: Stand up API and Front-End as an Open Source Contributor and Suggest Documentation Improvments

### ISSUE THREAD

**Issue by acouch** [HHS/simpler-grants-gov#1614]
### Summary

The goal of this task is to improve our documentation for potential open source contributors.

To do this, review the current documentation, stand up the API and front-end applications, and suggest edits that help improve the experience or fix gaps or confusing elements.

### Acceptance criteria

- [ ] API and front-end working locally
- [ ] Edits to documentation in the form of a pull request

**Comment by emilycnava** [comment]
I was able to standup the API and frontend with little hastle following the appropriate readme's :)
