### ISSUE TITLE
[Task]: SearchFilterCheckbox test should call `decrement()` when unhcecking

### ISSUE THREAD

**Issue by rylew1** [HHS/simpler-grants-gov#1618]
### Summary

In the `SearchFilterCheckbox` test, we click the checkbox and assert that `mockIncrement` has been called - this works ok.

However when we subsequently go to uncheck the box, `mockDecrement` (and `mockUpdateCheckedOption` with a `false` value doesn't appear to be called - this code is failing for some reason:

```
 // Simulate user clicking the checkbox again to uncheck it
    fireEvent.click(checkbox);


    await waitFor(() => {
      expect(mockDecrement).toHaveBeenCalledTimes(1);
    });

    // Wait for the updateCheckedOption function to be called with the checkbox being unchecked
    await waitFor(() => {
      expect(mockUpdateCheckedOption).toHaveBeenCalledWith(option.id, false);
    });


```

### Acceptance criteria

- test passing with `mockDecrement` expected to have been called
    - If not possible - some explanation for why this is happening in the form of a comment in the test file

**Comment by acouch** [comment]
This reflects a different strategy for capturing input that was changed in #2067 . Now inputs change the query params in the URL which updates the page.
