### ISSUE TITLE
[Task]: Spike for Search page tracking set up for GA

### ISSUE THREAD

**Issue by sumiat** [HHS/simpler-grants-gov#1619]
### Summary

Set up GA tracking and/or custom events for the following metrics in the ACs. Separate these into separate tickets, if needed. 

### Acceptance criteria

We have a plan or some discovery into how to implement the below analytics from simpler.grants.gov to GA4. If it's easier to just implement the tracking, go ahead and do so. Create the relevant follow up ticket(s) with implementation details: 

- [ ] Total number of searches made via the UI: should validate but it should come standard https://support.google.com/analytics/answer/1032321?hl=en#zippy=%2Cin-this-article 
- [ ] Track search terms searched so that we can understand top search terms: we will need to have the search term in the query param to track in google analytics: https://support.google.com/analytics/answer/1012264?hl=en#zippy=%2Cin-this-article

**Comment by sumiat** [comment]
hi @btabaska did you create the separate issues for the last 4 data points we need to track?

**Comment by btabaska** [comment]
![Image](https://github.com/HHS/simpler-grants-gov/assets/29316916/12b624ff-a16f-4482-a216-c6341a325da2)

Search terms added, waiting for data to populate once code change goes to prod.
