### ISSUE TITLE
Measure branding impact

### ISSUE THREAD

**Issue by sumiat** [HHS/simpler-grants-gov#1620]
### Summary

We have a mechanism set up and are able to measure the following metrics for branding noted in the ACs

### Acceptance criteria

- [ ] Send a survey link to at least 10 HHS stakeholders to measure brand recognition, impact, how easy it is to use new tools and guidelines
- [ ] Method to measure the usability of the brand in the grants process itself, such as accessible colors and ranking of key message

**Comment by margaretspring** [comment]
@senongo Has this item been on your radar for the Branding deliverables? Thinking we can do a survey out to stakeholders re: Branding choices for the 1st part, but not sure how to address the 2nd.

**Comment by margaretspring** [comment]
Descoping for current Unified Branding 30k.
