### ISSUE TITLE
[Task]: Create a Delivery Metrics Dashboard

### ISSUE THREAD

**Issue by acouch** [HHS/simpler-grants-gov#1622]
### Summary

After #1507 a delivery metrics dashboard should be created. 

example: 
<img width="1042" alt="image" src="https://github.com/HHS/simpler-grants-gov/assets/5768468/2e187c3f-4978-49e6-ab97-e82712120ae4">

Note: text explanations of the dashboards will be conducted in #1237.

### Acceptance criteria

The dashboard should contain the following:

- [ ] Completion percentage: Percentage of all tickets/points completed per deliverable
- [ ] Deliverable burndown: Number of open tickets/points remaining for a given deliverable per day
- [ ] Deliverable burnup: Number of tickets/points opened and closed for a given deliverable per day

**Comment by mxk0** [comment]
This is now tracked elsewhere: https://github.com/HHS/simpler-grants-gov/issues/2347
