### ISSUE TITLE
[Task]: Secure database in which we can store participant PII

### ISSUE THREAD

**Issue by rishalee** [HHS/simpler-grants-gov#1630]
### Summary

Database for participant PII has been selected and obnboarded

### Acceptance criteria

- Nava has recommended database
- Database is identified and agreed upon
- PAC lead has been given access and onboarded to database

**Comment by rishalee** [comment]
@margaretspring Nava has recommended Ethnio, this is with @lucasmbrown-usds

**Comment by margaretspring** [comment]
@rishalee is this Lucas' to approve or Nava's to work out?  

I updated https://github.com/HHS/simpler-grants-gov/issues/891 - Wondering if we should mark this as blocked pending a determination about Ethnio being made?

**Comment by andycochran** [comment]
I'm going to close this out, now that we have an Ethn.io account up and running with access for all 3 Nava designers.
