### ISSUE TITLE
Confirm total compensation budget for first cohort of Co Design Group

### ISSUE THREAD

**Issue by rishalee** [HHS/simpler-grants-gov#1631]
### Summary

- Dollar amount of participant compensation budget is specified

### Acceptance criteria

- [ ] Agreement of HHS leadership on budget amount
- [ ] Budget for first cohort has been communicated to Co-Design Group team

**Comment by rishalee** [comment]
@margaretspring this task is with @lucasmbrown-usds

**Comment by widal001** [comment]
### From our 30k review on 5/8

The non-binding estimated budget to use for planning is _$90,000 for 6 months_ which roughly corresponds to:

**Scenario 1: More participants with fewer hours**

24 participants * 6 months * 6 hrs/mo * $100/hr = $86,400

**Scenario 1: Fewer participants with more hours**

12 participants * 6 months * 12 hrs/mo * $100/hr = $86,400

**Comment by margaretspring** [comment]
Since Nava now has ODCs & has been approved to compensation participants, we'll keep these #s for estimates, but request approval for funding against OCDs as Co-Design gets underway and in alignment with the Deliverable scope & acceptance criteria per Quad & Year planning.
