### ISSUE TITLE
Define hourly rate of compensation for participants

### ISSUE THREAD

**Issue by rishalee** [HHS/simpler-grants-gov#1632]
### Summary

- Define hourly compensation rate for participants

### Acceptance criteria

- [x] Nava has recommended amount to HHS
- [x] HHS leadership has approved amount of hourly compensation
- [x] Hourly amount of compensation has been communicated to CDG team

**Comment by rishalee** [comment]
Nava has recommended rate of $100/hr @margaretspring this is with @lucasmbrown-usds

**Comment by widal001** [comment]
Lucas approved the recommended rate of $100/hr in [this slack thread](https://betagrantsgov.slack.com/archives/C05T74HRWRL/p1715182121415389?thread_ts=1715181676.039999&cid=C05T74HRWRL)

**Comment by andycochran** [comment]
@rishalee I think you can close this. Or is there anything remaining?
