### ISSUE TITLE
Define platform for transferring money to participant

### ISSUE THREAD

**Issue by rishalee** [HHS/simpler-grants-gov#1634]
### Summary

- Define platform for compensation transfer to participant (e.g. Ethnio, Usertesting, Tremendous)

### Acceptance criteria

- [x] Nava has suggested strategy of transferring via Tremendous 
  - [x] SOP drafted: https://app.gitbook.com/o/cFcvhi6d0nlLyH2VzVgn/s/v1V0jIH7mb7Yb3jlNrgk/design/design-research/research-documentation/research-incentives-standard-operating-procedure-sop
- [ ] HHS leadership has approved process

**Comment by rishalee** [comment]
@margaretspring this is with @lucasmbrown-usds

**Comment by andycochran** [comment]
This is resolved. Closing.
