### ISSUE TITLE
[Task]: Switch sort by dropdown to USWDS Select component

### ISSUE THREAD

**Issue by rylew1** [HHS/simpler-grants-gov#1637]
### Summary

see this comment: https://github.com/HHS/simpler-grants-gov/pull/1617#discussion_r1556444400

Should we move to the [UWDS Select component ](https://github.com/trussworks/react-uswds/tree/main/src/components/forms/Select) ?

**Comment by emilycnava** [comment]
I'm gonna pick this one up first :)

**Comment by mdragon** [comment]
We've confirmed this actually was done during the pause.
