### ISSUE TITLE
Schedule remaining interviews with SMEs

### ISSUE THREAD

**Issue by rishalee** [HHS/simpler-grants-gov#1650]
### Summary

Lucas and Risha will meet with SMEs to describe project and solicit help with recruiting participants. 

Blocked by #1631, #1632, and #1415 

### Acceptance criteria

- [ ] Timeline has been agreed upon on when SME meetings will end and meetings have been scheduled

**Comment by rishalee** [comment]
@lucasmbrown-usds please let me know if 
- I can schedule these for us
- you have prioritized who to meet with
- you want to be present for all meetings
- when these meetings should conclude (I recommend end of April to allow us to give time for following up with them and screening participants in time for May 14 POP)

**Comment by rishalee** [comment]
Posted in internal-grants channel on 4/9

**Comment by rishalee** [comment]
@margaretspring @andycochran this is a high priority item for expediting towards kickoff of Co Design group - please follow up with Lucas/MH as necessary

**Comment by andycochran** [comment]
Marking this blocked by #1631, #1632, and #1415

**Comment by andycochran** [comment]
@rishalee is this still blocked?
