### ISSUE TITLE
Stand Up OpenSearch

### ISSUE THREAD

**Issue by acouch** [HHS/simpler-grants-gov#1656]
### Summary

This task is to stand up OpenSearch in AWS ~~the lower environment in AWS in order to get hands on experience with the tool. The result will be a better understanding of the LOE for setup and maintenance and features.~~

### Acceptance criteria

- [ ] OpenSearch setup in dev in AWS
- [ ] OpenSearch configured via terraform for deployment to other environments
- ~~[ ] demo of OpenSearch for devs~~

**Comment by mdragon** [comment]
Work has been completed.

**Comment by coilysiren** [comment]
See also: https://github.com/HHS/simpler-grants-gov/issues/2327

**Comment by mxk0** [comment]
Is setting up OpenSearch in staging/prod part of this ticket too? The description and acceptance criteria are a little confusing.

**Comment by mdragon** [comment]
> Is setting up OpenSearch in staging/prod part of this ticket too? The description and acceptance criteria are a little confusing.

That was my intention, up and running in Dev for integration with the API, but done in such a way that it should roll out cleanly to the higher environments as we move it forward.

**Comment by mxk0** [comment]
@mdragon gotcha! More a process question than anything, should we have separate tickets for provisioning the other environments or should that be acceptance criteria under this one?

**Comment by mxk0** [comment]
🎉🎉🎉
