### ISSUE TITLE
[Task]: Setup i18n with next-intl

### ISSUE THREAD

**Issue by rylew1** [HHS/simpler-grants-gov#1657]
### Summary

setup i18n with next-intl

### Acceptance criteria

Internationalization works on app router pages

**Comment by acouch** [comment]
@rylew1 is the approach to have two sets of i18n folders until #1361 is done?

**Comment by acouch** [comment]
@rylew1 this approach could be a quick fix initially https://github.com/HHS/simpler-grants-gov/pull/1358/commits/7d41ab7f306ba2bc2482c9c5ef04367430289202#diff-0df8a6933bb9d8397e13f2e5f8799e5603a12d421c0a672ea2803e133622a4e6L28

**Comment by acouch** [comment]
I started this locally, will try and push a branch before cob.

**Comment by acouch** [comment]
I have this working, needs a lot of clean up https://github.com/HHS/simpler-grants-gov/tree/acouch/issue-acouch-i18n/frontend
