### ISSUE TITLE
[Task]: Set up all agencies as filter options

### ISSUE THREAD

**Issue by andycochran** [HHS/simpler-grants-gov#1658]
### Summary

- Make sure every agency appears as an option in the agency filter. 
- Get the values from the API docs

- Create a lookup list from the `agencyFilterList` so we can show our user friendly names based on the agency code. Something like this:
`{ "ARPAH" : "All Advanced research PRojects Agency for Health [ARPAH"}`

**Comment by andycochran** [comment]
> - Make sure every agency appears as an option in the agency filter.

Not necessarily "every agency" in the data. We only need to display the agencies that are in the current grants.gov search UI

**Comment by rylew1** [comment]
https://betagrantsgov.slack.com/archives/C05TSL64VUH/p1713298196755899

See this discussion, we've found that prod agency data is not in the greatest state, and it's better if we show a user friendly label , but we need to generate a lookup agency list (from the `agencyFilterList` file we already have)

**Comment by crystabelrangel** [comment]
https://docs.google.com/spreadsheets/d/1M14vX-kDakn0QHhYkUnIasBnTFUfU73BKXXxAfCxtzQ/edit?usp=sharing

**Comment by andycochran** [comment]
Here's https://docs.google.com/spreadsheets/d/1M14vX-kDakn0QHhYkUnIasBnTFUfU73BKXXxAfCxtzQ/edit#gid=1891194558
