### ISSUE TITLE
[Task]: Populate the Search API with seeded data in dev

### ISSUE THREAD

**Issue by rylew1** [HHS/simpler-grants-gov#1659]
### Summary

Populate API with factory seeded data (similar to how we can do it locally)

This work is blocking Usability Testing, and frontend connecting to dev and showing data. Staging will be done later

### Acceptance criteria

- API is seeded with mock data for dev

**Comment by rylew1** [comment]
cc @chouinar @andycochran @acouch 

This is blocking the search UI work

**Comment by chouinar** [comment]
@rylew1 / @andycochran - A few questions:

1. How "realistic" of data do we want? Would the data we have generated in the API locally be sufficient (knowing that we can adjust the factories to add some more variance) OR do we just want to use production data? I'd actually lean toward production data just to avoid missing scenarios we may not have thought of
2. Is a one-time copy good enough, or do we want to consider doing this more than once (ie. how much should I document the process?)

**Comment by andycochran** [comment]
For usability testing, we might make due with the local mock data. But it'd be optimal to have real data, as to not confuse users. I understood we needed to seed mock data in an environment because real data depends on the transformation work. If we dan we get a 1-time copy of real data into the database soon, I think that would suffice for usability testing even if it gets a little stale.

**Comment by chouinar** [comment]
The easiest way to get the data into the DB quickly is loading CSVs, its just whether I generate them locally, or write some scripts to convert prod data. The transformations we would need to do are pretty simple (the complexity with the transformation work is largely around it being continuous, but a one-time transform is easy enough). I can also simplify it a little by trimming the data and not trying to import 15+ years of opportunities and all the historical data.

If we're happy with a one-time copy of prod data, I can get started on writing a quick script to generate CSVs in our table's formats. Two things I'll need help with (probably @coilysiren )
1. Once I have these CSV files, we'll need to load them into the database. I'm not sure how we can best do that, in the past I've worked with a DBA who was able to connect directly to the DB from their local machine and use PgAdmin to run the load CSV scripts, but I'm guessing that might not work. Any ideas?
2. We'll need to get the ECS task setup for the `set-current-opportunities` script. A side question - is there any way to manually run an ECS task to call a specific script (ie. call ECS and pass it the `poetry run ...` command)? Would work around needing to setup the terraform for it yet

**Comment by coilysiren** [comment]
RE 1. RDS can load from S3

RE 2. Yes, thats what the migrations do, for example. I'll go get a command example now...

**Comment by bretthrosenblatt** [comment]
The easiest way to get the prod data loaded is to just query the fdw (insert into target select * from fdw).

**Comment by coilysiren** [comment]
Here's an example of running one-off commands:

https://github.com/navapbc/bid-fed-hhs-swift-challenge/issues/120#issuecomment-1996007450

**Comment by coilysiren** [comment]
Here's the syntax for running one-off commands:

```
aws ecs run-task \ --region=us-east-1 \ --cluster=api-prod \ --task-definition=api-prod \ --started-by="$(whoami)" \ --launch-type=FARGATE \ --platform-version=1.4.0 \ --network-configuration \ '{ "awsvpcConfiguration": { "subnets": [ "subnet-06c6fca10930aa4bb", "subnet-074b2318055b4ddb4", "subnet-0f05bc8211f6b6bb8" ], "securityGroups": [ "sg-09aed6d319f4cfc64" ], "assignPublicIp": "DISABLED" } }' \ --overrides \ '{ "containerOverrides": [ { "name": "api-prod", "command": [ "poetry", "run", "flask", "institution", "load-csv" ], "environment": [ { "name": "FLASK_APP", "value": "src.app:create_app()" } ] } ] }'
```

Just need to adjust the subnets and such

**Comment by coilysiren** [comment]
IMO the easiest thing here is to write a one off transformation command that queries the foreign data wrapper. We can then use that command for the actual transformation work later. 

Doing that would avoid the need to setup the stuff needed to load a CSV

**Comment by chouinar** [comment]
The transformations are fairly complex if written in SQL, and my understanding is that we were leaning towards a custom transformation process in-code which this would be a precursor to.

In python we can re-use a lot of already existing code to aid the transformation logic and it just requires mapping of a lot of values instead.

**Comment by andycochran** [comment]
> …I would imagine we could just use production for post-launch user testing. @andycochran is that correct that we will use production for user-testing once we are live?

Yeah. We can do usability tests in production. That's preferred actually.

**Comment by rylew1** [comment]
Be good to actually see 70k results as it is in prod!

**Comment by chouinar** [comment]
Reopening: I still have work on this ticket

**Comment by chouinar** [comment]
Looks like the VPN was changed for connecting to the grants.gov databases, opened a ticket and I'm waiting to hear back. Until then - blocked as I can't get new data to upload.

**Comment by widal001** [comment]
Closing because issue was marked as 'Done' in https://github.com/orgs/HHS/projects/13
