### ISSUE TITLE
[Task]: Add FF based nav link to search (which includes status query params)

### ISSUE THREAD

**Issue by rylew1** [HHS/simpler-grants-gov#1664]
### Summary

Status checkbox should be set to forecasted, and posted

![image](https://github.com/HHS/simpler-grants-gov/assets/93001277/018a9c07-75f1-4eb4-956e-504542146aa2)

### Acceptance criteria

- Initial load of search has `forecasted` and `posted` status checkboxes checked

**Comment by rylew1** [comment]
Open question - @andycochran @crystabelrangel  - should this update the query params on initial load? I'm open to thoughts but kind of leaning that it shouldn't since it's almost implied. If they uncheck forecasted and posted, then re-check those options, it should reflect in the query params.

**Comment by rylew1** [comment]
Also when the error state happen (fetch fails or the API otherwise errors ) - should the 2 default options be checked?

**Comment by andycochran** [comment]
Let's do whatever is easiest here. We will need to test the behavior regardless. 

This is just an idea, please recommend a simpler solution if you have one: 
- If the page is loaded with no query params, do not update them. 
- If no statuses are checked, show results for all statuses (just like other filters)
- The "Search" link in the nav menu can contain query params for the default statuses

Would that work? 

Not sure I understand your error state question.

**Comment by rylew1** [comment]
>If the page is loaded with no query params, do not update them.
This is wrong now right @andycochran ? We revised it.

The latest on query params is that we do want to show `status=forecasted,posted` even if the page is not initially loaded with any QP

**Comment by acouch** [comment]
The decision is that by default the search page shows all results. However internal links should include these two statuses.

**Comment by rylew1** [comment]
Some discussion in slack here: https://betagrantsgov.slack.com/archives/C05TSL64VUH/p1713545861704219
