### ISSUE TITLE
[Task]: Receive edits and approval from HHS design leads for sending email describing Co Design group to SMEs

### ISSUE THREAD

**Issue by rishalee** [HHS/simpler-grants-gov#1670]
### Summary

- Incorporate edits from HHS to #1642 
- Receive approval from HHS to send to HHS Project leads

### Acceptance criteria

- [ ] - Edits have been received and incorporated from HHS Design/Comms leads
- [ ] - Final approval has been given to send to HHS Project Leads

**Comment by andycochran** [comment]
Closing this as "won't do" — adding approval to AC of #1642
