### ISSUE TITLE
[Task]: SearchFetcherProps should be renamed (drop the props)

### ISSUE THREAD

**Issue by rylew1** [HHS/simpler-grants-gov#1680]
### Summary

`SearchFetcherProps` is a type used throughout the frontend to reference query param state. Typically using props in a name is associated with an interface - so this should be renamed .

Could be `SearchFetcherData` or similar

### Acceptance criteria

`SearchFetcherProps` is renamed

**Comment by acouch** [comment]
@rylew1  can we move this to: https://github.com/HHS/simpler-grants-gov/milestone/155 since it is something we want to do before closing this line of work but is not blocking users from testing the search page?
