### ISSUE TITLE
[Task]: Create Transform Table Strategy

### ISSUE THREAD

**Issue by acouch** [HHS/simpler-grants-gov#1687]
### Summary

Document the order and the transform needs for each of the tables so the individual tables can be added #1697 and the transforms applied #1686 . This can done in Gitbook or in the comments here. The need is to identify the type of transform needed (ie grab updates for certain fields or all fields, and what the old / new schema is). Actually writing the SQL can be done in #1686 

### Acceptance criteria

- [ ] Document or update existing docs for transformation needs

**Comment by acouch** [comment]
Closing for #1686

**Comment by widal001** [comment]
Closing because issue was marked as 'Done' in https://github.com/orgs/HHS/projects/13
