### ISSUE TITLE
Receive edits from HHS Design and Comms Lead acceptance email to participants

### ISSUE THREAD

**Issue by rishalee** [HHS/simpler-grants-gov#1695]
### Summary

- Receive edits from HHS for #1693 and incorporate into email
- Receive approval to send to HHS Project Leads

### Acceptance criteria

-Edits have been received from HHS
-Edits have been incorporated
-Approval is communicated to send to HHS Project Leads

**Comment by andycochran** [comment]
Approved by Lucas 9/25
