### ISSUE TITLE
[Task]: Request Access to Additional Tables for Search API Expanded Data Model

### ISSUE THREAD

**Issue by acouch** [HHS/simpler-grants-gov#1696]
### Summary

Request access to additional tables for dev and stage.

After #1569 is approved, we need to ask @bretthrosenblatt for expanded access in order to load additional tables in production.

### Acceptance criteria

- [x] request access for dev/stage
- [x] request access for production

**Comment by acouch** [comment]
@bretthrosenblatt is writing an opps ticket

**Comment by acouch** [comment]
Waiting on approval.

**Comment by sumiat** [comment]
@bretthrosenblatt checking with @marwanabufadel
