### ISSUE TITLE
[Task]: Create wiki for frontend search

### ISSUE THREAD

**Issue by rylew1** [HHS/simpler-grants-gov#1700]
### Summary

We've drawn some diagrams for frontend search and the client/server but we don't have a single place to share and discuss the mechanics of how it all fits together.

This ticket is to create a wiki page to include those diagrams

### Acceptance criteria

Wiki page with diagrams discussing the mechanics of how search works.

**Comment by widal001** [comment]
Closing because issue was marked as 'Done' in https://github.com/orgs/HHS/projects/13
