### ISSUE TITLE
[Task]: Set up Tremendous for research incentives 

### ISSUE THREAD

**Issue by andycochran** [HHS/simpler-grants-gov#1701]
### Summary

Nava needs to set up a Tremendous account for incentives disbursement.

### Acceptance criteria

- [x] Tremendous account is established where we fund research incentives 
- [x] Nava has provided user accounts to staff for distributing incentives to research (and Code Challenge) participants
  - [x] @andycochran 
  - [x] @rishalee 
  - [x] @crystabelrangel 
  - [x] @btabaska

**Comment by margaretspring** [comment]
Pursuing ASAP, but likely to not be implemented until Sprint 24.
