### ISSUE TITLE
[Task]: Open Source Onboarding - Gabriel Watson

### ISSUE THREAD

**Issue by btabaska** [HHS/simpler-grants-gov#1709]
### Summary

Onboard Gabriel Watson to the Open Source Community

### Acceptance criteria

- [ ] Submitted Checklist
- [ ] Slack Onboarded
- [ ] GitHub Code Cloned

**Comment by btabaska** [comment]
Individual has been onboarded.

**Comment by widal001** [comment]
Closing because issue was marked as 'Done' in https://github.com/orgs/HHS/projects/13
