### ISSUE TITLE
[Task]: Open Source Onboarding - Jessie Mahr

### ISSUE THREAD

**Issue by btabaska** [HHS/simpler-grants-gov#1710]
### Summary

Onboard Jassie Mahr to the Open Source Community

### Acceptance criteria

- [ ] Onboarding Checklist Filled out
- [ ] Onboarded to Slack
- [ ] GitHub Code Setup Locally

**Comment by widal001** [comment]
Closing because issue was marked as 'Done' in https://github.com/orgs/HHS/projects/13
