### ISSUE TITLE
[Task]: Open Source Onboarding - Devin Cunningham

### ISSUE THREAD

**Issue by btabaska** [HHS/simpler-grants-gov#1712]
### Summary

Onboard Devin Cunningham to the Open Source Community

### Acceptance criteria

- [ ] Google Form Onboarding Checklist Submitted
- [ ] GitHub Cloned Locally
- [ ] Onboarded to Slack

**Comment by btabaska** [comment]
Individual has completed onboarding

**Comment by widal001** [comment]
Closing because issue was marked as 'Done' in https://github.com/orgs/HHS/projects/13
