### ISSUE TITLE
Search UI – participant recruiting and scheduling with grantors

### ISSUE THREAD

**Issue by sumiat** [HHS/simpler-grants-gov#1718]
### Summary
Recruit grantors for search ui usability testing and set up scheduling 

### Acceptance Criteria
- [ ] Schedule sessions with grantors for search ui usability testing

### Open questions
- Do we need to check with Lucas/Julius on the grantors we're doing usability testing with? Yes

**Comment by crystabelrangel** [comment]
In the process of recieving grantors from Emily and Lucas.

**Comment by andycochran** [comment]
Recruiting messaging approved by MH, sent to HHS.

**Comment by crystabelrangel** [comment]
Hi @lucasmbrown-usds! I want to start contacting Grantors and was reviewing our previous list. I was wondering if by any chance you've been able to get a direct contact from SBA community navigators, Environmental Justice Thriving, or Rural Partners Network?

![Image](https://github.com/user-attachments/assets/4574de3c-5e36-486f-8d26-24e50fe0c143)

**Comment by crystabelrangel** [comment]
emailed 11 grantors today.
