### ISSUE TITLE
[Task]: Draft Outline of Recruiting and Screening Process

### ISSUE THREAD

**Issue by rishalee** [HHS/simpler-grants-gov#1729]
### Summary

-Draft outline of full process of recruitment
-Submit to MH for edits and approval for passing to HHS

### Acceptance criteria

-Full process is drafted
-MH edits have been incorporated and approval to be sent to HHS is received

**Comment by alexis-bunc** [comment]
Thanks @rishalee! I have a few documents in the queue right now and will take a look by EOD tomorrow.

**Comment by CarleyKimball** [comment]
Reviewed and added a few minor edits. I see they were accepted. Thanks @rishalee. Would still like to give @alexis-bunc time to review before we send forward.

**Comment by rishalee** [comment]
Approval received by slack on 4/19/24
