### ISSUE TITLE
[Task]: Draft Co-Design Group Intake Script and receive MH approval

### ISSUE THREAD

**Issue by rishalee** [HHS/simpler-grants-gov#1731]
### Summary

- Draft Co-Design Group Intake Script to use in initial calls with participants
- Receive edits from MH and approval to pass to HHS

### Acceptance criteria

- Co-Design Group intake script is drafted
- Edits have been received and incorporated from MH
- Approval to pass to HHS has been received

**Comment by rishalee** [comment]
Sent to @CarleyKimball and @alexis-bunc for approval 4/19:
https://docs.google.com/document/d/16OeC972hwg60al6qpAE073tAj37NV_BpdYmI2vcH8u0/edit

**Comment by rishalee** [comment]
Approval received by slack 4/19

**Comment by CarleyKimball** [comment]
Added edits and comments. Please allow @alexis-bunc time to review before proceeding.

**Comment by alexis-bunc** [comment]
Added notes in the doc. Thank you!

**Comment by rishalee** [comment]
4/22: received verbal approval in comms meeting
