### ISSUE TITLE
[Task]: Draft invitation email for potential participants

### ISSUE THREAD

**Issue by rishalee** [HHS/simpler-grants-gov#1733]
### Summary

- Draft invitation email for potential participants
- Receive edits from MH and approval to pass onto HHS

### Acceptance criteria

- Invitation email has been drafted
- Edits from MH have been incorporated
- Approval to pass onto HHS has been received

**Comment by rishalee** [comment]
Shared in slack and by email with @alexis-bunc and @CarleyKimball on 4/16/24

**Comment by alexis-bunc** [comment]
I left a few suggestions on the email, let me know if you have any questions.

**Comment by alexis-bunc** [comment]
Unassigned myself after addressing comments.

**Comment by CarleyKimball** [comment]
Adding minor edits. Sending back to @rishalee

**Comment by rishalee** [comment]
approval from @CarleyKimball on 4/17/24

**Comment by rishalee** [comment]
4/17 Received comments from @itsemilyianacone and implemented; 4/18  received comments from Adriana Weitzman and implemented - awaiting approval for existing copy pending integration of information
