### ISSUE TITLE
[Task]: Draft messaging to go out to grantors for recruiting

### ISSUE THREAD

**Issue by andycochran** [HHS/simpler-grants-gov#1756]
### Summary

Draft the email message that we will send to grantors who are potential research participants. Talked to comms and they agreed that the comms approval process is not needed. 

### Acceptance criteria

- [x] Draft the email message to send to grantors
- [x] Review with MH and HHS
- [x] Incorporate feedback into draft
- [x] Approval from HHS

**Comment by crystabelrangel** [comment]
[Link to email draft](https://docs.google.com/document/d/1-IYqCi0Lld67mDaYoFTmlMZiG6daSFJQgXOakZGtzQg/edit?usp=sharing)

**Comment by andycochran** [comment]
LGTM!

**Comment by crystabelrangel** [comment]
Draft has been sent to MH (Carley and Alexis) to review.

**Comment by alexis-bunc** [comment]
Added two notes for consideration in Google Docs

**Comment by widal001** [comment]
Closing because issue was marked as 'Done' in https://github.com/orgs/HHS/projects/13
