### ISSUE TITLE
Create an email account where participants can send responses

### ISSUE THREAD

**Issue by rishalee** [HHS/simpler-grants-gov#1766]
### Summary

- An email account without a staff name on it should be set up for participants and co design group team to communicate through as the official contact point

### Acceptance criteria

- [x] An email has been decided upon - CoDesign@grant.gov
- [x] Email account has been created

**Comment by rishalee** [comment]
@sumiat setting up amazon workplace account

**Comment by rishalee** [comment]
4/23: followed up in standup with @ebuwa-evbuoma-fike to follow up with marwan

**Comment by margaretspring** [comment]
@ebuwa-evbuoma-fike Thank you for looking into this. I created a ticket in MH's Jira to pursue it. It's https://hhsgrants.atlassian.net/servicedesk/customer/portal/5/SO-35 (only accessible to those w/ access to MH's Jira).

**Comment by sumiat** [comment]
Waiting for Oscar and Marwan to create the email

**Comment by andycochran** [comment]
- CoDesign@grants.gov inbox requested on May 1, 2024 
- @margaretspring to follow up

**Comment by andycochran** [comment]
Done
