### ISSUE TITLE
[Tech spec]: Delivery dashboard

### ISSUE THREAD

**Issue by sumiat** [HHS/simpler-grants-gov#1768]
Update the delivery spec in Gitbook for the delivery dashboard based on the new template.

**Comment by acouch** [comment]
The ADRs tell most of the story:

* [Delivery Dashboard data storage](https://github.com/HHS/simpler-grants-gov/blob/main/documentation/decisions/adr/2024-03-19-dashboard-storage.md)
* [Delivery Dashboard Tool](https://github.com/HHS/simpler-grants-gov/blob/main/documentation/decisions/adr/2024-04-10-dashboard-tool.md)
* ETL workflow ([to be written](https://github.com/HHS/simpler-grants-gov/issues/1248))
* Updated diagram ([to be created](https://github.com/HHS/simpler-grants-gov/issues/1265))

**Comment by acouch** [comment]
I created a merge request for @sumiat and @widal001 to give initial review.

**Comment by sumiat** [comment]
Thanks @acouch! I reviewed and LGTM

**Comment by sumiat** [comment]
@widal001 approved as well. i merged the changes: https://app.gitbook.com/o/cFcvhi6d0nlLyH2VzVgn/s/Pm7UEzeiS1tbLCV1SFRu/product/deliverables/specifications/delivery-dashboard/delivery-dashboard-technical-spec
