### ISSUE TITLE
[Task]: Update API metrics on the public wiki

### ISSUE THREAD

**Issue by sumiat** [HHS/simpler-grants-gov#1786]
### Acceptance Criteria

- [ ] Update the [public wiki](https://app.gitbook.com/o/cFcvhi6d0nlLyH2VzVgn/s/Pm7UEzeiS1tbLCV1SFRu/analytics/simpler-grants.gov-analytics/api-metrics) with API metrics for the appropriate sprint dates. Spreadsheet to update the metrics can be found here: https://docs.google.com/spreadsheets/d/19dftxSepvjVz_sil-eEL92FTMApRWJJ7Pq74JQh96Kg/edit#gid=1208306053

**Comment by mxk0** [comment]
Closing as reporting like this will be handled by automated Metabase reports moving forwards.
