### ISSUE TITLE
[Task]: Update the open source onboarding metrics page on the public wiki

### ISSUE THREAD

**Issue by sumiat** [HHS/simpler-grants-gov#1787]
### Acceptance Criteria 

- [ ] Update the public wiki with open source metrics for the appropriate sprint

**Comment by sumiat** [comment]
Created a change request here: https://app.gitbook.com/o/cFcvhi6d0nlLyH2VzVgn/s/Pm7UEzeiS1tbLCV1SFRu/~/changes/95/product/deliverables/specifications/search-api
and spreadsheet to update is here: https://docs.google.com/spreadsheets/d/1eI2SaIktvVadBG3t-_-nM0yFY433YBfVZGHL7zG3mO4/edit#gid=0

**Comment by btabaska** [comment]
It looks like I can't edit while it is your change request, so we will need to merge prior to adding the metrics. I'll take a look once we merge.

**Comment by sumiat** [comment]
@btabaska - can you add the gh metrics in the spreadsheet https://docs.google.com/spreadsheets/d/1eI2SaIktvVadBG3t-_-nM0yFY433YBfVZGHL7zG3mO4/edit#gid=0? That will update in GitBook.

**Comment by widal001** [comment]
Closing because issue was marked as 'Done' in https://github.com/orgs/HHS/projects/13
