### ISSUE TITLE
[Task]: Update Get Opportunity Metrics

### ISSUE THREAD

**Issue by margaretspring** [HHS/simpler-grants-gov#1789]
This task is to add the metrcis for the sprint end.

The steps are documented here: https://app.gitbook.com/o/cFcvhi6d0nlLyH2VzVgn/s/v1V0jIH7mb7Yb3jlNrgk/engineering/operations/collecting-project-metrics

**Comment by widal001** [comment]
Closing because issue was marked as 'Done' in https://github.com/orgs/HHS/projects/13
