### ISSUE TITLE
Investigate date rounding bug on search ui

### ISSUE THREAD

**Issue by rylew1** [HHS/simpler-grants-gov#1806]
### Summary

 Noticing on the UI locally that the dates are off-by-1 (eg. 2023-04-23 is rendering as April 22, 2024) 

### Acceptance criteria

Dates are not rounding and match API response dates

**Comment by mdragon** [comment]
In the past I've seen these where a UTC time of midnight is being interpreted as local, so it's the day before. Typically I've gotten around this by wedging in a noon or adding 12 hours so that no matter the timezone (US centric) you're in the correct day even after UTC/local conversions.

**Comment by mxk0** [comment]
Already fixed.
