### ISSUE TITLE
[Task]: Setup Step Function / Orchestration for Transformations

### ISSUE THREAD

**Issue by acouch** [HHS/simpler-grants-gov#1809]
### Summary

Copy existing oracle data task.

### Acceptance criteria

- [ ] data loads in AWS from oracle to postgres and transformations work

**Comment by jamesbursa** [comment]
The command it should run is:

```
poetry run flask data-migration load-transform --load --no-transform --no-set-current
```

so that only the load part of the process is enabled.

**Comment by coilysiren** [comment]
👍

**Comment by coilysiren** [comment]
Two notes:

- we shouldn't be running this in dev right now
- we want to run it daily, since the performance isn't at the place where we can run it every X minutes
