### ISSUE TITLE
[30k]: Co-Design Group kickoff

### ISSUE THREAD

**Issue by widal001** [HHS/simpler-grants-gov#1822]
### Key links

- Deliverable specification
- [Simpler Grants.gov full roadmap](https://github.com/orgs/HHS/projects/12)
- 10k milestones

### Description

- **What:** Recruit and onboard the first cohort of the Co-Design Group to provide ongoing feedback on our product and roadmap.
- **Why:** Ensures that Simpler.Grants.gov HHS decision makers design with the most underserved communities in the grants ecosystem and create continuous feedback loops to ensure equitable product development. This kickoff proves that we've addressed the open questions and needs surfaced during the planning process.
- **Who**
  - The most underserved applicant individuals/groups within the grants ecosystem
  - Internal Simpler.Grants.gov stakeholders

> [!NOTE]
> For more information about this deliverable, please refer to the deliverable specification linked above.

**Comment by sumiat** [comment]
**Weekly Update 5/8**

**What has been done?**
- Started drafting collaborative activities for the first cohort

**Status**
- Planning

**Risk**
- Requested to be phrased as if/then so impact understood. 

**Deliverable Date**
- TBD

**What will be done?**
- Determine a delivery date for the completion of the Co-Design Group kickoff deliverable
- Finish the drafting the activities for the first cohort

**Comment by widal001** [comment]
Replacing our old deliverable tickets with a new ticket format
