### ISSUE TITLE
Send Co-Design Group expectations email to SMEs 

### ISSUE THREAD

**Issue by rishalee** [HHS/simpler-grants-gov#1837]
### Summary

Send email to SMEs detailing group expectations and compensation so they can reach out and provide info to contacts who would be good fits for the Co-Design Group. 

Blocked by #1642

### Acceptance criteria

- [ ] All SMEs have been contacted and asked to provide Co-Deign Group contacts

**Comment by andycochran** [comment]
@rishalee this still says "Blocked by #1642" (which is marked as done). If this task is no longer blocked, please update the description.
