### ISSUE TITLE
[Task]: Move community feedback strategy document to the wiki

### ISSUE THREAD

**Issue by sumiat** [HHS/simpler-grants-gov#1841]
### Summary

The [community feedback proposal](https://docs.google.com/document/d/18D0-KPZ5B1PAacXzJEqGALVpa9C3b3jlaTjBVvawrMc/edit#heading=h.g09r0bw50012) has been created in a word doc and added to the wiki

### Acceptance criteria

- [ ] Add the [community feedback proposal](https://docs.google.com/document/d/18D0-KPZ5B1PAacXzJEqGALVpa9C3b3jlaTjBVvawrMc/edit#heading=h.g09r0bw50012) to the internal wiki

**Comment by andycochran** [comment]
Change request up: https://app.gitbook.com/o/cFcvhi6d0nlLyH2VzVgn/s/v1V0jIH7mb7Yb3jlNrgk/~/changes/581/about-us/community-feedback-strategy
