### ISSUE TITLE
[Task]: Delivery Dashboard - Metabase - finish configuring WAF

### ISSUE THREAD

**Issue by coilysiren** [HHS/simpler-grants-gov#1871]
### Summary

Followup from https://github.com/HHS/simpler-grants-gov/pull/1856#discussion_r1581567424

### Acceptance criteria

- [ ] WAF `aws_wafv2_web_acl_logging_configuration` deployed
- [ ] frontend staging passes all deployment checks

**Comment by coilysiren** [comment]
via @aplybeah!

> Terraform has updated the docs to address this: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/wafv2_web_acl_logging_configuration.html

**Comment by coilysiren** [comment]
It looks like the same issue is currently blocking on staging frontend deploy: 

https://github.com/HHS/simpler-grants-gov/actions/runs/8914895196/job/24484125422

**Comment by aplybeah** [comment]
Pulling this into the current sprint before this becomes an issue for too long
cc @acouch @sumiat @margaretspring
