### ISSUE TITLE
Metabase - configure Google SSO

### ISSUE THREAD

**Issue by coilysiren** [HHS/simpler-grants-gov#1872]
### Summary

https://www.metabase.com/docs/v0.49/people-and-groups/google-and-ldap.html#enabling-google-sign-in

### Acceptance criteria

- [ ] in dev
- [ ] in staging
- [ ] in prod

**Comment by mxk0** [comment]
Closing in favor of https://github.com/HHS/simpler-grants-gov/issues/2391.
