### ISSUE TITLE
[Task]: Co-Design Group resourcing

### ISSUE THREAD

**Issue by rishalee** [HHS/simpler-grants-gov#1873]
### Summary

- Outline the requirements for executing the co design group as currently scoped
- Work with Nava program manager on scoping

**Comment by rishalee** [comment]
4/29: Request shared by slack for additional headcount with @andycochran and @margaretspring: https://docs.google.com/document/d/1TtoFpjpPRL83xSA6qZZWfoyOkTWGgrGJSlcO3d5RA-M/edit#heading=h.17qv91x8upy4

**Comment by andycochran** [comment]
Calling this done.
