### ISSUE TITLE
[Tech spec]: Opp listing synopsis first draft

### ISSUE THREAD

**Issue by sumiat** [HHS/simpler-grants-gov#1877]
The tech spec is a living document. We want to start the first draft of the tech spec for the opportunity listing page synopsis so that we can start to think about how we will breakdown the work 

### Acceptance Criteria

- [x] Draft the opp listing synopsis tech spec
- [x] Have Aaron review and add to the spec for the first draft version.

**Comment by sumiat** [comment]
@acouch - this is ready for your review: https://app.gitbook.com/o/cFcvhi6d0nlLyH2VzVgn/s/Pm7UEzeiS1tbLCV1SFRu/~/changes/105/product/deliverables/specifications/opportunity-listing-synopsis

**Comment by acouch** [comment]
I created a scratch pad here: https://docs.google.com/document/d/1hXFIK7nsgUMClw-70eg1aAPdE-DKqJYNxeDSv_tXTu4/edit

**Comment by acouch** [comment]
Met w/ @sumiat and @andycochran on this, worked on the 30k dashboard estimates. Next steps are to figure out how much API work we want to bite off.

**Comment by sumiat** [comment]
Next work is in the #1883
