### ISSUE TITLE
Add GA4 tracking for number of searches made per search term

### ISSUE THREAD

**Issue by btabaska** [HHS/simpler-grants-gov#1891]
### Summary

Number of searches made per search term and the click conversion rate to the opportunity listing: might be the same configuration as the first one: https://support.google.com/analytics/answer/1032321?hl=en#zippy=%2Cin-this-article

### Acceptance criteria

Number of searches made per search term and the click conversion rate to the opportunity listing

**Comment by mxk0** [comment]
I can't tell why I closed this. Is the tracking already in place?

**Comment by mxk0** [comment]
Yes, we already have this.
