### ISSUE TITLE
Spike: Review GA4 tracking for click-through-rate from a search results page to an opportunity listing

### ISSUE THREAD

**Issue by btabaska** [HHS/simpler-grants-gov#1892]
### Summary

This is part of ensuring we have instrumentation that will allow us to measure search accuracy as defined in the Metrics section of #2200.

We have an older implementation of this tracking using GA4. This ticket is to review the GA tracking to see if it's still working. This should be time-boxed to a couple of hours and if there's anything resembling a rabbit hole we should avoid it and check in with @mdragon or @mxk0.

### Acceptance criteria

- [ ] GA tracking reviewed, report back on findings
- [ ] Ticket created for any work needed to implement click through rate tracking

**Comment by mikehgrantsgov** [comment]
What we have here should be sufficient to track click-through rate. Here is a closed funnel (i.e. steps must happen in the order specified) I put together in GA which should track this:
https://analytics.google.com/analytics/web/#/analysis/p404968752/edit/LA7n0MzdQ76EaDpv5WvATA

The funnel first matches on a search_term event followed immediately by a page event with the title matching "Opportunity Listing -" (the opportunity page). Data here is delayed by a day, so I will check tomorrow if my searches / actions matching this funnel would generate data.

cc @mdragon

**Comment by mikehgrantsgov** [comment]
Here is another Path Exploration of the user flow from the Search Page:
https://analytics.google.com/analytics/web/#/analysis/p404968752/edit/LtxZZeUCTbmoXUUXvntx7w

**Comment by mdragon** [comment]
Hmm, both these links say I don't have permissions. @margaretspring can you check if you can access these, and if so can you double check my permissions in that Project/Property?

**Comment by mxk0** [comment]
It sounds like we should be good to go with this tracking. For completeness, I added an acceptance criterion to make a new ticket for any follow-up work needed (just in case we need to add/fix the tracking).
