### ISSUE TITLE
[Task]: New Relic Sizing Questionnaire 

### ISSUE THREAD

**Issue by acouch** [HHS/simpler-grants-gov#1908]
### Summary

We need the following details for sizing our New Relic instance:

Sizing
- Application instance count: **3? API, Frontend, Analytics**
- Describe the current application operating behavior: Low/Medium/High errors/throughput: **low throughput** 
- Rough average container count: **10 ~ 20**
- Rough server count for any EC2s you may have: **1 ~ 3**
- Log Data currently in GB: **~40GB** (mostly VPC flow logs) or **~10GB** (without the flow logs)
- How many engineers that would need to fix code or troubleshoot issues?: **~10**
- What are your data retention needs?: **5 years per security controls**

### Acceptance criteria

- [x] Responses completed in this ticket

**Comment by coilysiren** [comment]
@acouch I added answers to the questions
