### ISSUE TITLE
[Task]: Add GA4 ID for Dev Site

### ISSUE THREAD

**Issue by acouch** [HHS/simpler-grants-gov#1918]
### Summary

In order to setup the metrics for the search before there is data in prod, this task is to add a GA4 id to the dev site so that there is data to create the desired reports.

### Acceptance criteria

- [ ] GA4 ID added and working in dev

**Comment by widal001** [comment]
Closing because issue was marked as 'Done' in https://github.com/orgs/HHS/projects/13
