### ISSUE TITLE
Create documentation for running Analytics locally

### ISSUE THREAD

**Issue by acouch** [HHS/simpler-grants-gov#1928]
### Summary

With #1914 we have a working container that can connect to a local analytics database. Once we have the ETL tool running locally with the connection to postgres we need to document how to setup and run it locally. This should go in the analytics readme folder.

### Acceptance criteria

- [ ] Clear instructions for new users to stand up the analytics dashboard, database, and run the github transforms.

**Comment by coilysiren** [comment]
The majority of this documentation already exists here: https://github.com/HHS/simpler-grants-gov/tree/main/documentation/analytics. It just needs to be extended for recent work.
