### ISSUE TITLE
Upgrade to React 19

### ISSUE THREAD

**Issue by rylew1** [HHS/simpler-grants-gov#1935]
### Summary

https://react.dev/blog/2024/04/25/react-19

Could be several changes to server actions and our search page and the hooks we were using like `useFormStatus`.

### Acceptance criteria

- React upgraded to v 19

**Comment by acouch** [comment]
A number of the project dependencies aren't compatible with React 19 yet. Here are links to some of them:

* next-intl: https://github.com/amannn/next-intl/issues/1075
* react-uswds: https://github.com/trussworks/react-uswds/issues/3045
*

**Comment by mxk0** [comment]
Re-opening for...some day.

**Comment by mdragon** [comment]
Replacing this with Next 15 upgrade ticket which will bring us to React 19 #2621
