### ISSUE TITLE
[Task]: Create outline for contact-us email process

### ISSUE THREAD

**Issue by alexis-bunc** [HHS/simpler-grants-gov#1948]
### Summary

- [ ] Review and provide feedback for contact-us email process documented in GitBook

### Acceptance criteria

Link to process: https://app.gitbook.com/o/cFcvhi6d0nlLyH2VzVgn/s/v1V0jIH7mb7Yb3jlNrgk/~/changes/569/communications/email-approval/contact-us-email-approvals/contact-us-email-process

**Comment by CarleyKimball** [comment]
@alexis-bunc Looks great! No changes on my end.

**Comment by CarleyKimball** [comment]
Assigning to @meghscase for a quick look.

**Comment by meghscase** [comment]
This looks good to me. The only thing I might consider adding is something about how if there becomes a critical mass of a topic that doesn't fit a current template, a template will be developed with the normal process. 

cc: @alexis-bunc @CarleyKimball
