### ISSUE TITLE
[Task]:  Sort by Posted Date desc by default

### ISSUE THREAD

**Issue by rylew1** [HHS/simpler-grants-gov#1957]
### Summary

More useful to users to sort by Posted Date desc be default

### Acceptance criteria

- Default API call to Posted Date desc
- Posted Date desc comes by default first in the list
- Posted Date asc is 2nd (move them both up)

**Comment by rylew1** [comment]
@andycochran can you verify this ticket is correct?

**Comment by andycochran** [comment]
LGTM (just added a note about moving the ascending version up too so they stay together)
