### ISSUE TITLE
[Task]: Scheduled Reminders Slack Integration for Github

### ISSUE THREAD

**Issue by acouch** [HHS/simpler-grants-gov#1962]
### Summary

Setup this functionality by connecting our Github to our Slack instance

=> https://docs.github.com/en/organizations/organizing-members-into-teams/managing-scheduled-reminders-for-your-team

This requires an HHS organization admin to setup, as it works on a Github organization level.

### Acceptance criteria

- [ ] scheduled reminders added to `#topic-pull-requests`

**Comment by coilysiren** [comment]
done https://betagrantsgov.slack.com/archives/C072ZJTGRED/p1715274501668449
