### ISSUE TITLE
[Bug]: Unbounded pagination shows extra pagination pages 

### ISSUE THREAD

**Issue by rylew1** [HHS/simpler-grants-gov#1965]
### Summary

```
      <Pagination
        pathname="/search"
        currentPage={page}
        // totalPages={totalPages} // this was removed to make this component "unbounded"
        maxSlots={MAX_SLOTS} // constant set to 5
        onClickNext={() => handlePageChange(page + 1)}
        onClickPrevious={() => handlePageChange(page - 1)}
        onClickPageNumber={(event, page) => handlePageChange(page)}
      />
```

When we removed the `totalPages` prop from being passed into `SearchPagination` in order to make the component "unbounded" - I believe this impacts the number of pages shown in the `SearchPagination` component when the results are less then the number of `MAX_SLOTS` (set to 5)

For example -
- On initial load - there's full set of results and 5 pagination "slots" - (page 1, page 2, page 3, an ellipses, and a next button):
![image](https://github.com/HHS/simpler-grants-gov/assets/93001277/f7188cdf-343a-4065-9e13-466c7a38b9c9)

- When you filter the results just down to 3 results - there's still 5 pagination "slots" - but nothing actually on anything other than the 1st page:

![image](https://github.com/HHS/simpler-grants-gov/assets/93001277/b5acc1e7-2cd1-4349-abdc-e323a8c6e9ae)

So we do need to manually calculate a `totalPages` if the number of pages is less than 3 I believe. 

### Acceptance criteria

- If we want to keep the Pagination "unbounded" - have some logic to display the correct number of Pagination pages

**Comment by rylew1** [comment]
cc @andycochran if you have a moment can you take a peek at this?

**Comment by andycochran** [comment]
Brainstorming options: https://betagrantsgov.slack.com/archives/C05TGEL3C6Q/p1715213399388129

**Comment by rylew1** [comment]
- Reintroduce `totalPages` 
- Go up to `MAX_SLOTS` of 7

- Stretch:  
     - Change size of pagination via `theme-pagination-font-family` in css settings
     - Check if there's still there overflow at certain widths
