### ISSUE TITLE
[Task]: Move Issues from NavaPBC to HHS Simpler Repo

### ISSUE THREAD

**Issue by acouch** [HHS/simpler-grants-gov#2028]
### Summary

[Nava forked the existing project ](https://github.com/navapbc/simpler-grants-gov)and contributed numerous features. The work there was tracked in Github issues. We would like to move those issues over to this repository.

Issues should be moved with the same title, body, state (open/closed) and labels.

Once the issues are moved and code merged we can archive this repository.

### Acceptance criteria

- [x] Github issues moved
- [x] state maintained
- [x] creators and assignees maintained
- [ ] labels maintained

**Comment by acouch** [comment]
The current approach would allow us to move issues, comments, and labels but not milestone and project data.

**Comment by coilysiren** [comment]
@acouch I think this is done?

**Comment by acouch** [comment]
Yes, thanks.
