### ISSUE TITLE
[Task]: Merge Nava fork

### ISSUE THREAD

**Issue by acouch** [HHS/simpler-grants-gov#2029]
### Summary

[Nava forked the existing project ](https://github.com/navapbc/simpler-grants-gov)and contributed numerous features. This task is to merge that work to this work. To do this we can create a PR. If we merge the individual commits (no squash) we will maintain the history.

There are two issues with that history:

1) links to PRs would wrong
2) links to issues would be wrong

## Options

To deal with the incorrect links we could do one of the following. This is an example commit:

```
[Issue #86] Download the search response as a CSV file (#87)
## Summary
Fixes #86

### Time to review: __10 mins__

## Changes proposed
Modified the search endpoint to be able to return its response as a CSV
file...
```

The new issue number is 123456

### 1. Remove the links to PRs and update the issue #s that we track from #2028 

```
[Issue #123456] Download the search response as a CSV file 
## Summary
Fixes #123456

### Time to review: __10 mins__

## Changes proposed
Modified the search endpoint to be able to return its response as a CSV
file...
```

### 2. Same as 1 but update the links to the PRs so they point to the forked PRs with a message in the history

```
[Issue #123456] Download the search response as a CSV file (#navapc/simpler-grants-gov/pulls/87)
## Summary
Fixes #123456

### Time to review: __10 mins__

## Changes proposed
Modified the search endpoint to be able to return its response as a CSV
file...
```

### 3. Just remove the links to the PRs and issues (saves time)

```
Download the search response as a CSV file
## Summary

### Time to review: __10 mins__

## Changes proposed
Modified the search endpoint to be able to return its response as a CSV
file...
```

### Acceptance criteria

- [ ] Nava forked commits and features are merged to HHS repo

**Comment by mdragon** [comment]
I think there is some value in going with Option 2 for the Nava team to have that context and be able to get back to the PR as we continue to build and support the software. I wouldn't anticipate it being super confusing to have a handful of commits linking back to a non-public PR in the grand scheme of the repo's commit history, so I think we should transform the issue number and fix the reference to match the original PR.
