### ISSUE TITLE
[Bug]: Browser Console Error "Image with src "/_next/static/media/grants-gov-logo.7f89963e.png" has either width or height modified"

### ISSUE THREAD

**Issue by acouch** [HHS/simpler-grants-gov#2099]
---

Migrated from https://github.com/navapbc/simpler-grants-gov/issues/165
Originally created by @acouch on *Tue, 23 Jul 2024 18:29:24 GMT*

---

### What happened?

The following appears in the browser console:

```
Image with src "/_next/static/media/grants-gov-logo.7f89963e.png" has either width or height modified, but not the other. If you use CSS to change the size of your image, also include the styles 'width: "auto"' or 'height: "auto"' to maintain the aspect ratio
```

Removing `.maxh-15` fixes it but creates a visual issue on mobile. See: https://github.com/navapbc/simpler-grants-gov/pull/101#discussion_r1668887457

### Steps to reproduce the behavior

View site in locally with the browser console open.

### Priority

low (inconvenience)

### Relevant log output

```shell
see above
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by emilycnava** [comment]
Picking this up
