### ISSUE TITLE
Github Automations Needed

### ISSUE THREAD

**Issue by acouch** [HHS/simpler-grants-gov#2134]
---

Migrated from https://github.com/navapbc/simpler-grants-gov/issues/114
Originally created by @margaretspring on *Fri, 28 Jun 2024 04:02:32 GMT*

---
Place to capture automations that seem like they'd be useful to make GitHub a better planning & tracking tool. 

**At Issue creation**
- [ ] Create a table for team members identifying which Track (from the custom field list) they typically work on (e.g. Alsia - Infra). When issues are created, auto-assign Track to the issue based on the Track of the person creating the issues. This will only be at issue creation, so if someone creates an issue for another Track, they can manually update it.  
- [ ] Status - Make No Status updated to default of "To Do"

**Batch overnight updates**
- [ ] For each Milestone, check if there is an issue with the custom field "Level" assigned 10K - Milestone that is assigned to the Milestone. If there is, pull the "100K HHS Goal" or "30K  Deliverable" custom field assignments from the issue with "Level" 10K - Milestone and assign it to any issues assigned to that Milestone missing those 2 fields.  One exception we might want to make is for any issue assigned to a Milestone that includes the "fast follow' in the title?

**Pending/Open Question**
* Can we have all PRs in repository default assigned to the Project so they show up & team doesn't need to assign them? Will also ease Assignee/Reviewer confusion as Reviewer assigned will display in the Sprint Board. 
*

**Comment by acouch** [comment]
---

Migrated from https://github.com/navapbc/simpler-grants-gov/issues/114#issuecomment-2237038020
Originally created by @margaretspring on *Thu, 18 Jul 2024 16:31:51 GMT*

---
Hey there @aplybeah - Not sure this is complete, but happy to huddle up & discuss. Just grab some time when works for you. Thanks!

**Comment by margaretspring** [comment]
Closing as these were notes for automations we were trying to rig up before we got into the GitHub issue hierarchy beta.
