### ISSUE TITLE
[Task]: Search agency name is incorrect

### ISSUE THREAD

**Issue by acouch** [HHS/simpler-grants-gov#2172]
---

Migrated from https://github.com/navapbc/simpler-grants-gov/issues/5
Originally created by @rylew1 on *Tue, 14 May 2024 22:47:44 GMT*

---
### Summary

 In the search results, for agency name, you’re using the agency code and/or name from the summary object. We don’t want to do that, that data is junk (I should remove them from the API response entirely), we only want to use the agency in the top-level opportunity object.
 
 
 see slack thread https://nava.slack.com/archives/C057K146W8H/p1715720160675029

### Acceptance criteria

- correct agency info displays

**Comment by emilycnava** [comment]
Looking into this
