### ISSUE TITLE
[Task]: Update Maintainers.MD and CODEOWNERS

### ISSUE THREAD

**Issue by acouch** [HHS/simpler-grants-gov#2193]
### Summary

We have some new folks on the project. This task is to update https://github.com/HHS/simpler-grants-gov/blob/main/MAINTAINERS.md and https://github.com/HHS/simpler-grants-gov/blob/main/.github/CODEOWNERS

**Comment by chouinar** [comment]
If possible, the best approach would be to use github groups that way we can modify the groups via the Github UI without needing a PR, but I know that would require working with whoever owns the HHS space on Github.

Either way, my two cents for the codeowners configuration:
* For the API folder, I'd put me, Matt Dragon, and whichever Focus engineers will be working on the backend
* It might be worth setting another more specific rule for things like the API schema file to also include some frontend folks
* If we want to get even more specific, some of the CI/CD in the .github folder that pertains to the API might be useful to include the API folks as well.

Also, we should make sure to update the [renovate.json](https://github.com/HHS/simpler-grants-gov/blob/main/.github/renovate.json#L15) file configuration which specifies who gets added to PRs.

**Comment by coilysiren** [comment]
> but I know that would require working with whoever owns the HHS space on Github

We have a contact for this, but they're far enough away from the project that I don't think we would want to pull them in for every staffing change.

**Comment by acouch** [comment]
Closing as the work described in the summary was completed.
