### ISSUE TITLE
Search *

### ISSUE THREAD

**Issue by margaretspring** [HHS/simpler-grants-gov#2200]
### Summary

Grant seekers can search, filter, and sort opportunities on simpler.grants.gov

### Press release

We are pleased to announce that Simpler.Grants.gov now has improved search capabilities that will make it easier for the public to find grant opportunities published by Grants.gov. These features include more relevant search results based on keywords, filtering and sorting, the ability to easily share and bookmark search results, and an easier to use interface.

Test users of the new search page reported that they find it to be a significant improvement over existing grants search options.

### Acceptance criteria

- [x] **Search, filter, and sort:** Users can
  - [x] search opportunities by keyword
  - [x] filter by at least 3 structured fields
  - [x] sort by relevance and 3 additional fields
- [x] **Stateful UI:** Search criteria are reflected in the URL, so that users can bookmark or share the link to a page with a given combination of search criteria.
- [x] **API parity:** All search features available via the UI are also available via API.
- [x] **Load testing:** Load testing performed to assess whether we can simulate 2,000 concurrent users with our current infrastructure.

### Metrics

- [x] **Adoption:** At least 10,000 unique users have used the search UI, and at least 5 unique users have used the search directly from the API endpoint (i.e., not via the UI).
- [x] **Reliability:** The monthly average error rate remains below 5%, meaning fewer than five 5xx errors per 100 API and five 5xx errors per 100 page requests in production.
- [x] **Search accuracy:** Set a baseline metric for accuracy, as measured by monthly click-through rate (CTR) for results on the first page.

**Comment by lucasmbrown-usds** [comment]
FYI, I updated the Search accuracy metric to reflect our proposed new language about setting a baseline.

**Comment by mxk0** [comment]
Internal notes:

- What dependencies does making the search API available introduce? Do we need basic API auth?
- Likely use static API keys for a hand-picked set of API users for Quad 1

**Comment by widal001** [comment]
> Internal notes:
> 
> * What dependencies does making the search API available introduce? Do we need basic API auth?
> * Likely use static API keys for a hand-picked set of API users for Quad 1

Great callout! Maybe we can touch on this in the "Assumptions" section or in the "Technical description" section of the agile estimates?

**Comment by mxk0** [comment]
@widal001 we made #2244 to cover those questions, so I think we're good!

**Comment by mxk0** [comment]
@widal001 re: the new "Load testing" acceptance criteria, I don't think 10,000 concurrent users is the goal. To hit this deliverable we need 10,000 unique users for search, but that's cumulative rather than concurrent. We have a load testing spike (#2322) where we'll think through what peak concurrent usage could look like in order to get our 10,000 cumulative users. Can we cut the load testing criterion? We don't know what potential peak concurrent usage is yet, so I don't think it makes sense to set a number as an acceptance criterion.

Same comment goes for #2203. The 2,000 user goal is cumulative, not concurrent.

cc @mdragon

**Comment by margaretspring** [comment]
@widal001 - I'd like to get the Deliverable approval over to Julius. Can you clarify these item @mxk0 asked about re: the addition load item that wasn't in the HHS Priorities presentation. Thanks!

**Comment by mxk0** [comment]
For the record, I booked time for us to discuss the open questions tomorrow.

**Comment by mdragon** [comment]
## Sprint 1.3 updates

**Status:** 🟢 On track

### Sprint goal

The main goal for this deliverable in Sprint 1.3 was to launch the improvements to the search offering publicly, without requiring a feature flag

### Accomplishments

**Search launch**
- Search is fully public, removed the feature flag
- Implementation for sort by relevancy

**Generate traffic for search*
- Emails went out as requested to Simpler list and 5k portion of the grants.gov list 
- However, traffic is not meeting the level we were hoping for

### Rollover

### Risks

- Emails sent don't seem to be driving the level of traffic we expected
- Google Analytics data is suspect, looking to cross reference with email platform open/click rates.

### Sprint 1.4 goals

- Drive traffic to Search
- Address bugs/issues

**Comment by lucasmbrown-usds** [comment]
A couple questions: 

1. How's load testing coming along? 

2. How's API user recruitment coming along? 

3. Do we have an accuracy metric (i.e., Metric #3) in GA4 yet?

**Comment by mxk0** [comment]
@lucasmbrown-usds good questions!

1. Load testing is happening this sprint. Looking good so far.
2. Sorry, I messed up on where to post the API user update! We'll make sure that's here instead of #2204 next time.
3. Yes! We reviewed the tracking in #1892. Are you able to view [this GA link](https://analytics.google.com/analytics/web/#/analysis/p404968752/edit/LtxZZeUCTbmoXUUXvntx7w)?

**Comment by mxk0** [comment]
## Sprint 1.3 updates

**Status:** 🟢 On track

### Sprint goal

The main goal for this deliverable in Sprint 1.3 was to launch the improvements to the search offering publicly, without requiring a feature flag

### Accomplishments

**Search launch**
- Load testing complete, follow-up tickets created. We are confident we can handle the traffic from emailing the full Grants.gov listserv.

**Generate traffic for search**
- Email went out as requested to 50k portion of the grants.gov list 
- However, traffic is still not meeting the level we were hoping for

**Search API users**

- Reached out to more potential Search API users. 4 external parties have hit the Search API so far!


### Rollover

- N/A

### Risks

- MicroHealth may not be able to prioritize emailing more of the newsletter or publishing a banner on Grants.gov
 
### Sprint 1.5 goals

- Email remaining ~550k users on the Grants.gov newsletter listserv
- Put up a banner on Grants.gov to drive more traffic to Search
- Address bugs/issues

**Comment by mdragon** [comment]
Front End Page 200 vs 5xx Errors:
![Image](https://github.com/user-attachments/assets/32f249ff-364d-4885-97ce-f836831914d7)
42/617745 = 0.006% error rate < 5%

API 200 vs 5xx Errors:
![Image](https://github.com/user-attachments/assets/a27b26e0-37eb-4e6e-acf3-158459cf6897)
91/100298 = 0.09% error rate < 5%

**Comment by mxk0** [comment]
## DRAFT Sprint 1.5 updates:

**Status:** 🟢 On Track

### Sprint goal

The main goals for this deliverable in Sprint 1.5 were to drive more traffic to Search in service of our 10,000 user goal and get one more search API user.

### Accomplishments

**Generate traffic for search**
- Banner launched on Grants.gov
- Email to remaining ~550k users subscribed to the Grants.gov newsletter scheduled for [date]

**Search API users**

- One more developer hit the search API, getting us to our goal of 5 search API users.

### Rollover

- N/A

### Risks

- N/A
 
### Sprint 1.6 goals

- No active work planned. We expect current traffic numbers to get us to our 10,000 user goal within the next ~1-2 weeks.
