### ISSUE TITLE
[Bug]: Newsletter confirmation page message is incorrect

### ISSUE THREAD

**Issue by snyder-ux** [HHS/simpler-grants-gov#2205]
### Contact Details

jennifer.snder@focusconsulting.io

### What happened?

I signed up for Simpler.Grants.gov updates. The [confirmation page](https://simpler.grants.gov/newsletter/confirmation?sendy=User+subscribed+successfully.) is showing an incorrect message (see attached) by displaying `paragraph_1` and `Newsletter.pahragraph_2`.

### Steps to reproduce the behavior

1. Go to [Newsletter signup](https://simpler.grants.gov/newsletter) page
2. Subscribe
3. View confirmation page

### Priority

low (inconvenience)

### Screenshots and additional context

Copy/message should be updated to change "newsletter" in accordance with [#1560](https://github.com/HHS/simpler-grants-gov/issues/1560): [Content strings for the confirmation page](https://github.com/HHS/simpler-grants-gov/blob/89676fd0f8c97bd5a26513ff4ae2c3afbb84c026/frontend/src/i18n/messages/en/index.ts#L345-L357)

![Image](https://github.com/user-attachments/assets/d0d5d052-2e1b-4a02-a5f1-95dcaeb639e1)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by emilycnava** [comment]
Looking into this
