### ISSUE TITLE
Load testing for scale

### ISSUE THREAD

**Issue by widal001** [HHS/simpler-grants-gov#2224]
### Summary

The simpler.grants.gov platform has been load tested and can support up to 10,000 concurrent users.

**Comment by mxk0** [comment]
@widal001 can we move this into #2200 as an acceptance criteria, saying "Search has been load tested and can support up to 10,000 concurrent users."? Seems like that's the key thing here and it might be confusing to have a separate deliverable that doesn't explicitly call out Search. cc @margaretspring @mdragon

**Comment by mdragon** [comment]
And a similar call out on the Opportunities page Deliverable #2203 as well.

**Comment by widal001** [comment]
@mdragon @mxk0 Sorry I missed your earlier comment on this issue! If it makes more sense for y'all to track this as part of the other deliverables, we can definitely close this issue as "not planned" and incorporate it as AC in those other tickets.

Maybe we can just circle back on this when @lucasmbrown-usds gets back to confirm they're cool with accounting for the scaling effort that way?

**Comment by widal001** [comment]
Closing this ticket, after accounting for this work as part of the acceptance criteria for #2200 and #2203
