### ISSUE TITLE
Quad 1 user research

### ISSUE THREAD

**Issue by widal001** [HHS/simpler-grants-gov#2228]
### Summary

Members of the public and grantors can participate in user research sessions hosted during quad 1.

**Comment by margaretspring** [comment]
@andycochran Was comparing the high level deliverable issue to the Roadmap planning we agreed for Quad 1 [here](https://app.mural.co/t/agilesixapplications0942/m/agilesixapplications0942/1726451557143/f05c4d84df67426ddcab364fa460a1672ef04740?wid=0-1726457421068&sender=u1fa7045a23154cd2bb149624).   

Do you think we want this as a separate deliverable for Quad 1 (maybe bc relative to future work not in quad 1? OR remove it as a separate Deliverable in Github bc the user research work should live under larger deliverables (E.g Search, Creation flow).

**Comment by andycochran** [comment]
I think user research should be part of the larger deliverable like "Search v1"

**Comment by mxk0** [comment]
We also already call out user research as an acceptance criteria in #2204

**Comment by mxk0** [comment]
Closing this since it's already accounted for under #2204.
