### ISSUE TITLE
[Task]: Figure out a workaround for data that can't be loaded across the Oracle Foreign Data Wrapper

### ISSUE THREAD

**Issue by chouinar** [HHS/simpler-grants-gov#2252]
### Summary

We're encountering an issue when loading TSYNOPSIS_HIST in dev:

```sh
psycopg.errors.DatetimeFieldOverflow: timestamp out of range: "8386-01-01 00:00:00 BC"
CONTEXT:  converting column "posting_date" for foreign table scan of "tsynopsis_hist", row 13697
```

In short, the Oracle DB has some records where the post date is set to 8386 BC, while Postgres only supports timestamps going back to 4713 BC. Because the data wrapper itself does basic conversions of types, it fails to read the record. We need to figure out how we want to approach working around this issue.

A few ideas:
* Manually copy the record over while fixing the date - this would mean the copy process wouldn't think it is new and would ignore it.
  * Technically works, but doesn't help us in the event of future issues. As we've only encountered this in a few cases in the test data, this might be fine?
* Don't use timestamps for timestamp columns and instead convert (and error handle) in the transform logic.
  * This is a lot of rework of transformation logic 
* Setup a way to skip specific records
  * The way we setup the copy command is really generic, would need to refactor a bit to make this happen

### Acceptance criteria

- [ ] Get the table TSYNOPSIS_HIST table loaded

**Comment by coilysiren** [comment]
@chouinar maybe we can ask them to change the dates on the records? as another option

**Comment by chouinar** [comment]
I believe we had asked about that before the stoppage and got some pushback - suggesting we instead do option 2 above (define columns as text, handle it in the transforms). Even if we wanted to go with that approach, the turnaround time might be a while, I'm not sure who we'd even ask on MicroHealth's side now?

I'm personally leaning towards option 1 - while it isn't terribly scalable, I think the issue here is mostly down to bad test data. I don't think we hit the problem in prod at all when James ran it, and the other 17 tables had no issues.

**Comment by chouinar** [comment]
Actually found a way to query an Oracle metadata table to get the minimum date in every table to see if we'd encounter this again.

Can run something like:
```sql
SELECT
    table_name,
    column_name,
    dbms_stats.convert_raw_to_date(low_value) AS min_date
FROM
    sys.all_tab_cols
WHERE
        owner = 'EGRANTSADMIN'
    AND data_type = 'DATE'
ORDER BY
    min_date ASC   
```

This column is the only one that is too early. Here's everything that is earlier than 2000:
```
TSYNOPSIS_HIST	POSTING_DATE	8386-01-01 00:00:00 BC
TSYNOPSIS_HIST	ARCHIVE_DATE	1580-01-01 00:00:00 BC
TSYNOPSIS	POSTING_DATE	0002-03-09 00:00:00 AD
TCOMPETITION	OPENINGDATE	0002-08-20 00:00:00 AD
TSYNOPSIS_HIST	RESPONSE_DATE	0200-09-05 00:00:00 AD
TFORECAST	EST_APPL_RESPONSE_DATE	0206-04-01 00:00:00 AD
TCOMPETITION	CLOSINGDATE	0210-08-14 00:00:00 AD
TCFDA_IMPORT_TEMP	PUBLISHED_DATE	1922-01-01 00:00:00 AD
```

**Comment by chouinar** [comment]
So, following up that, I'm going to insert the 3 records manually myself into our dev staging table so that they don't get picked up.

Fetching the values from Oracle:
```sql
ALTER SESSION SET NLS_DATE_FORMAT = 'YYYY-MM-DD HH24:MI:SS BC';
select * from egrantsadmin.tsynopsis_hist where posting_date < to_date('01-01-0001', 'dd-MM-yyyy')
```

This affects opportunity IDs `63782`, `63780` and `63783`. These three records are identical except for the opportunity they are connected to, so I'll just craft an insert statement, and adjust the post date to something after 4713 BC.

---
Another thing I want to check before running this in test is whether we hit any issue when doing the transformations in python. I'm not sure BC dates are supported in python dates?

**Comment by chouinar** [comment]
Hmm, seems like Python / psycopg (the Python Postgres library), can't handle dates before year 1. I adjusted an opportunity post date in the DB, and just tried to fetch it via the GET endpoint and got this error:
```
sqlalchemy.exc.DataError: (psycopg.DataError) date too small (before year 1): '2000-01-01 BC'
```

So, rather than setting these dates to some other BC date, I need to make sure they're at least after year 1. There isn't any situation I can imagine us wanting a BC date in our system anyways, and prod never does BC dates, so that shouldn't be a major issue.

While there is an additional column that has this issue in the `archive_date` of the same `tsynopsis_hist` table, it is the exact same 3 records, so nothing too difficult to work around.

**Comment by chouinar** [comment]
I was able to manually insert those 3 records, and then successfully run the extract-load job with it ignoring those as it thought it already copied them. Looks like we're good to go.
