### ISSUE TITLE
Design a near-term solution for "Learn more"/"Apply now"

### ISSUE THREAD

**Issue by mxk0** [HHS/simpler-grants-gov#2272]
### Summary

When a user lands on an opportunity listing, there isn't currently a path forward. We need a clear call-to-action showing the user what they can do from the page. We won't know whether the user is eligible to apply or not, so we should use a general CTA like "Learn more". We may want to mention the word "apply".

### Acceptance criteria

- [ ] There is a link from each Simpler opportunity listing to the opportunity listing on Grants.gov

**Comment by snyder-ux** [comment]
[Figma](https://www.figma.com/design/FGxWtAgToKhehLJCiuy1zL/Simpler.Grants.gov-Project?node-id=224-1587&t=1wyP8mCS2Gt0iHLq-1)
- add a button with icon and label: Apply on Grants.gov
- add instructional text: Simpler.Grants.gov is a work in progress. Thank you for your patience as we build this new website.

**Comment by snyder-ux** [comment]
Updated text to: aThis site is a work in progress. Go to [www.grants.gov](http://www.grants.gov/) to apply, subscribe for updates, and track application status.

**Comment by snyder-ux** [comment]
**Updated copy based on feedback from Lucas to:** This site is a work in progress. Go to [www.grants.gov](http://www.grants.gov/) to apply, subscribe for updates, and track application status.

**Comment by snyder-ux** [comment]
Added heading "How to Apply" based on Emily's feedback.
We will need a different heading after it's closed, to go with that copy edit and state: [comment thread in Figma: ](https://www.figma.com/design/FGxWtAgToKhehLJCiuy1zL?node-id=239-2733#987460527).
