### ISSUE TITLE
Implement NOFO download in the UI

### ISSUE THREAD

**Issue by mxk0** [HHS/simpler-grants-gov#2275]
### Summary

Implements the design from https://github.com/HHS/simpler-grants-gov/issues/2339.

The new section is at the top of the left column.

**Heading:** Funding opportunity
**Button:** Download Full Announcement (NOFO)
- downloads the (previously known as) NOFO document
**Link:** Jump to all documents
- takes user to the document section

![Image](https://github.com/user-attachments/assets/4a4fe295-490e-4151-b86e-963d66e3969a)

Figma Link: https://www.figma.com/design/FGxWtAgToKhehLJCiuy1zL/Simpler.Grants.gov-Project?node-id=1-10&m=dev

### Acceptance criteria

- [ ] If there's a NOFO document in our infra for a particular opportunity listing, user can easily find and download the document

**Comment by doug-s-nava** [comment]
The current opportunity listing page does not have a document section. Do we need to build that out before doing this card, or do we want to move the addition of the "jump" link to a document section card?

**Comment by emilycnava** [comment]
Plan on picking this up :)

**Comment by doug-s-nava** [comment]
Depends on:
* https://github.com/HHS/simpler-grants-gov/issues/2637
* https://github.com/HHS/simpler-grants-gov/issues/2636

**Comment by crystabelrangel** [comment]
@emilycnava I updated the with the latest screenshot and link to the mockup for reference
