### ISSUE TITLE
Setup Infrastructure for storing/serving NOFOs

### ISSUE THREAD

**Issue by mdragon** [HHS/simpler-grants-gov#2278]
### Summary

Need to have infra in place for storing NOFO artifacts.
S3 Bucket(s) for Published and Draft documents

ADR happening in #2277.

**Comment by mdragon** [comment]
@coilysiren we should come to an agreement on the S3 buckets. 

- For initial hand-setup files I used the api general purpose bucket the platform has created for us in Dev.
- I think your research landed on separate DRAFT vs Published buckets.
- Do we want to use the general purpose bucket for one of those two?
- Do we want to create buckets explicitly for this usage (one likely needs to be public the other definitely not)?

**Comment by coilysiren** [comment]
@mdragon two total buckets, and we should just make sure the private bucket (eg. The general purpose one) is consistent about its paths

**Comment by mdragon** [comment]
@coilysiren thank you. And should we continue the naming convention of like api-<env>-documents-draft kinda thing?

**Comment by coilysiren** [comment]
@mdragon yep!
