### ISSUE TITLE
Identify and engage API users for search

### ISSUE THREAD

**Issue by mxk0** [HHS/simpler-grants-gov#2311]
### Summary

We need at least 5 unique API users to make at least one prod API request to meet our Quad 1 deliverable.

> ...at least 5 unique users have used the search directly from the API endpoint (i.e., not via the UI)

How many potential API users do we need to reach out to in order to ensure we hit our goal of 5? We have some leads already: USDR and people who reached out to our contact-us address.

### Acceptance criteria

- [x] Outreach plan written
- [ ] Potential users engaged

**Comment by mxk0** [comment]
Brandon and Raine (who is in the process of creating a GitHub account) to pair on this.

**Comment by mxk0** [comment]
@btabaska @rainedalton making sure this is on your radar for this sprint. Let me know if you have any questions about the scope, happy to get together on it.

**Comment by btabaska** [comment]
Yep! On my radar, I'll put time next week for us to discuss. Was giving @rainedalton a week to get up to speed on the effort before engaging her directly on this.

**Comment by btabaska** [comment]
We have reached out to 10 users for the API. We have gotten responses from 3 users.

**Comment by btabaska** [comment]
We have reached out to 20 users, we have gotten 10 "Yes" and have seen 3 users utilize the API so far. Closing as done.
