### ISSUE TITLE
Run ELT process and load data in staging environment

### ISSUE THREAD

**Issue by chouinar** [HHS/simpler-grants-gov#2323]
### Summary

This is a precursor to enabling automation.

We want to make sure the full ELT process works successfully, and any issues are worked through and corrected.

### Acceptance criteria

- [ ] ELT process successfully loads data fetchable via the API
- [ ] ELT process successful a second time (wait a day and handle updates/deletes)

**Comment by chouinar** [comment]
Running this yesterday, I did a diff between the legacy test data, and our data - looking at just the opportunity status.

For posted/forecasted/closed statuses, these were the only differences I could find (comparing ~2k records):
```
294059: forecasted != archived | GDIT
297940: forecasted != archived | IVV-IVVSUB1
286317: forecasted != archived | GDIT
59610: forecasted != archived | GDIT
62702: forecasted != archived | GDIT
291160: forecasted != closed | GDIT
294848: forecasted != closed | GDIT
291157: forecasted != posted | GDIT
62199: forecasted != archived | GDIT
284022: forecasted != archived | GDIT
59951: forecasted != archived | GDIT
283310: forecasted != archived | GDIT
282873: forecasted != archived | GDIT
283363: forecasted != archived | GDIT
283277: forecasted != archived | GDIT
283299: forecasted != archived | GDIT
283316: forecasted != archived | GDIT
69903: forecasted != archived | GDIT
```
The legacy system has a scenario where if an opportunity has both a forecast and synopsis record, and the forecast is "forecasted", it actually prefers the forecast (most of the time this isn't relevant as normally when a synopsis gets "posted" the forecast gets archived). This is a scenario that the legacy system intentionally supports for a very very specific case where they want to reuse an opportunity posting each year. From brief discussions with some stakeholders, this might not be something we need to support, but I'm not sure if any decision has been made officially. It goes against what makes sense and would be simple (forecast precedes posted, and doesn't ever go back to forecasted).

@mxk0 - The above scenario is something we should add to whatever list of technical/policy questions we have for stakeholders. Happy to go through it in more depth with you to help explain it - the current system's approach is really technical and complex in the way it works in the data for a very specific edge case.

**Comment by mxk0** [comment]
Added to our list to discuss with HHS (#2433).
