### ISSUE TITLE
Determine what we should do with empty assistance listings

### ISSUE THREAD

**Issue by chouinar** [HHS/simpler-grants-gov#2325]
### Summary

Opportunities have assistance listings which consist of a program title + assistance listing number. An opportunity can have several of these assistance listings.

The legacy data has tens of thousands of these records (~15% of all records) where both values are blank. There doesn't appear to be any purpose to these values. They filter it out on their frontend.

Should we just skip importing these records entirely?

### Acceptance criteria

- [ ] Figure out whether we should keep these
- [ ] If we decide to filter them out, implement that in the transformation logic

**Comment by mxk0** [comment]
@margaretspring to intro @mdragon and @mxk0 to HHS stakeholder for product discovery.

**Comment by chouinar** [comment]
Adding an example:

Here is what data we have for an assistance listing coming out of our API at the moment when we hit this case:
![Image](https://github.com/user-attachments/assets/86df7893-2df1-4365-a9d9-42f828fadeb1)

Here is how the existing grants.gov website renders that data:
![Image](https://github.com/user-attachments/assets/cd8aa9dc-0fac-44be-afd6-790cd52946ba)

I need to check their APIs, but as far as I can tell from the logic, the API would return these empty assistance listings as well, and their front-end just doesn't display them.

**Comment by chouinar** [comment]
In an unrelated discussion, I found at least some clue to why these blank assistance listings exist. The assistance listings are used to link an opportunity to the `TCOMPETITION` table and then to various application package tables (all of which we don't consume yet).

In some cases, its linked through these null assistance listings (and the code even references `nullCFDA` as a concept a few times. Why exactly it is needed, I'm not sure, but it looks like they do serve some other purpose.

You can see this a bit on the API.

This opportunity gets to its package via an ordinary assistance listing number
https://grants.gov/search-results-detail/355417
![Image](https://github.com/user-attachments/assets/721c8d80-242c-49cb-aa27-da96d6826f85)
 
This opportunity gets to its package via the weird null one
https://grants.gov/search-results-detail/356641
![Image](https://github.com/user-attachments/assets/cd06bc01-4324-4018-8df5-bab97c08dd55)

I think the question now is - why?

**Comment by chouinar** [comment]
From chatting with Narmada, confirmed it has to do with linking to the packages/competitions.

I'm going to take a little time to look into that connection a bit more to see if we can trim those out for now

**Comment by chouinar** [comment]
So here's how the current system works.

An opportunity has opportunity_cfda (assistance listing) records. A competition points to one of these opportunity_cfda records in order to connect it to the opportunity, so effectively.

Opportunity -> opportunity_cfda -> competition

Is necessary in order to connect these together. Because sometimes a competition _doesn't really need to be connected to a CFDA_ (when that happens, no idea), they have to create these "empty" opportunity_cfda records.

Here is my idea:

* Opportunity has a list of opportunity_cfdas (assistance listings / no change to this relationship)
* A competition knows its Opportunity AND assistance listing (which is nullable)

We no longer use the opportunity_cfda as a weird one-to-many table to the competition table, but instead just have a one-to-many relationship directly from opportunity to competition where they each uniquely have an assistance listing (TODO - would having multiple blank assistance listing values be an issue?)

As far as transforming this data, we just need to check if the current opportunity_cfda was a null one and if so, set the assistance listing foreign key to null.

This would mean we could just delete all of these weird empty assistance listings and not pull them in at all.

**Comment by chouinar** [comment]
TODO - make some follow-up tickets for this
