### ISSUE TITLE
Application considerations for Load Testing

### ISSUE THREAD

**Issue by mdragon** [HHS/simpler-grants-gov#2330]
### Summary

* frontend
  * do we need to update the search page to work with the CDN? (answer: we can't without making larger changes)
  * do we want to statically render the opportunity listing pages? (answer: yes, after we remove the feature flag)
*  API
   * if we statically render the opportunity listing pages, do we need a new API to get all pages? (answer: no)

### Acceptance criteria

- [x] A plan for what frontend changes are needed to facilitate load testing
- [ ] Epics/Tasks for implementing those changes and running the load tests

**Comment by acouch** [comment]
## Notes

* The site is currently entirely static except for the presence of the feature flag
* With Next we can generate the pages as "Static", "SSG", or "Dynamic"
  * SSG caches the pages for a current default of 8 hours. SSG is ideal as it provides a cached HTML response with the ability to regenerate and the correct headers for a CDN
  * Current all of the site pages are SSG except for opportunity pages
  * Currently the search page is SSG, however the cache-control headers are not set

### Answers

> do we need to update the search page to work with the CDN?

Currently the search page is SSG but does not have proper cache control headers for a CDN AFAICT (need to confirm).

> do we want to statically render the opportunity listing pages?

We should at least test this to see what it does to the build time.

> if we statically render the opportunity listing pages, do we need a new API to get all pages?

Let's test the above.

### Potential to-dos:

* determine proper cache lifetime for pages (currently ~8 hours)
* SSG opportunity pages so that they are not dynamically rendered
  * This requires getting all of the opportunity IDs. We can page through the search api but we might want an easier way to get this
* Ensure 404s have the correct cache control headers and try and cache them for a period after they are rendered

**Comment by doug-s-nava** [comment]
> if we statically render the opportunity listing pages, do we need a new API to get all pages?

`generateStaticParams` can be used to statically build a set of dynamic pages based on a url param. This seems like the sort of thing we'd want to use if, for example, we wanted to build a cache of opportunity pages at build time. https://nextjs.org/docs/app/api-reference/functions/generate-static-params

**Comment by acouch** [comment]
Some notes:

* Cloudfront can act as a reverse proxy for the static site. It is standard to use the origin (ie frontend) headers to [manage the cache lifetimes](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/Expiration.html#ExpirationDownloadDist)
* 90% of the site traffic will likely be anonymous (we could verify this with grants.gov traffic), so would want to not use server resources to generate content that is the same for everyone and changes infrequently
* We will soon start to add interactive features that will enable users to sign up and do things interactively on the opportunity and other pages
* We will want to be careful to maintain the cache for the general public and bots while providing profile-based interactivity
  * One way of achieving that could be to invalidate the CDN if the user [has a cookie indicating they are logged in](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/Cookies.html)
* We may be limited to not use RSC components that stream updates through suspense boundaries for content we would like to cache. That will probably be fine as most of that will be for logged in users, but something to keep in mind, and something we are doing on the search page

Here is a list of the page types and their current status in regards to the SSG rendering and cache headers:

| Page Type | Current Exports Correct Headers for CDN | Steps to take |
|---|----|---|
| static pages (home, process, research etc) | 🟢 | N/A |
| search page | 🔴 | Next won't set the proper headers for CDN/Reverse proxy for any pages that use query params. We are also getting streamed updates from the server. We would need to re-architect to not fetch data from the server which is not ideal. |
| opportunity pages | 🔴 | Opp pages will cache after the first response if we add an empty `generateStaticParams()` to the page file and remove the feature flag |
| 404s | 🔴 | [Next does not support caching of 404s](https://github.com/vercel/next.js/discussions/63239) but we can add [short cache lifetimes in cloudfront](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/HTTPStatusCodes.html) so we aren't DDOSed through 404s|
| subscribe | 🟢 | Make sure we don't change this with server actions |


I'd propose we start by not caching the search page and see how bad the performance is when we run a load test. If it seems problematic we could fetch the results from the client and cache it or try another mechanism.

When we are ready to setup a CDN and move forward, some tasks are:

* Setup the CDN to use the cache headers coming from the app
* Decide on and implement a cache lifetime (10mins? 30 mins?)
*

**Comment by acouch** [comment]
I'm still doing some research on how to use a reverse proxy or CDN with RSC and suspense streams: https://nextjs-forum.com/post/1291843906706866178 . However putting this down for now.

For next steps:

> Epics/Tasks for implementing those changes and running the load tests

@mdragon Think this would fall under the larger CDN effort. I could create some tickets to set the cache lifetime, but most of of the work is outside the app. What would you like for next steps?

**Comment by acouch** [comment]
Closing this an epic with tickets has been created https://github.com/HHS/simpler-grants-gov/issues/2535
