### ISSUE TITLE
Design UI/UX for downloading NOFOs on the Opportunity Listing view

### ISSUE THREAD

**Issue by andycochran** [HHS/simpler-grants-gov#2339]
### Summary

We're building a prototype to allow the download of ~7 NOFOs, and we want to highlight these NOFOs for download in the UI so that applicants can find them quickly. This design should show up on the 7 opportunities where the NOFOs are available. When we add NOFOs for all opportunities, this design will show up for all opportunities.

We should determine what the call to action is and how we refer to the NOFO (assuming we want a friendlier term than "NOFO").

Work with @chouinar to determine what data will be available and how we can format it in the UI. 

### Acceptance criteria

- [ ] A Figma mockup is ready for FE to implement

**Comment by mxk0** [comment]
@crystabelrangel just wanted to call out that I cleaned up the issue description to [hopefully] make it more clear. Let me know if you have any questions!

**Comment by chouinar** [comment]
We want to get rid of the existing folder approach as it just nests things awkwardly, that would give us a response like:

```json
{
   "opportunity_id": 12345,
   "summary": {},
   
   "related_documents": [
   {
      "file_location": "https://...",
      "file_name": "my_NOFO.pdf",
      "mime_type": "application/pdf",
      "file_description": "The full announcement NOFO",
      "file_size_bytes": "10012",
      "created_at": "2024-01-01 12:00:00",
      "updated_at": "2024-01-01 12:00:00",
      "document_type": "nofo"
    }
  ]
}
```

If we went with an approach where we kept all of the same data, the response would look something like:

```json
{
   "opportunity_id": 12345,
   "summary": {},
   
   "related_documents": {
      "folders": [
         {
             "folder_name":"Something here",
             "zip_location": "https://...",
             "folder_type": "full_announcement", # legacy has full_announcement, revised_full_announcment, and other_supporting_documents
             "folder_name": "The full announcement folder",
             "folder_size_bytes":"10121",
             "created_at": "2024-01-01 12:00:00",
             "updated_at": "2024-01-01 12:00:00",
             "attachments": [
               {
                    "file_location": "https://...",
                    "file_name": "my_NOFO.pdf",
                    "mime_type": "application/pdf",
                    "file_description": "The full announcement NOFO",
                    "file_size_bytes": "10012",
                    "created_at": "2024-01-01 12:00:00",
                    "updated_at": "2024-01-01 12:00:00",
               }
             ]
         }
      ]
   }
}
```

**Comment by mxk0** [comment]
For the record, I added Michael's comment above to a list of topics to review with HHS soon (#2433)

**Comment by crystabelrangel** [comment]
Added a Funding Details section below the Description. Heading and text is still a work in progress.

Figma mockup in devmode w/comments
https://www.figma.com/design/FGxWtAgToKhehLJCiuy1zL/Simpler.Grants.gov-Project?node-id=239-2733&m=dev
