### ISSUE TITLE
[Bug]: legacy newsletter footer link is broken

### ISSUE THREAD

**Issue by doug-s-nava** [HHS/simpler-grants-gov#2343]
### Contact Details

dougschrashun@navapbc.com

### What happened?

Existing grants newsletter url seems to be out of date and 404s.

* see https://www.grants.gov/web/grants/connect/newsletter-archive.html
* https://github.com/HHS/simpler-grants-gov/blob/0c76e547bcb3f224333e2cccb1e9d9a0ae08dd5d/frontend/src/constants/routes.ts#L16

### Steps to reproduce the behavior

1. click mail (envelope) link in footer
2. _VERIFY_: page that loads is a 404

### Priority

low (inconvenience)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by emilycnava** [comment]
Verified issue, picking this one up, found new URL: https://grants.gov/connect/manage-subscriptions/newsletter-archive
