### ISSUE TITLE
Updating Research Plan

### ISSUE THREAD

**Issue by crystabelrangel** [HHS/simpler-grants-gov#2352]
The Research plan has been updated with the below changes:

- Include the Deliverables #2200 and #2203 
- Research objectives are updated to reflect the new deliverables
- Research Hypotheses have been added to test predictions about the study referencing past research
- Research Questions have been added and linked to the Hypotheses
- Updated Study timeline
- Sections C and D on the discussion guide have been updated for users to perform a search on current grants.gov site, evaluate the new Search UI, and provide input on Opportunity Listing pages

**Comment by crystabelrangel** [comment]
@andycochran the updated Research Plan is ready for your review.
https://docs.google.com/document/d/1KT-3czVmjPV4gyrUoYcGn77BM25ImEwq6V6DMmj92dk/edit?usp=sharing

**Comment by andycochran** [comment]
@crystabelrangel This looks great to me. Please work with @itsemilyianacone to review/approve (probably async, since we've look at this before).
