### ISSUE TITLE
Opportunity listing usage analytics

### ISSUE THREAD

**Issue by mxk0** [HHS/simpler-grants-gov#2378]
### Summary

Ensure we can report on:

> UI adoption: At least 2,000 unique users have viewed the opportunity listing via the user interface (UI).

### Acceptance criteria

- [ ] Tracking in place to measure unique users that view the opportunity listing UI.

**Comment by doug-s-nava** [comment]
Does this work? https://analytics.google.com/analytics/web/#/analysis/p404968752/edit/4dEN3E3PSI2Y1yLYgPa8Nw

**Comment by mdragon** [comment]
Yeah, this should cover the needs of this ticket, @doug-s-nava.
