### ISSUE TITLE
Click tracking for "Learn more and apply"

### ISSUE THREAD

**Issue by mxk0** [HHS/simpler-grants-gov#2379]
### Summary

This is part of ensuring we have instrumentation that will allow us to measure conversion as defined in the Metrics section of #2203.

> Conversion: Set a baseline metric for percent of users who click “Learn more and apply” on the opportunity listing page.

This ticket is to review GA tracking to see if this is already in place. This should be time-boxed to a couple of hours and if there's anything resembling a rabbit hole we should avoid it and check in with @mdragon or @mxk0.

### Acceptance criteria

- [ ] GA tracking reviewed, report back on findings

### Acceptance criteria

- [ ] Tracking in place to show conversion rate from "gross opportunity listing page views" to "clicks on 'Apply' on the Simpler opportunity listing page"

**Comment by doug-s-nava** [comment]
This report should do it? https://analytics.google.com/analytics/web/#/analysis/p404968752/edit/1nTYCNpQSkyD-A2xR1jbQw cc @mxk0 @mdragon

**Comment by mxk0** [comment]
The click-through rate for the period Nov 25-Dec 2 was ~9% (383 clicks out of 3773 page views). GA4 doesn't offer a way to view this in a chart, so we'll need to move this tracking to New Relic in Quad 2.

![Image](https://github.com/user-attachments/assets/95187d5f-b698-4ce5-828a-cda419766df5)
![Image](https://github.com/user-attachments/assets/cd9e13b8-ef2a-4420-8627-1642e7b3db33)
