### ISSUE TITLE
Create chart showing frequency and length of database sync with Grants.gov

### ISSUE THREAD

**Issue by mxk0** [HHS/simpler-grants-gov#2380]
### Summary

This will allow us to meet part of our opportunity listing deliverable:

> Database syncing: Set a baseline metric for how quickly data is synced from Grants.gov to simpler.grants.gov; i.e., data is synced at least once every 24 hours.

### Acceptance criteria

- [x] Report for internal use showing frequency and speed of data sync from Grants.gov to simpler.grants.gov created

**Comment by mxk0** [comment]
We have the logging/charting. Need to update this ticket to be "report on stats to HHS stakeholders at the end of the quad.

**Comment by mdragon** [comment]
We don't have length of run in the document I added to the ticket, but we can attest that it doesn't run for a whole day (it runs in a few minutes at most). Should I try to capture this datapoint also?

**Comment by mxk0** [comment]
@mdragon if the data is easily available, yes please!

**Comment by chouinar** [comment]
@mdragon - I added duration to the dashboard on Cloudwatch (same log messages have that, just wasn't putting in the table).

![Image](https://github.com/user-attachments/assets/d2fb0203-94eb-46a3-8d34-e93ca4ba3a97)

**Comment by chouinar** [comment]
And if you want those in graph form, added those to the bottom.
![Image](https://github.com/user-attachments/assets/ac451a42-5bc1-49ef-a2e3-ddfddcc7f449)
