### ISSUE TITLE
[Task]: Back-end dependency vulnerability checks

### ISSUE THREAD

**Issue by daphnegold** [HHS/simpler-grants-gov#239]
### Summary

Configure the [Safety](https://pypi.org/project/safety/) tool (or optionally just Renovate for consistency with front-end). Requires getting a Safety-specific API key and configuring in Github Actions. 

### Acceptance criteria

- [ ] Get Safety API key & add to Github Secrets (need admin permissions)
- [ ] Install and configure Safety
- [ ] Add to Github Actions config

**Comment by daphnegold** [comment]
We have so many scans already: Hadolint, Trivy, Anchore, Dockle. I do not know if Renovate is running or requires some config, so maybe we can look into that to check. But adding another tool could be undesirable and just overkill at this point maybe?

**Comment by SammySteiner** [comment]
After reviewing safety, it seems like it's a paid tool so maybe not in line with the open source ideology of our project. Alternatively, we can set up renovate or dependabot to provide vulnerability checks for both backend and front end applications.

**Comment by SammySteiner** [comment]
Waiting for a meeting on 9/26 with Dom from HHS CIO's office to add Renovate to the repo's github integrations.

**Comment by acouch** [comment]
We have [added Renovate to the front end](https://github.com/HHS/grants-equity/blob/main/.github/renovate.json) but not for the backend.

**Comment by acouch** [comment]
Closing as the app code and containers are checked for vulnerabilities in GA and in the cloud with AWS ECR. Additionally renovate scans and posts PRs to remediate dependency issues.
