### ISSUE TITLE
Define list of Metabase users

### ISSUE THREAD

**Issue by mxk0** [HHS/simpler-grants-gov#2390]
### Summary

We need a list of who should have access to Metabase across Nava, A6, and HHS.

### Acceptance criteria

- [ ] List finalized and shared in this ticket.

**Comment by mdragon** [comment]
10 Licenses, for now allocated as follows.
A6:
- David (Dev and Prod)

Nava:
- Kai (Dev and Stage)
- Matt (Dev and Stage)

HHS:
- Lucas (Dev and Prod)
- Julius (Prod)
- Narmada (Prod)
