### ISSUE TITLE
Stand up Metabase

### ISSUE THREAD

**Issue by mxk0** [HHS/simpler-grants-gov#2391]
### Summary
Get Metabase up and ready for Users to work with the data and build dashboards

### Acceptance criteria

- [x] Deploy to all environments
- [x] Connect to Analytics Database
- [x] Get analytic data visible in Metabbase
- ~~Associate licenses with our install~~ Accounted for in #2938 
- [ ] Invite users

**Comment by coilysiren** [comment]
I've got metabase connecting to the analytics database in dev:

![Image](https://github.com/user-attachments/assets/3ef9ec44-af54-4c93-ac33-0cb74a550c6c)

Looks like its empty though, so we can't do anything with it yet

![Image](https://github.com/user-attachments/assets/5d2a6b91-d209-4b79-ad06-ec41e99c977d)

**Comment by mdragon** [comment]
Got Google SSO working in Dev using a Google Developer Client ID provided by Lucas.

**Comment by mdragon** [comment]
We have a license, so we're going to switch our containers over to use the Enterprise image and that will let us hook up our license token.
