### ISSUE TITLE
Site name in site title should link to index

### ISSUE THREAD

**Issue by andycochran** [HHS/simpler-grants-gov#2440]
### Summary

The `.usa-logo__text` in the `Header` component should link to the `/index` page. 

(See https://designsystem.digital.gov/components/header/ for implementation)

### Reproducibility

None

### How to reproduce the bug

Click the site name in the header. 

### Browser

Chrome

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by acouch** [comment]
Not sure if you were encouraging updating the markup to be the same in the linked (ie `.usa-logo__text`) but I tested that locally:

![Image](https://github.com/user-attachments/assets/d272a551-6869-436a-98ce-e0973baf546e)

vs what is there now:

![Image](https://github.com/user-attachments/assets/c9826f36-2a72-4fbb-91dc-b144a5ee1eb2)

**Comment by andycochran** [comment]
Didn't mean to imply anything but adding a link to the site name. The taller header does look nicer, but we can address any visual changes with the branding work.
