### ISSUE TITLE
Implementation for enabling users to sort by relevancy

### ISSUE THREAD

**Issue by mxk0** [HHS/simpler-grants-gov#2447]
### Summary

Implementation for the design from #2264.

### Acceptance criteria

- [ ] User can explicitly sort by relevancy, relevancy sort used when user enters search terms

**Comment by doug-s-nava** [comment]
Reqs from 10/21 meeting:

- Create "Default / Most Relevant" sort option in drop down
- This option will sort by post date descending (reverse chronological by post date) when no query term is present, and by relevancy when query term is present. (Note that no switch is necessary here as the secondary sort when relevancy is used is post date descending)
- Once a user selects a non-default sort, this will persist even if the user enters a new search term or refreshes
