### ISSUE TITLE
Evaluate updating of USDWDS to version 9.1+

### ISSUE THREAD

**Issue by mdragon** [HHS/simpler-grants-gov#2487]
Following up on #2096 which determined the issue was in the library we depend on.

Investigate what an update from 7 to 9.1+ would involve. If it appears to be easy/well supported and we can get a good sense of what would be affected we can just go ahead and make the leap. If it's more complicated spin up some tickets to cover this work

**Comment by doug-s-nava** [comment]
fun note that the fixes in trussworks v8 are courtesy of nava's own Joseph Anderson! https://github.com/trussworks/react-uswds/pull/2820

**Comment by doug-s-nava** [comment]
# Notes on possible breaking changes

Note that the latest version of Trussworks pins USWDS at ^3.7.1 so we should likely only upgrade USWDS as far as 3.7.1 (last version before 3.8.

## USWDS

* https://github.com/uswds/uswds/releases/tag/v3.9.0
    * various minor markup updates that could signal changes in our markup if we were manually including USWDS markup. Not relevant
    * change to Alert and SiteAlert
        * need to evaluate 
        * **Note for future work** we should try to use the SiteAlert component for the BetaAlert
* https://github.com/uswds/uswds/releases/tag/v3.8.0
    * change to side nav behavior that would mean recreating and toggling a mobile sidenav for responsiveness
        * does not look like we implement a side nav anywhere, so should be fine
 

## Trussworks
