### ISSUE TITLE
Update API schema to include both the agency name AND top-level agency name

### ISSUE THREAD

**Issue by chouinar** [HHS/simpler-grants-gov#2490]
### Summary

We already return the `agency_name` field in an opportunity, but want to add an additional string field called `top_agency_name`.

This field won't be populated yet as there is no corresponding field in the DB, we're just getting it available in the request for the frontend to be able to use it.

### Acceptance criteria

- [ ] API schema updated

**Comment by emilycnava** [comment]
Picking this up!
