### ISSUE TITLE
[10k]: Document sam.gov tasks

### ISSUE THREAD

**Issue by widal001** [HHS/simpler-grants-gov#254]
### Description

Document all tasks that need to be completed on sam.gov to enable functionality on grants.gov.

Document which of these tasks can be completed using APIs versus which must go through the sam.gov user interface.

### Sub-Tasks

- [ ] TODO

### Definition of Done

- [ ] TODO

**Comment by sarahknoppA6** [comment]
@sumiat @EOKENAVA this is a priority, could we possibly put it into the next sprint?
cc @lucasmbrown-usds

**Comment by sumiat** [comment]
commented in Slack: https://betagrantsgov.slack.com/archives/C05TGEN1J7N/p1702331858166489?thread_ts=1702308932.028769&cid=C05TGEN1J7N

**Comment by widal001** [comment]
Replacing our old 10k ft deliverable issues with a new Epic format

**Comment by widal001** [comment]
Reopening for review during sprint planning
