### ISSUE TITLE
Cleanup Fetcher Pattern

### ISSUE THREAD

**Issue by doug-s-nava** [HHS/simpler-grants-gov#2554]
### Summary

The current search fetch pattern was introduced over the course of two PRs:
* https://github.com/HHS/simpler-grants-gov/pull/1263
* https://github.com/HHS/simpler-grants-gov/pull/1386

Some functionality was created here to abstract away the actual classes that are being used to make the requests, with the benefit being the ability switching out real implementations for mocks when in testing scenarios based on an environment variable. However, it seems like this environment variable (`USE_SEARCH_MOCK_DATA`) is not in use anywhere, and mocking of API interactions is being done in other ways in various tests at the moment.

Since the functionality this abstraction offers is not being used, and there are arguably better alternatives in use, I propose removing the "fetcher" pattern present in the services directory and allow components that make requests to the API to directly access the relevant API classes. This should improve readability and maintainability of the code, and create a clearer pattern to use going forward as we add more API related functionality.

### Acceptance criteria

* All calls to search and opportunity endpoints function as expected
* Components making calls to the API use the BaseAPI extensions directly rather than "fetchers"
* Functionality present in the files at src/services/ other than the FeatureFlagManager and SearchFilterManager are either removed or moved into the BaseAPI or extensions

### Alternative

We opt to maintain the fetcher pattern and update our testing practices and API interactions to use it

**Comment by acouch** [comment]
Sounds great!

> Functionality present in the files at src/services/ other than the FeatureFlagManager and SearchFilterManager are either removed or moved into the BaseAPI or extensions

🔥 🔥 🔥
