### ISSUE TITLE
Send Comms for third largest rollout email

### ISSUE THREAD

**Issue by mxk0** [HHS/simpler-grants-gov#2586]
### Summary

This ticket is to make the request to Comms to send our third larger rollout email. The audience is 50,000 users, which we think will yield the 10,000 cumulative search users we need for quad 1. The email content is from #2399. **We will only send this email once we are comfortable with the results of the initial test rollout in #2401 and second larger rollout in #2402.**

### Acceptance criteria
- [x] Send Comms request for initial small rollout email
- [x] Get HHS & other approvals 
- [x] Email sent to third larger batch of users

**Comment by michellemin-nava** [comment]
[Draft - Google Docs](https://docs.google.com/document/d/1GvMiD7Pn97G9dJgn22l250SOwpvRw2f7/edit)

[Final - Sharepoint](https://bpsconsulting.sharepoint.com/:w:/r/projects/hhs-grantsgov/_layouts/15/Doc.aspx?sourcedoc=%7BD2E8B4D5-F065-4DAF-99DB-DF1CD0264628%7D&file=Simpler.Grants.gov%20Email%20Campaign%20-%20Search%20Announcement%203%20of%203.docx&action=default&mobileredirect=true)

[Sharepoint folder](https://bpsconsulting.sharepoint.com/projects/hhs-grantsgov/ITS%20Documents/Forms/AllItems.aspx?csf=1&web=1&e=JYB19z&CID=23b05d95%2D5be6%2D4ac7%2D9b21%2D680e8f76ef76&FolderCTID=0x01200075572C27B1F6414D9240B2C2E44CD78D&id=%2Fprojects%2Fhhs%2Dgrantsgov%2FITS%20Documents%2FT8%20Communications%20and%20Outreach%20Support%2FSimpler%2EGrants%2Egov%2FEmails&sortField=Modified&isAscending=true&viewid=975aa123%2D9df3%2D4148%2Dba3c%2D19212dda8e9a)
