### ISSUE TITLE
Review alerts and logs to ensure we are ready for the load tests

### ISSUE THREAD

**Issue by acouch** [HHS/simpler-grants-gov#2629]
### Summary

This should be a small task to ensure that the best possible linear regression function derived from AWS Cloudtrail via the load testing. There are already dashboards that cover this need 100%, we we need to study those graphs to determine the linear regressions for load.

### Acceptance criteria

- [ ] We use our cloudtrail dashboards to generate a linear regression for API / database load that looks [like this one](https://nava.slack.com/archives/C057K146W8H/p1731000835721639?thread_ts=1731000057.790689&cid=C057K146W8H). It would be expanding on this PR: https://github.com/HHS/simpler-grants-gov/pull/2720.

**Comment by coilysiren** [comment]
There's two places to look for consistently:

1. [the ECS service metrics dashboard](https://us-east-1.console.aws.amazon.com/ecs/v2/clusters/frontend-staging/services/frontend-staging/health?region=us-east-1)
2. Your emails, the `api-staging-high-app-response-time` alarm will fire

We don't have any logs for this purpose
