### ISSUE TITLE
Content design: post Search launch beta alert

### ISSUE THREAD

**Issue by andycochran** [HHS/simpler-grants-gov#2634]
### Summary

![Image](https://github.com/user-attachments/assets/3ce1b1dd-1da9-4b05-956d-8227b7be5325)

The beta alert currently says, "Go to www.grants.gov to search and apply for grants." However, once the Search feature flag is flipped this will make less sense, as you will be able to search without going to www. 

We should create new conditional content for this alert that clarifies what's possible on Simpler and improves this call-to-action. 

### Acceptance criteria

- [x] Improved beta alert message has been written
- [x] Content has been reviewed and approved by Product (@mxk0) 
- [ ] Content has been approved by client (@itsemilyianacone)
- [ ] Determine with Product and Emily whether additional approvals are necessary

**Comment by mxk0** [comment]
Thanks @michellemin-nava! I just updated #2635 with a note that this is ready for implementation.
