### ISSUE TITLE
Create "documents" section on opportunity detail

### ISSUE THREAD

**Issue by doug-s-nava** [HHS/simpler-grants-gov#2637]
### Summary

We need a place on the opportunity detail page to display associated documents

See designs here: https://www.figma.com/design/FGxWtAgToKhehLJCiuy1zL/Simpler.Grants.gov-Project?node-id=239-2733&node-type=frame&m=dev

Related tickets:

* https://github.com/HHS/simpler-grants-gov/issues/2275 depends on this change
* https://github.com/HHS/simpler-grants-gov/issues/2636 is a pre-requisite

### Acceptance criteria

A documents section is created that adheres to the designs from Figma and outcome of https://github.com/HHS/simpler-grants-gov/issues/2636

**Comment by emilycnava** [comment]
Picking this up too :)

**Comment by emilycnava** [comment]
We have added the day.js library to the FE as part of this ticket to manage dates/times going forward. Also added a tech debt ticket to backlog to refactor old date formatting to use the new library: https://github.com/HHS/simpler-grants-gov/issues/2736
