### ISSUE TITLE
Task: Create a login.gov sandbox app

### ISSUE THREAD

**Issue by emilycnava** [HHS/simpler-grants-gov#2644]
### Summary

Create a login.gov sandbox app. Will require access to login.gov sandbox team.

### Acceptance criteria

Sandbox app is created and usable

**Comment by chouinar** [comment]
I've created three apps, one for each of our environments which can be found at https://dashboard.int.identitysandbox.gov/service_providers once you login. 

I created a set of private/public keys that are necessary for private_key_jwt when fetching a token from login.gov and have verified it works with dev at least (connecting to it from my local machine). These keys will eventually be added to parameter store when we configure the env vars, but for now I stored them in our 1password vault:
<img width="358" alt="Image" src="https://github.com/user-attachments/assets/2ab63f27-2df9-48c5-8f4b-6b1ab7281ea2" />

A recent PR wrote up the [details on how to update these certificates](https://github.com/HHS/simpler-grants-gov/pull/3190/files#diff-fb2c4fc67269b004dff6972148a4867aa7fc3f288841ec86c0bea3cf04a83fa0) as well

Dev/staging should be fully setup, prod has a [follow-up ticket](https://github.com/HHS/simpler-grants-gov/issues/3192) as there is a whole process for requesting our app be setup, and we should do that after we further test the behavior in dev/staging.
