### ISSUE TITLE
Spike: Investigate login.gov user info returned from auth

### ISSUE THREAD

**Issue by emilycnava** [HHS/simpler-grants-gov#2646]
### Summary

Investigate the user info we get back from login and what we can display and what can be used as a UUID for each user for our authorization functionality wrapper that will wrap around login authentication

### Acceptance criteria

Usable data for user distinction and identification (i.e. UUID/email and name) have been identified.

**Comment by chouinar** [comment]
Duplicate of / done in: https://github.com/HHS/simpler-grants-gov/issues/2726
