### ISSUE TITLE
Task: Add login callback server action that receives simpler jwt and sets cookie for the frontend

### ISSUE THREAD

**Issue by emilycnava** [HHS/simpler-grants-gov#2654]
### Summary

Add login callback server action that receives simpler jwt and sets cookie for the frontend.

### Acceptance criteria

- [ ] Route created
- [ ] Session cookie set for frontend that allows for frontend session

**Comment by acouch** [comment]
Doing research on this. Start off [creating an oath0 account](https://github.com/auth0/nextjs-auth0/tree/main?tab=readme-ov-file#auth0-configuration) per the nextjs-auth0 docs. I've downloaded the sample app that is similar to this one and am walking through it: https://github.com/farayez/nextjs-base/tree/main

**Comment by acouch** [comment]
I've installed the nextjs-auth0 example and am reading through docs. I started https://docs.google.com/document/d/1oFKPbGjYK6Ku4b_0EjXygtVP-RMlHls5PnB71SSCdTg/edit?tab=t.0 to doc the workflow

**Comment by acouch** [comment]
I've updated the auth flow mural to better show the details of the various handoffs:

![Image](https://github.com/user-attachments/assets/76c1ff87-fde3-4f08-a38f-137e201c0ee0)

Will have some internal disc before proceeding.

**Comment by acouch** [comment]
Landed on ![Image](https://github.com/user-attachments/assets/c48862ca-ef7c-4732-b2c8-ce83aaef3adc)

Investigating https://next-auth.js.org to help handle validation and session management.

**Comment by acouch** [comment]
I've pushed a branch with a user provider scaffold.

**Comment by acouch** [comment]
I started a PR, and handed this off to @doug-s-nava
