### ISSUE TITLE
Setup local oauth2 server for API to connect to

### ISSUE THREAD

**Issue by chouinar** [HHS/simpler-grants-gov#2668]
### Summary

We want to setup a local oauth2 server to connect to for the purposes of local development. Non-locally we'll be connecting to login.gov, but for local development we want something running on your host.

One possible implementation is https://github.com/navikt/mock-oauth2-server which looks like we can add to our docker-compose file.

### Acceptance criteria

- [ ] Local oauth2 instance stood up
- [ ] Rudimentary testing / notes about how it works (things like how we create users)

**Comment by babebe** [comment]
@chouinar Since we can get the public key associated with the token via the` jwks_uri` is it still necessary for us to have a static key ?
