### ISSUE TITLE
ADR for shared calendar

### ISSUE THREAD

**Issue by widal001** [HHS/simpler-grants-gov#2680]
### Summary

Create or update the ADR for managing shared calendars and team availability.

### Options

- Shared calendar in Google (A6)
- Calendar integration in Slack

### Decision Criteria

- Enables users to check team members availability
- Displays recurring team meetings/ceremonies

### Approvers

- @lucasmbrown-usds 
- @margaretspring (and Nava team)

### Acceptance criteria

- [ ] The approvers for this decision have been identified (ideally before work on the ADR starts)
- [ ] The ADR is created and stored in `documentation/wiki/decisions/adr` with status "Accepted"
- [ ] The ADR has been reviewed and approved by the approvers listed above
- [ ] The ADR satisfies requirements that are outlined in the ADR template
- [ ] Any follow-up tickets have been created (if necessary)

**Comment by widal001** [comment]
We might want to connect with Lucas and Julius to define the purpose of this tool/ADR.

**Comment by sarahknoppA6** [comment]
I think this might be blocked right now. I do have a thought about unblocking- will discuss as we progress on the internal wiki ADR.
