### ISSUE TITLE
Add kill switch for Search and Opportunity data display

### ISSUE THREAD

**Issue by mdragon** [HHS/simpler-grants-gov#2695]
### Summary

In case we have an issue with bad data that rises to the level of a risk to the program we want to have a way to disable usage of the Search and Opportunity pages respectively to force people back to the existing site. 

Use content from #2735 

The Dev flags have been set up in AWS Systems Manager - Parameter Store:
/frontend/dev/feature-opportunity-off
/frontend/dev/feature-search-off

### Acceptance criteria

- [ ] With the Search flag set to True the Search page does not allow searching and does not display results
- [ ] With the Opportunity flag set to True the Opportunity page does not display data about the Opportunity
- [ ] When the flags are True a message is displayed directing the user to grants.gov until the issue can be resolved
- [ ] With the Search flag set to False the Search page behaves as normal
- [ ] With the Opportunity flag set to False the Opportunity page behaves as normal

**Comment by coilysiren** [comment]
Kill switch options:

- env var: no - would get reset on redeploy
- database value: maybe - this requires database access though, with is a little rare. also would add frontend latency on every request, but not backend latency
- ssm param at runtime: no - this would add latency to every request that we don't want
- ssm param at build time: yes - good option, would require a redeploy though

**Comment by doug-s-nava** [comment]
seems like we need some consensus on whether or not the AC for this:
* is ok with a redeploy to introduce a flag change (and read from SSM parameters)
* is ok with a code change to introduce a flag change (no change necessary)
* needs to be dynamic at runtime (should probably split out into multiple tickets and discuss approach)

**Comment by mdragon** [comment]
@doug-s-nava lets make this require a code change for now, but set it up where we have the message for "Sorry we're currently offline, please use grants.gov" or whatever (from @michellemin-nava) wired up in the code so that if we flip the variable the message is up and we can roll it out.
Let's make sure this is overridable via a query param for testing both directions, turning on the message for this development, but also bypassing the message in Prod to make sure Search or Opp bugs are fixed before we roll out the code change to turn those features back on.
