### ISSUE TITLE
Generate NewRelic beacons from the frontend

### ISSUE THREAD

**Issue by mdragon** [HHS/simpler-grants-gov#2696]
### Summary

Implement in our client code
https://docs.newrelic.com/docs/browser/new-relic-browser/browser-pro-features/browser-data-distributed-tracing/

### Acceptance criteria

- [ ] Frontend has the NewRelic library
- [ ] Frontend is sending browser data requests using NewRelic library

**Comment by coilysiren** [comment]
😍

**Comment by mxk0** [comment]
@coilysiren just a heads up from when you froze during sprint planning, one of the frontend folks is going to pick this up.
