### ISSUE TITLE
Display Opportunity Number

### ISSUE THREAD

**Issue by crystabelrangel** [HHS/simpler-grants-gov#2709]
### Summary

The opportunity number does not display on the opportunity listing page.
In the mockup, it is visible in:

- breadcrumbs
- under the Award boxes section

![Image](https://github.com/user-attachments/assets/b4a163ab-1c15-4f52-9386-c5818468ca8f)
![Image](https://github.com/user-attachments/assets/54f98707-6a0f-4b14-b523-0e63536fff50)

### Acceptance criteria

Opportunity number displays 

- [ ] breadcrumbs
- [x] under the Award boxes section - Done as part of ([2552](https://github.com/HHS/simpler-grants-gov/issues/2552))

**Comment by mdragon** [comment]
Confirmed that breadcrumbs are still needed, but [2552](https://github.com/HHS/simpler-grants-gov/issues/2552) fixes the Award boxes section
