### ISSUE TITLE
[10k]: User research for search

### ISSUE THREAD

**Issue by widal001** [HHS/simpler-grants-gov#271]
### Description

Conduct additional user research on search needs.

### Sub-Tasks

- [ ] TODO

### Definition of Done

- [ ] TODO

**Comment by acouch** [comment]
This wasn't scoped for the "Search UI 30K", moving to "Search 2.0" for now.

**Comment by widal001** [comment]
Replacing our old 10k ft deliverable issues with a new Epic format
