### ISSUE TITLE
Create user tables for basic login.gov auth

### ISSUE THREAD

**Issue by chouinar** [HHS/simpler-grants-gov#2716]
### Summary

We want to create three tables in our database:

`user`
* user_id : UUID
* created_at/updated_at timestamps (like every other table, just use the mixin)

`lk_external_user_type`
This follows our usual pattern for [lookup tables](https://github.com/HHS/simpler-grants-gov/blob/main/api/src/db/models/lookup_models.py)

The enum we create for this will only have a single value of `login_gov` at this time.

**link_external_user**
* link_external_user_id : UUID
* external_user_id: str
* user_id: UUID / foreign key to user table / indexed
* external_user_type_id: int / foreign key to the lk_external_user_type table
* email: str
* first_name: str
* last_name: str

Note that we have been using integers for a lot of our tables primary keys up to this point. However we want these to be UUIDs so they aren't just incrementally counting upward. If you make the python type `Mapped[uuid.UUID]` it should make the DB type correctly, but we'll need to validate that (it should also automatically populate the ID if none provided, we'll likely need to configure that).

### Acceptance criteria

- [x] Tables created
- [x] The two user related tables should be in a new models file
- [x] Migrations created
- [ ] Updated factories to be able to generate user with login.gov info

**Comment by babebe** [comment]
@chouinar  Do I have this right >>  The UUID for table `user` is what we generate ? which is the foreign key  `external_user_type_id` in table `link_external_user` and the UUID in that table is the UUID from login.gov ?

**Comment by chouinar** [comment]
@babebe 

The user table has no knowledge of anything to do with login.gov - it's a very generic table we'll add to later.

The link_external_user table is where we put info that will connect a user to an oauth service, in this case, just login.gov

The lk_external_user_type is just to store enums for different types of external users (in this case, just login.gov) in our DB
