### ISSUE TITLE
Quickly clicking multiple status filters does not toggle all of them

### ISSUE THREAD

**Issue by andycochran** [HHS/simpler-grants-gov#2728]
### Summary

When you very quickly click several status filters, not all of them are toggled. I am wondering if there’s a race condition or a debounce causing a problem here. If you click slowly, this is not an issue. 

Trying to recreate this also sometimes leads to an error. Once you get this error, the URL and UI fall out of sync (clicking statuses change the query params, but the checkboxes do not toggle): 

<img src="https://github.com/user-attachments/assets/f3261018-0d95-4bf4-bc29-869c6d175c3d" width="500" /> 

### Reproducibility

I tried multiple times and saw the bug intermittently

### How to reproduce the bug

From a fresh page load, quickly click all 4 status filters

### Browser

Chrome

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by acouch** [comment]
@andycochran can you take a video? I can't recreate this.

**Comment by andycochran** [comment]
https://www.loom.com/share/0ba7844114804ce990f14182d68bea95

**Comment by doug-s-nava** [comment]
dug in a little, and from what I can tell this is a matter of a "mousedown" or "keydown" not triggering the "change" event that is necessary to update the UI as it's currently written. Should be able to fix this by specifically binding to "mousedown", "keydown" and "touchstart"

**Comment by doug-s-nava** [comment]
After a bit more research, I'm not sure this is something we can solve at all easily. It's looking like an `onChange` handler is going to fire once the value of an input has changed, so firing anything prior to that will not reliably pick up the change in value unless we are actively changing the value ourselves more quickly. We could theoretically do that but it'd be potentially tricky.

FWIW Some vague research into behavior on other sites (ebay, zappos, etc.) shows similar issues.

**Comment by andycochran** [comment]
Okay, let's not address the too-quick clicking for now then. I don't think it's a huge bug. And there is clear UI feedback when an element does/doesn't toggle. If a user comes across this bug, that can simply toggle the element again, which should happen more slowly.

Do we have any ideas what might be causing the "We're sorry" error?

**Comment by andycochran** [comment]
Should we revisit our debounce method? I'm not sure how it's working exactly, but might be worth checking. 

cc @mxk0 are you okay with closing this as "won't fix" for now? We can always reopen.

**Comment by doug-s-nava** [comment]
Connected my local env to the PROD API briefly to try and reproduce the 500 and failed. Without deploying something out to dev with some extra debugging code I think this is going to be hard to track down at this point.

As far as debouncing goes, I don't see any code that is using a debounce at this point. The app still includes a `useDebounce` hook library, but it is unused as far as I can tell. @acouch can you give me a second pair of eyes on that state of affairs? Believe we can go ahead and pull out the debounce library and add it back if we want it later? https://github.com/HHS/simpler-grants-gov/pull/2936

**Comment by doug-s-nava** [comment]
As suggested by @andycochran and @mxk0 - closing as won't fix for now, but perhaps to be revisited later if this proves to be an enduring issue.
