### ISSUE TITLE
Content for scenario where we disable search or opportunity listings

### ISSUE THREAD

**Issue by mxk0** [HHS/simpler-grants-gov#2735]
### Summary

Draft a simple "maintenance mode" message to be used in our 404 page in this scenario.

### Acceptance criteria

- [ ] Content drafted and shared

**Comment by michellemin-nava** [comment]
@mxk0, the error message content is ready for review.

Title: Simpler.Grants.gov Is Currently Undergoing Maintenance
Body: Our team is working to improve the site, and we’ll have it back up as soon as possible. In the meantime, please visit www.Grants.gov to search for funding opportunities and manage your applications.

Thank you for your patience.

![Image](https://github.com/user-attachments/assets/bda60459-83a2-4ed9-9080-2f23d2b87614)

**Comment by mxk0** [comment]
Looks great. Thank you @michellemin-nava!
