### ISSUE TITLE
Gather participants to distribute API keys to

### ISSUE THREAD

**Issue by mxk0** [HHS/simpler-grants-gov#2743]
### Summary

5 people emailed contact-us asking for API keys. We want to email at least 15 people. 

Other potential avenues to API users:

- Lucas connections
- Reme connections

### Acceptance criteria

- [ ] Engage potential API users who emailed us requesting a key
- [ ] At least 10 other potential users identified and engaged

**Comment by btabaska** [comment]
20 people have been emailed, 10 "Yes" and 3 users have used the API. closing as the DoD has been fulfilled.
