### ISSUE TITLE
Draft email content for participants

### ISSUE THREAD

**Issue by btabaska** [HHS/simpler-grants-gov#2763]
### Summary

In order to share Search API keys with participants we will need a short campaign of email content to communicate with participants. This should include all emails that will be bulk sent to participants. We will need one to let the person know that they have been selected for testing, one to send the API key with a link to the documentation, and a final one to confirm use and request feedback. 

### Acceptance criteria

- [x] Introduction and invite email written up
- [x] API key and documentation email written up
- [x] Request feedback email written up

**Comment by rainedalton** [comment]
[Email draft ](https://docs.google.com/document/d/1yyQe-EIMHM42mxYKWP1TGxhdf77pnHVdLFDUa4c4LGo/edit?tab=t.0 )
