### ISSUE TITLE
[30k]: Opportunity listing (synopsis)

### ISSUE THREAD

**Issue by widal001** [HHS/simpler-grants-gov#277]
### Key links

- [Deliverable specification](https://simpler-grants.gitbook.io/wiki/product/deliverables/specifications/opportunity-listing-synopsis)
- [Simpler Grants.gov full roadmap](https://github.com/orgs/HHS/projects/12)
- [10k milestones](https://github.com/orgs/HHS/projects/13/views/11?sliceBy%5Bvalue%5D=Opportunity+listing+(synopsis))

### Description

- **What:** Create an initial opportunity listing page that allows applicants to view basic information about an opportunity on simpler.grants.gov.
- **Why:** Creates the foundation for future user testing and the open source hackathon related to the opportunity listing page.
- **Who:**
  - Existing grants.gov users
  - Open source contributors

> [!NOTE]
> For more information about this deliverable please refer to the deliverable specification linked above

**Comment by sumiat** [comment]
**Weekly Update 5/8**

**What has been done?**
- Opp listing deliverable spec drafted, reviewed internally by Nava, reviewed by Sarah and Billy
- Opp listing planning and tech spec drafting (Nava leads only) 
- Started the mockup design to account for any approval times we need and so the engineering work can happen  

**Status**
- Planning

**Risk**
- Initial mockup approvals - we assume just approvals from Emily/Julius/Lucas are needed. It may be a risk if there needs to exec leadership approval but we can still start on engineering. 

**Deliverable Date**
- TBD

**What will be done?**
- Determine delivery date for opp listing synopsis 
- Publish the first draft of the tech spec

**Comment by widal001** [comment]
Replacing our old deliverable tickets with a new ticket format
