### ISSUE TITLE
[SPIKE] Connect Metabase to Postgres

### ISSUE THREAD

**Issue by widal001** [HHS/simpler-grants-gov#2845]
### Summary

Research the steps required to connect Metabase to Postgres in staging or dev.

### Acceptance criteria

- [x] Users can query data from Postgres in Metabase (in staging or other hosted environment)
- [x] OR (if further work is required) additional tickets have been created

**Comment by widal001** [comment]
@coilysiren Thinks this _might_ already be configured -- we'll be able to test it more easily once we have data in Postgres.

**Comment by coilysiren** [comment]
![Image](https://github.com/user-attachments/assets/245d54b3-7d1e-48b7-9b0d-2e5d9b543c1e)

**Comment by widal001** [comment]
Metabase is connected to live data in dev
