### ISSUE TITLE
Run ETL process for GitHub data in staging environments

### ISSUE THREAD

**Issue by DavidDudas-Intuitial** [HHS/simpler-grants-gov#2857]
### Summary

Follow up to #2665 in which the db was initialized manually by running SQL statements in RDS query editor, which is not desirable for staging and prod environments. Instead, we would like our programmatic database migrations and our ETL to be able to run to completion in staging. This requires various privileges, permissions, configurations, etc.

### Acceptance criteria

- [x] Database migrations can execute automatically in staging environment
- [x] ETL process for GitHub data runs successfully in staging environments
- [x] GitHub data is available in the staging Metabase instance

**Comment by widal001** [comment]
Here's screenshots of the data showing up in the staging Metabase instance

![Image](https://github.com/user-attachments/assets/bb08d821-5cb4-495e-96bd-bd56ff5249ea)
![Image](https://github.com/user-attachments/assets/768fc227-90a4-4da7-92b8-240bba9e7e8a)
