### ISSUE TITLE
Email search usability testing participants to solicit feedback

### ISSUE THREAD

**Issue by mxk0** [HHS/simpler-grants-gov#2860]
### Summary

Once all of the usability testing sessions are complete, we should follow up with participants to solicit feedback, see if they would participate again, and ask if they would recommend anyone else for future studies.

We need to get this feedback to meet the Engagement Sessions metric:

> Satisfaction: At least 50% of the attendees/participants indicate interest in attending another session in the future or would refer/recommend to a friend, colleague, etc.

### Acceptance criteria

- [ ] All usability testing participants emailed

**Comment by mxk0** [comment]
@crystabelrangel getting this on your radar for Sprint 1.5! Let me or @andycochran know if you have any questions.

**Comment by crystabelrangel** [comment]
Initial email and form ready for review
https://docs.google.com/document/d/116pRYAa4hPVZSusKi6YV4WSpCvM6cACvnXzJ2mWloYQ/edit?tab=t.0#heading=h.kx4t5fkm2xb

**Comment by crystabelrangel** [comment]
All 16 participants have been emailed.
