### ISSUE TITLE
Draft a social blurb about Search

### ISSUE THREAD

**Issue by michellemin-nava** [HHS/simpler-grants-gov#2868]
### Summary

Draft up a blurb that team members & others can share out encouraging them to check out the new Search feature

### Acceptance criteria

- [x] Draft blurb
- [x] Solicit feedback
- [ ] Finalize: document and distribute to team members to use

**Comment by michellemin-nava** [comment]
[Copy doc](https://docs.google.com/document/d/1yDM2ffIqBMOwWSGlYHhAuYkLv-3L8_agvZ3xFkqZT4w/edit?tab=t.0)

**Comment by michellemin-nava** [comment]
Hi @mxk0! The social blurbs are ready for your review. [Copy doc](https://docs.google.com/document/d/1yDM2ffIqBMOwWSGlYHhAuYkLv-3L8_agvZ3xFkqZT4w/edit?tab=t.0)

Could you take a look and update the status tracker next to your name with "Approved" when ready? Thank you! 🙏

**Comment by mxk0** [comment]
@michellemin-nava done. Thank you!
