### ISSUE TITLE
Metabase vs Sprinty McBurndown discrepancy

### ISSUE THREAD

**Issue by widal001** [HHS/simpler-grants-gov#2927]
### Summary

When trying to calculate the percent of points or issues complete by deliverable, the Metabase dashboard matches Sprinty McBurndown for all deliverables except two:

- Search
- Delivery metrics

### Notes

I _think_ this has to do with how we're capturing the relationship between epics and deliverables in `gh_epic_deliverable_map` If an epic has _ever_ been associated with a deliverable and then is removed, we have no way of designating that that mapping is no longer valid.

It's possible there's a way of working around this with the query, but it might require some rework on the load. We should decide how this scenario is handled long term.

### Reproducibility

I tried multiple times and saw the bug every time

### How to reproduce the bug

1. Look at [the Metabase dashboard](http://metabase-dev-710651776.us-east-1.elb.amazonaws.com/dashboard/2-delivery-metrics)
2. Look at the [percent complete in Slack](https://betagrantsgov.slack.com/archives/C064Y8VNW14/p1731964063475949)

### Browser

Not applicable

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by DavidDudas-Intuitial** [comment]
@widal001 What are the expected values and actual values?

**Comment by DavidDudas-Intuitial** [comment]
>  If an epic has ever been associated with a deliverable and then is removed, we have no way of designating that that mapping is no longer valid

We do indeed have a way. In `gh_epic_deliverable_map`, the column `deliverable_id` is allowed to transition back and forth to `null`. 

For example, in my local dev instance:
```
app=# select * from gh_epic_deliverable_map where epic_id = 4;
 id  | epic_id | deliverable_id | d_effective |         t_created          |         t_modified
-----+---------+----------------+-------------+----------------------------+----------------------------
   4 |       4 |                | 2024-11-06  | 2024-11-20 06:23:27.413657 | 2024-11-20 06:23:27.413657
  28 |       4 |                | 2024-11-07  | 2024-11-20 06:23:32.976838 | 2024-11-20 06:23:32.976838
  52 |       4 |                | 2024-11-08  | 2024-11-20 06:23:39.270854 | 2024-11-20 06:23:39.270854
  72 |       4 |              1 | 2024-11-11  | 2024-11-20 06:24:01.831966 | 2024-11-20 06:24:01.831966
  77 |       4 |                | 2024-11-12  | 2024-11-20 06:24:13.677568 | 2024-11-20 06:24:13.677568
 101 |       4 |                | 2024-11-14  | 2024-11-20 06:24:46.040406 | 2024-11-20 06:24:46.040406
 128 |       4 |                | 2024-11-18  | 2024-11-20 06:25:01.819183 | 2024-11-20 06:25:01.819183
 153 |       4 |                | 2024-11-19  | 2024-11-20 06:25:08.34917  | 2024-11-20 06:25:08.34917
(8 rows)
```

**Comment by widal001** [comment]
As discussed in Slack the discrepancy related to search stemmed from how we were joining epics to deliverables through the `gh_epic_deliverable_map`. Because that table records a new mapping every day, regardless of whether or not the mapping changes, we can simply select the mapping where `d_effective = CURRENT_DATE - 1` to get the mapping from the previous days export.

After adjusting how we join join epics to deliverables using this new logic the discrepancy for Search disappears:

![Image](https://github.com/user-attachments/assets/358a1fd4-80cf-4ea4-81f0-73482506dd82)
![Image](https://github.com/user-attachments/assets/ee1ff4b1-14da-4702-88bb-76f223ae82dd)

**Comment by widal001** [comment]
Next steps for debugging the discrepancy for cross-program delivery metrics is to compare the data from [this view in Metabase](http://metabase-dev-710651776.us-east-1.elb.amazonaws.com/question/112-cross-program-delivery-metrics-issues) with the filtered version of [this export in Slack](https://betagrantsgov.slack.com/files/U0654R2D3NW/F081H8EQENR/source-data.csv) to identify which issues are missing from the Metabase view.

**Comment by DavidDudas-Intuitial** [comment]
PR https://github.com/HHS/simpler-grants-gov/pull/2992
