### ISSUE TITLE
Create opportunity tables in analytics db

### ISSUE THREAD

**Issue by mxk0** [HHS/simpler-grants-gov#2934]
### Summary

Create tables based on the decision made in #2933 

### Acceptance criteria

Tables:
- [ ] opportunity (3)
- [ ] opportunity_summary (4)
- [ ] current_opportunity_summary (5)
- [ ] lk_opportunity_status (1)
- [ ] lk_opportunity_category (2)

**Comment by mdragon** [comment]
@babebe I think these four should cover it, but if there's any additional tables you think we need or find would be helpful as you build these out, please let me know.

**Comment by mdragon** [comment]
@chouinar now that you're back, can you just double-check me on this list to make sure I didn't miss anything critical to this first pass?

**Comment by babebe** [comment]
@mdragon do we want agency names?

**Comment by mdragon** [comment]
@babebe lets go without Agency for this ticket and if we're making good progress we can consider doing agency in a separate ticket now or later when needed.
