### ISSUE TITLE
[Task]: Network DNS entry

### ISSUE THREAD

**Issue by sumiat** [HHS/simpler-grants-gov#295]
### Summary

Blocking #472 

This task is to fill out this form:  [DNS_Change_Request.pdf](https://github.com/HHS/grants-equity/files/12529419/DNS_Change_Request.pdf) and return it to HHS. 

- Set up DNS hosting service to manage DNS settings or identify who manages DNS for grants.gov
- Update DNS to point to domain 
- Configure any necessary subdomains 

### Acceptance criteria

- [ ] DNS settings are updated and the domain successfully resolves to correct address
- [ ] Website is accessible at beta.grants.gov
- [ ] Relevant documentation is provided for DNS configuration

**Comment by SammySteiner** [comment]
Blocked till we discuss with Terrance on Monday 8/28
