### ISSUE TITLE
Google Analytics "search_term" event is not sending proper data

### ISSUE THREAD

**Issue by doug-s-nava** [HHS/simpler-grants-gov#2969]
### Summary

When a user attempts a search we are trying to send a "search_term" event with a "key" event property set to the search term, but it is always coming through as an empty string.![Image](https://github.com/user-attachments/assets/f7635625-ea71-4f1e-82f4-ff53a2828c29)

### Reproducibility

I tried multiple times and saw the bug every time

### How to reproduce the bug

- Perform a search with a query on simpler.grants.gov
- In omnibug or another analytics plugin, verify that a "search_term" event was sent with event data set to ""

### Browser

Chrome

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by mxk0** [comment]
Marking as won't fix, search terms are working intermittently, but the real fix is moving away from GA4.
