### ISSUE TITLE
Design a branded Header component

### ISSUE THREAD

**Issue by andycochran** [HHS/simpler-grants-gov#2984]
### Summary

Apply the approved brand to the USWDS header component 

### Acceptance criteria

- [x] Senongo has approved the brand application 
- [x] Emily has approved the design
- [x] FE ticket has been updated per #2632

**Comment by crystabelrangel** [comment]
Header has been approved. The header/nav will be sticky.![Image](https://github.com/user-attachments/assets/58564778-706f-4431-abc0-023a4638154b)
