### ISSUE TITLE
Design a branded Footer and Identifier

### ISSUE THREAD

**Issue by andycochran** [HHS/simpler-grants-gov#2985]
### Summary

Apply the approved brand to the USWDS [Footer](https://designsystem.digital.gov/components/footer/) and [Identifier](https://designsystem.digital.gov/components/identifier/) components. These two components should be considered together, as they comprise what the user experiences as the site footer. 

### Acceptance criteria

- [x] Senongo has approved the brand application 
- [x] Emily has approved the design
- [x] FE ticket has been updated per #2632

**Comment by crystabelrangel** [comment]
Footer has been approved
![Image](https://github.com/user-attachments/assets/42326276-ce70-46db-a899-f4edea288ca3)
