### ISSUE TITLE
Design a branded BetaAlert component

### ISSUE THREAD

**Issue by andycochran** [HHS/simpler-grants-gov#2986]
### Summary

Apply the approved brand to the BetaAlert component. This is a custom component that uses the [Alert component](https://designsystem.digital.gov/components/alert/)). We do not have to account for all the variants for this component, although this might be automatically resolved when setting the color palette. 

### Acceptance criteria

- [x] Senongo has approved the brand application 
- [x] Emily has approved the design
- [ ] FE ticket has been updated per #2632

**Comment by crystabelrangel** [comment]
The Alert will be a page element rather than on top of the page. It will also no longer be sticky. 
Slight style updates may be made to look different from the button styles.

![Image](https://github.com/user-attachments/assets/9dd59e7c-36dc-4a7c-b254-ca730837573a)
