### ISSUE TITLE
Design a branded Homepage Hero component

### ISSUE THREAD

**Issue by andycochran** [HHS/simpler-grants-gov#2987]
### Summary

Apply the approved brand to the Homepage Hero component. 

Note: This is a custom component that uses `.usa-dark-background` which is not well-documented. You must be cautious/explicit about how colors and typography appear nested within this class. 

### Acceptance criteria

- [x] Senongo has approved the brand application 
- [x] Emily has approved the design
- [ ] FE ticket has been updated per #2632

**Comment by crystabelrangel** [comment]
Hero component is ready to start FE work. @andycochran will explore to make the star logo icon responsive.
![Image](https://github.com/user-attachments/assets/cca90693-5b92-43f4-937c-412b5b4a29f4)
