### ISSUE TITLE
Determine timeline for next Co-Design session

### ISSUE THREAD

**Issue by mxk0** [HHS/simpler-grants-gov#3014]
### Summary

Once the intro Co-Design group sessions happen, we need to determine the timeframe for planning and running the next session.

### Acceptance criteria

- [ ] Timeline for planning and running next Co-Design session determined
- [ ] Epic has been created for holding the [Dec/Jan] CDG session
- [ ] Issues have been created for inviting participants, scheduling the call, etc

**Comment by andycochran** [comment]
Adding AC for ticketing the next chunk of work…
