### ISSUE TITLE
Add Nava metrics to sprint metrics board

### ISSUE THREAD

**Issue by widal001** [HHS/simpler-grants-gov#3022]
### Summary

Duplicate the following Metabase questions and add them to a Nava tab in the sprint metrics dashboard:

- [Sprint burndown by issues](http://metabase-dev-710651776.us-east-1.elb.amazonaws.com/question/115-agile-six-sprint-burndown-by-issues)
- [Sprint burndown by points](http://metabase-dev-710651776.us-east-1.elb.amazonaws.com/question/119-agile-six-sprint-burndown-by-points)
- [Sprint burnup by issues](http://metabase-dev-710651776.us-east-1.elb.amazonaws.com/question/116-agile-six-sprint-burnup-by-issues)
- [Sprint burnup by points](http://metabase-dev-710651776.us-east-1.elb.amazonaws.com/question/117-agile-six-sprint-burnup-by-points)

Or alternatively, find a way to update this model so that it uses a variable for the project number (i.e. 17 for Agile Six and 13 for Nava) and then use the same charts across both tabs of sprint metrics dashboard.

### Acceptance criteria

- [x] The sprint metrics dashboard has been updated to include both an Agile Six tab and a Nava tab
- [x] Both tabs have the following metrics:
  - [x] Last updated
  - [x] Days left in sprint
  - [x] Sprint burndown & burnup by issues
  - [x] Sprint burndown & burnup by points

**Comment by DavidDudas-Intuitial** [comment]
![Image](https://github.com/user-attachments/assets/6574e55e-3a51-43b5-b0a1-bc7f73fae90d)
![Image](https://github.com/user-attachments/assets/0254dd08-fdbd-4c02-add1-11317afdcd33)

**Comment by DavidDudas-Intuitial** [comment]
http://metabase-dev-710651776.us-east-1.elb.amazonaws.com/dashboard/13-sprint-metrics-new?tab=16-agile-six

**Comment by DavidDudas-Intuitial** [comment]
![Image](https://github.com/user-attachments/assets/9088e9dc-cdbc-47f5-84ae-cfa7d2814c3c)
![Image](https://github.com/user-attachments/assets/7abe8106-c4cb-4716-b3e5-224f59b0db84)

**Comment by widal001** [comment]
Wooohooo!! Super exciting!

**Comment by DavidDudas-Intuitial** [comment]
http://metabase-dev-710651776.us-east-1.elb.amazonaws.com/dashboard/12-sprint-metrics?tab=19-agile-six
