### ISSUE TITLE
Support filtering sprint metrics by Sprint

### ISSUE THREAD

**Issue by widal001** [HHS/simpler-grants-gov#3023]
### Summary

Duplicate the "[Current sprint data](http://metabase-dev-710651776.us-east-1.elb.amazonaws.com/model/113-agile-six-current-sprint-data)" model and update it to accept Sprint as a variable used to filter the data returned by the model, then update or create new questions related to sprint metrics that use this date-based slice of sprint data.

### Acceptance criteria

- [x] In the existing sprint metrics dashboard (or a new interactive copy) users can view a snapshot of the sprint metrics for a certain sprint

**Comment by DavidDudas-Intuitial** [comment]
http://metabase-prod-899895252.us-east-1.elb.amazonaws.com/dashboard/10-sprint-metrics?scrum_board=17&sprint_name=Sprint+1.6

**Comment by DavidDudas-Intuitial** [comment]
<img width="764" alt="Image" src="https://github.com/user-attachments/assets/b8d50c5f-3c37-4ff2-9bc3-32f1aa287b93" />

**Comment by DavidDudas-Intuitial** [comment]
Public URL
http://metabase-prod-899895252.us-east-1.elb.amazonaws.com/public/dashboard/9b33aa23-df15-461e-8f1e-77c6f95eba8d?scrum_board=17&sprint_name=Sprint+1.6
