### ISSUE TITLE
Add velocity chart to the sprint metrics dashboard

### ISSUE THREAD

**Issue by widal001** [HHS/simpler-grants-gov#3024]
### Summary

Add a velocity chart to the [sprint metrics dashboard](http://metabase-dev-710651776.us-east-1.elb.amazonaws.com/dashboard/12-sprint-metrics-agile-six), which should be a bar chart of the total number of points complete in the last 4 sprints.

### Acceptance criteria

- [x] The sprint metrics dashboard displays the number of points complete in the last 4 sprints
- [x] This chart has been added to both the Agile Six and the Nava tab of the dashboard

**Comment by DavidDudas-Intuitial** [comment]
http://metabase-dev-710651776.us-east-1.elb.amazonaws.com/dashboard/12-sprint-metrics?tab=19-agile-six

**Comment by DavidDudas-Intuitial** [comment]
![Image](https://github.com/user-attachments/assets/d12f0aff-5d6b-4470-aa2f-47f7bcedf613)
