### ISSUE TITLE
Update `unstable_setRequestLocale` to `setRequestLocale`

### ISSUE THREAD

**Issue by acouch** [HHS/simpler-grants-gov#3079]
### Summary

We [upgraded next-intl](https://github.com/HHS/simpler-grants-gov/pull/2593), but missed that [setRequestLocale is now stable](https://github.com/amannn/next-intl/pull/1437).

### Acceptance criteria

- [ ] function calls updated

**Comment by doug-s-nava** [comment]
this was done in https://github.com/HHS/simpler-grants-gov/pull/3089
