### ISSUE TITLE
Report back on engagement satisfaction feedback

### ISSUE THREAD

**Issue by andycochran** [HHS/simpler-grants-gov#3086]
### Summary

Once we've heard from search usability testing session participants, report back their satisfaction level to Product/HHS. The metric is: of the number of participants who gave feedback on how the sessions went, what percentage of them would participate again or recommend someone to participate?

### Acceptance criteria

- [x] Product has been notified of engagement satisfaction rating

**Comment by crystabelrangel** [comment]
@mxk0 here is the report on the engagement satisfaction feedback.
https://docs.google.com/document/d/19yBuM8hsc3WYB-TOZJrfyLfsXrRmCmIW0aGD82PWn8E/edit?usp=sharing
