### ISSUE TITLE
Search: HHS agencies not showing full slate of available Opportunities

### ISSUE THREAD

**Issue by margaretspring** [HHS/simpler-grants-gov#3113]
### Summary

Narmada was testing out search & when she selected All the HHS agencies (3 listed in our search) only 13 Forecasted & Posted Opportunities showed up. On Grants.gov it's 1,329 opportunities. 

Not sure if we're missing agencies or opportunities? 

### Reproducibility

I tried multiple times and saw the bug every time

### How to reproduce the bug

Search for All HHS Forecasted & Posted Opportunities on Simpler.Grants.gov & Grants.gov... results are 13 vs 1329 (as of today). 

### Browser

None

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by chouinar** [comment]
Not exactly the same, but if you query by `HHS` that brings up a similar number:
https://simpler.grants.gov/search?query=HHS

At the time of writing this, I see 1328 results.

---

As a bit of additional sanity testing, I grabbed every agency that currently appears on grants.gov and queried the API directly with those:
```json
{
  "filters": {
    "agency": {
      "one_of": ["HHS-CDC-NCHHSTP", "HHS-CDC-NCIRD", "HHS-CMS", "HHS-AHRQ", "HHS-ACF-ANA", "HHS-ACF-OPRE", "HHS-CDC-GHC", "HHS-ACF-OHS", "HHS-ARPAH", "HHS-OPHS", "HHS-ACF-OFVPS", "HHS-ACF-OCS", "HHS-CDC-HHSCDCERA", "HHS-ACF-FYSB", "HHS-ACF-OTIP", "HHS-CDC-NCEZID", "HHS-IHS", "HHS-OS-ASPR", "HHS-CDC-NCCDPHP", "HHS-CDC-NCBDDD", "HHS-NIH11", "HHS-ACF-ORR", "HHS-ACF-OFA", "HHS-FDA", "HHS-HRSA", "HHS-SAMHS-SAMHSA", "HHS-CDC-NCIPC", "HHS-ACF", "HHS-ACF-CB", "HHS-ACL", "HHS-OS-ONC"]
    },
    "opportunity_status": {
      "one_of": [
        "forecasted",
        "posted"
      ]
    }
  },
  "pagination": {
    "order_by": "opportunity_id",
    "page_offset": 1,
    "page_size": 25,
    "sort_direction": "descending"
  }
}
```

And also got 1328 results:
```json
  "pagination_info": {
    "order_by": "opportunity_id",
    "page_offset": 1,
    "page_size": 25,
    "sort_direction": "descending",
    "total_pages": 54,
    "total_records": 1328
  }
```

**Comment by chouinar** [comment]
@mdragon - if we want to set a static config, this should be the right format for the frontend / contain agencies that have at least one opportunity.
[agency_data.json](https://github.com/user-attachments/files/18026976/agency_data.json)
