### ISSUE TITLE
Big Demo Webinar Invite Summary

### ISSUE THREAD

**Issue by margaretspring** [HHS/simpler-grants-gov#3157]
### Summary

Draft Quad 1 Big Demo summary for public event invite & get approvals. 

Initial Draft: https://docs.google.com/document/d/1Maxm6Du6MLT6Ij_T_3lPYTHvBRUNbVO1vph99ejVyDs/edit?usp=sharing

### Acceptance criteria

- [x] Draft Summary
- [x] Get Approval from HHS
- [x] Share to COFFA contact
- [x] Confirm public invite available

**Comment by margaretspring** [comment]
@michellemin-nava It ended up being longer than a paragraph. Please check out the initial draft link above. Would appreciate your edits for voice & content. Thank you!

**Comment by andycochran** [comment]
Does this issue include determining the invite list (e.g. Simpler mailing list, more)?

**Comment by michellemin-nava** [comment]
@andycochran, that should fall under the AC "Confirm public invite available." 

We want to use the Simpler mailing list and the Grants.gov newsletter. The former doesn't seem like it will be an issue, but the next Grants.gov newsletter edition is scheduled to go out in the third week of January, after the date of the Big Demo. @margaretspring and I need to connect to adjust our plan for the invite list.

**Comment by michellemin-nava** [comment]
@margaretspring, I completed my review pass for voice and content.

**Comment by margaretspring** [comment]
Julius approved the updates & the synopsis for the presentation was shared to with the GSA/COFFA contact Julius provided. Will post the public invite link here when I hear back about it getting booked.

**Comment by margaretspring** [comment]
Quad 1 Big Demo Registration - https://gsa.zoomgov.com/meeting/register/vJIscOCsrDgrG3wCaA7x0ysAkcdc2jMs0Zw#/registration
