### ISSUE TITLE
Align on remaining UX for auth MVP

### ISSUE THREAD

**Issue by mxk0** [HHS/simpler-grants-gov#3173]
### Summary

Design for:

Where do we send the user once they successfully create an account/log in?

- For the MVP, send the user back to the home page. In a future iteration we'll send the user back to the page they were on.

### Acceptance criteria

- [ ] Design published in Figma

**Comment by andycochran** [comment]
> Where do we send the user once they successfully create an account/log in?

If possible, send the user back to the page they were on when they entered the sign-in flow — e.g. if they were in the middle of a search, when they're done with Login, they still see the search with all its filters and keywords; or if they were looking at an opportunity, they're brought back to it. Login should not cause users to lose their work. 

Eventually, we'll probably want some sort of landing page for the account. But that's not ready yet. 

(via @snyder-ux)

**Comment by andycochran** [comment]
> How do we show auth errors?

Doesn't this all happen in login.gov? Would the be e.g. if you click the sign in button but the service is down? Is there a chance someone could successfully authenticate w/ login.gov but there's an error on our end? 

Who should @snyder-ux sync with? 
/cc @mdragon

**Comment by snyder-ux** [comment]
Need to clarify types of error and messaging to support it: [thread](https://betagrantsgov.slack.com/archives/C05TGEL3C6Q/p1734445763903229)
We can design the UI after the initial launch. It is limited on who can experience this so not a risk nor a blocker for engineering to do this.
