### ISSUE TITLE
[Task]: Analytics - Lead/cycle time metric

### ISSUE THREAD

**Issue by widal001** [HHS/simpler-grants-gov#318]
### Description

Create a metric in the analytics package that shows the lead/cycle time of tickets in a given sprint. This will likely require some further scoping to make sure that the metric is demonstrating a helpful statistic.

### Definition of done

- [ ] The analytics package can calculate a metric that shows the number of days between when a ticket is created and when a ticket is closed
- [ ] This metric should also include the following stats:
  - [ ] Mean lead time
  - [ ] Median lead time

**Comment by AlexanderStephensonUSDS** [comment]
Is mean/median lead time across the full range of issues? E.g, the metric would say "5" for an issue opened on a monday and closed on a Friday but "2" if the average was two days?

**Comment by widal001** [comment]
We're taking a different approach with delivery reporting. Will re-open if this becomes relevant again.
