### ISSUE TITLE
Move sprint metrics dashboard from dev to prod Metabase

### ISSUE THREAD

**Issue by widal001** [HHS/simpler-grants-gov#3188]
### Summary

Copy and paste the Dev dashboards and queries to prod once the data is loaded into the prod data warehouse and Metabase has access to it. Then ask someone with admin privileges to toggle public sharing via a link for these two dashboards.

### Acceptance criteria

- [x] Dashboards have been recreated in prod Metabase
- [x] Dashboards are available to users without a login via a public link

**Comment by DavidDudas-Intuitial** [comment]
http://metabase-prod-899895252.us-east-1.elb.amazonaws.com/dashboard/10-sprint-metrics?tab=14-agile-six

**Comment by DavidDudas-Intuitial** [comment]
![Image](https://github.com/user-attachments/assets/f286d47d-5f9b-4918-a35d-bc13121c6834)

**Comment by DavidDudas-Intuitial** [comment]
<img width="832" alt="Image" src="https://github.com/user-attachments/assets/5de78104-8c13-44e7-a300-40d7167cccd7" />

**Comment by DavidDudas-Intuitial** [comment]
![Image](https://github.com/user-attachments/assets/3b1720af-5240-4c33-aa11-7e8e5586836b)

**Comment by DavidDudas-Intuitial** [comment]
Public URL: http://metabase-prod-899895252.us-east-1.elb.amazonaws.com/public/dashboard/9b33aa23-df15-461e-8f1e-77c6f95eba8d
