### ISSUE TITLE
[30k]: Co-Design Group planning

### ISSUE THREAD

**Issue by widal001** [HHS/simpler-grants-gov#327]
### Key links

- [Deliverable specification](https://simpler-grants.gitbook.io/wiki/product/deliverables/specifications/co-design-group)
- [Simpler Grants.gov full roadmap](https://github.com/orgs/HHS/projects/12)
- [10k milestones](https://github.com/orgs/HHS/projects/13/views/11?sliceBy%5Bvalue%5D=Co-design+group)

### Description

- **What:** Define scope, target underserved communities, and invite representative individuals necessary to build a co-design group around the Simpler.Grants.gov initiative
- **Why:** Ensures that Simpler.Grants.gov HHS decision makers design with the most underserved communities in the grants ecosystem and create continuous feedback loops to ensure equitable product development. This includes framing strategic problems, roadmap development, designing solutions, and iteration.
- **Who**
  - The most underserved applicant individuals/groups within the grants ecosystem
  - Internal Simpler.Grants.gov stakeholders

> [!NOTE]
> For more information about this deliverable, please refer to the deliverable specification linked above.

**Comment by widal001** [comment]
Promoting this to its own 30k deliverable

**Comment by EOKENAVA** [comment]
Weekly Update

What has been done?

- Deliverable spec meeting
- Deliverable date planning session

Status
Planning

Risk
None

Deliverable Date
TBD

What will be done?
- Start to define underserved user groups through PAC interview 
- SME interview with Stacey Grant for PAC
- SME interview with Maria Lopez Nunez
- Finalize PAC timeline 
- Finalize tool for viewing and storing PAC member contact information and affiliation

**Comment by lucasmbrown-usds** [comment]
What's our plan for "Start to define underserved user groups through PAC interview"? Did we end up getting that meeting with the USDS equity team? Do we think this will be wrapped up next week?

**Comment by EOKENAVA** [comment]
**Weekly Update**

What has been done?
- Continued Planning Session for Deliverable date
- Determine rough estimate for deliverable date

**Status**
On Track

**Risk**
None

**Deliverable Date**
July 9th

**What will be done?**
- Discuss timeline with SGG Leadership
- Legal and security requirements defined 
- Define scope of PAC member involvement in activities such as hackathons and participatory budgeting
- Determine budget, compensation strategy 
- Finalize the name of the PAC

**Comment by EOKENAVA** [comment]
**Weekly Update**

**What has been done?**
- Determined rough estimate for deliverable date
- Discussed timeline with SGG Leadership


**Status**
On Track

**Risk**
None

**Deliverable Date**
July 9th

**What will be done?**
- Legal and security requirements defined
- Define scope of PAC member involvement in activities such as hackathons and participatory budgeting
- Determine budget, compensation strategy
- Finalize the name of the PAC

**Comment by margaretspring** [comment]
**Weekly Update**

**What has been done?**
- Determined rough estimate for deliverable date
- Discussed timeline with SGG Leadership


**Status**
On Track

**Risk**
None

**Deliverable Date**
July 9th

**What will be done?** (Much the same as Risha is back from PTO as of 3/20 and picking up)
- Legal and security requirements getting clarified and drafted for approval
- Define scope of PAC member involvement in activities such as hackathons and participatory budgeting
- Determine budget, compensation strategy
- Finalize the name of the PAC

**Comment by margaretspring** [comment]
**Weekly Update - IN DRAFT**

**What has been done?**
-
-

**Status**


**Risk**


**Deliverable Date**


**What will be done?**
-

**Comment by andycochran** [comment]
**Weekly Update**

**What has been done?**
- ...

**Status**
- In progress

**Risk**
- (Same as last update) Ethnio procurement, budget, and approvals from legal and execs on the agreements will impact the progression of this work

**Deliverable Date**
July 9th but still TBD

**What will be done?**
- ...

**Comment by margaretspring** [comment]
**Weekly Update 4/10**

**What has been done?**


**Status**
In Progress

**Risk**
If we have additional delays and aren't able to catch up (which is looking promising), then final deliverable approval timeline may extend past the current PoP end date of 5/14.  

**Deliverable Date**
Sprint 23 - for the whole 30k effort 5/14

**What will be done?**
- Incorporate [timeline deliverables as 10K & Tasks](https://github.com/HHS/simpler-grants-gov/issues/88#issuecomment-2018587270) in GitHub for greater transparency. Coordinate with Alexis on usage of Branding & Comms Board in GitHub 
- Continue work on Communications Strategy
- 4/11 Full Brand Positioning Recommendation at ToT
- Prep & review with Mh for April 16th Brand positioning Recommendations OG Leadership Review

**Comment by widal001** [comment]
Updated ticket format to reduce discrepancies with the deliverable spec.

**Comment by margaretspring** [comment]
**Weekly Update 4/17**

**What has been done?**


**Status**


**Risk**
  

**Deliverable Date**


**What will be done?**

**Comment by margaretspring** [comment]
**Weekly Update 4/24**

**What has been done?**



**Status**


**Risk**


**Deliverable Date**


**What will be done?**

**Comment by sarahknoppA6** [comment]
Date on ticket has been updated to reflect the expected 5/13 end date. 
Team to review changes to the Co-Design Group planning scope at the 30k review meeting on 5/1 to ensure all are in agreement on the scope and what is expected to be delivered at the end of the PoP.

**Comment by margaretspring** [comment]
**Weekly Update 5/1**

**What has been done?**
- 

**Status**
In Progress

**Risk**
 

**Deliverable Date**


**What will be done?**

**Comment by andycochran** [comment]
**Weekly Update 5/8**

Closed! 🏁
