### ISSUE TITLE
Implement Simpler.Grants.gov Static Updates

### ISSUE THREAD

**Issue by margaretspring** [HHS/simpler-grants-gov#3289]
### Summary

**Must ship by 1/10/25**

Implement content and design for Simpler.Grants.gov website updates. Coordinate with @snyder-ux on any questions.

### Acceptance criteria

- [ ] Content and design specified in #2865 and #3336 implemented and live in prod

**Comment by snyder-ux** [comment]
Content and page layout are approved. [thread](https://betagrantsgov.slack.com/archives/C061HLPAR4K/p1734989478717329)
