### ISSUE TITLE
[10k]: User research incentives

### ISSUE THREAD

**Issue by widal001** [HHS/simpler-grants-gov#329]
### Summary

TODO

### User story

TODO

### Dependencies

TODO

### Sub-Tasks

- [ ] TODO

### Acceptance criteria

- [ ] TODO

### Describe the proposed testing strategy

TODO

### Screenshots and additional context

TODO

**Comment by lucasmbrown-usds** [comment]
Should this be closed as a dupe of https://github.com/HHS/simpler-grants-gov/issues/84 ?

**Comment by widal001** [comment]
@lucasmbrown-usds Good catch, closing as not completed and applying the duplicate label.
