### ISSUE TITLE
Design Simpler.Grants.gov content updates (Process page)

### ISSUE THREAD

**Issue by mxk0** [HHS/simpler-grants-gov#3336]
### Summary

Once the content in #2865 is finalized, we need updated design for the Roadmap section of the Process page. Needed by ~12/27.

### Acceptance criteria

- [x] Design published in Figma

**Comment by snyder-ux** [comment]
Update page layouts in Figma - please share feedback @andycochran @michellemin-nava
- [Home](https://www.figma.com/design/FGxWtAgToKhehLJCiuy1zL/Simpler.Grants.gov-Project?node-id=1685-7244&t=w1Y9b9q8AyBGpOm7-1) - couple layout options
- [Process](https://www.figma.com/design/FGxWtAgToKhehLJCiuy1zL/Simpler.Grants.gov-Project?node-id=1685-8839&t=w1Y9b9q8AyBGpOm7-1)

Feedback from Andy: the home page layout shouldn’t change for now ([thread](https://nava.slack.com/archives/C057K146W8H/p1734728125523989))

**Comment by snyder-ux** [comment]
[Slack thread](https://betagrantsgov.slack.com/archives/C05T74HRWRL/p1734734985495769) -  waiting on approval of content updates
- Page design in [doc with content updates](https://docs.google.com/document/d/1lfWLaiEPC6SK7nsIa5u8u5fyZJRki6n7rtMCtZ5rcKw/edit?tab=t.0#heading=h.xoa74grbzuux)

**Comment by snyder-ux** [comment]
Layout approved - [Slack thread](https://betagrantsgov.slack.com/archives/C061HLPAR4K/p1734989478717329)

**Comment by snyder-ux** [comment]
Minor UI Update: Process page new content should have an icon for the GitHub links for consistency. The existing page links use the icon to indicate links that go to another site and it should open in a new tab. (links to other pages in the same site do not get a link and it opens within the same tab, ie, replaces the page).
