### ISSUE TITLE
[Task]: Shared Calendar Implementation

### ISSUE THREAD

**Issue by EOKENAVA** [HHS/simpler-grants-gov#409]
### Summary

We selected TBD as the shared calendar tool of choice in the  TBD ticket. This work is to set up an onboarding process so that users can easily onboard to TBD, start using it, and navigate the tool easily.

### Acceptance criteria

-  Onboarding instructions for new users are clearly and accessibly documented in a public place.
-  Instructions for the internal team that assists with onboarding new users are clearly and accessibly documented in a public place.
-  At least 5 members of HHS full-time staff have been onboarded.
-  At least 5 members of contractor teams (employed by HHS) have been onboarded.
-  At least 3 members of the general public have been onboarded.
-  New users can be onboarded to the tool for no cost to the user in a process that takes less than 2 days.
-  Services are accessible to all people on the HHS network, public internet, and preferably the White House network and most or all agency networks

**Comment by EOKENAVA** [comment]
@sarahknoppA6 , Hi Sarah, this should be completed internally by end of week. HHS Staff should be completed next week

**Comment by sarahknoppA6** [comment]
@EOKENAVA could you please provide an update here on the plan to accomplish this, just to keep Github up to date?

**Comment by EOKENAVA** [comment]
Scheduled training session with HHS staff for 12/6 to train and onboard

**Comment by EOKENAVA** [comment]
@lucasmbrown-usds @sarahknoppA6 - Should the following acceptance criteria still be relevant ?  "At least 3 members of the general public have been onboarded." I don't imagine we are onboarding folks from the public anytime soon

**Comment by sarahknoppA6** [comment]
@EOKENAVA It would depend on the ETA of getting a community manager, as we would hope to start onboarding members of the public after they get here.

**Comment by lucasmbrown-usds** [comment]
Are we tracking a list of HHS/contractor users who have been onboarded to this already, and who still needs to be onboarded? 

Also, did we resolve the issues for Narmada and others?

**Comment by sarahknoppA6** [comment]
@EOKENAVA could you please provide an update based on Lucas' questions above?

**Comment by EOKENAVA** [comment]
@lucasmbrown-usds @sarahknoppA6 - It’s stuck on HHS IT
Julius was onboarded but no one else had permissions to onboard. Emily mentioned contacting HHS IT to figure out what is going on. While I am OOO, I created a thread on the simpler slack channel to track progress

**Comment by sarahknoppA6** [comment]
@EOKENAVA Narmada informed us that IT denied her request to integrate slack with outlook, saying that slack does not have a valid ATO on file. Julius is also not able to complete the integration.
Let's regroup on next steps when you return.

**Comment by EOKENAVA** [comment]
SIA for Slack has been approved. Sarah to check in with Narmada on next steps

**Comment by margaretspring** [comment]
@sarahknoppA6 - Assuming this can be closed, but wanted to confirm. Thank you

**Comment by sarahknoppA6** [comment]
@lucasmbrown-usds I think there were some lingering action items on this one (but I might be mistaken)- is HHS now able to use the calendaring plugin?

**Comment by margaretspring** [comment]
Zoom & Ethnio fulfill an aspect of the scheduling needs & will draft a more current & specific for new needed work.
