### ISSUE TITLE
[Task]: Update Appendix X with Simpler changes

### ISSUE THREAD

**Issue by sumiat** [HHS/simpler-grants-gov#464]
### Summary 
The SIA will cover the approaches being used to launch [beta.grants.gov](http://beta.grants.gov/) as part of our overall [grants.gov](http://grants.gov/) system, and how those approaches fit within our existing [grants.gov](http://grants.gov/) SSP. This work identifies how our approaches might require changes to it the existing Appendix X and to document and note those changes and controls. 

Updates for the following controls should be addressed:

[AU-1: Audit And Accountability Policy And Procedures](https://csf.tools/reference/nist-sp-800-53/r4/au/au-1/)
[AU-2: Audit Events](https://csf.tools/reference/nist-sp-800-53/r4/au/au-2/)
[AU-3: Content Of Audit Records](https://csf.tools/reference/nist-sp-800-53/r4/au/au-3/)
[AU-4: Audit Storage Capacity](https://csf.tools/reference/nist-sp-800-53/r4/au/au-4/)
[AU-5: Response To Audit Processing Failures](https://csf.tools/reference/nist-sp-800-53/r4/au/au-5/)
[AU-7: Audit Reduction And Report Generation](https://csf.tools/reference/nist-sp-800-53/r4/au/au-7/)
[AU-9: Protection Of Audit Information](https://csf.tools/reference/nist-sp-800-53/r4/au/au-9/)
[AU-11: Audit Record Retention](https://csf.tools/reference/nist-sp-800-53/r4/au/au-11/)
[CM-3: Configuration Change Control](https://csf.tools/reference/nist-sp-800-53/r4/cm/cm-3/)
[CM-6: Configuration Settings](https://csf.tools/reference/nist-sp-800-53/r4/cm/cm-6/)
[CM-8: Information System Component Inventory](https://csf.tools/reference/nist-sp-800-53/r4/cm/cm-8/)
[CM-9: Configuration Management Plan](https://csf.tools/reference/nist-sp-800-53/r4/cm/cm-9/)
[CM-10: Software Usage Restrictions](https://csf.tools/reference/nist-sp-800-53/r4/cm/cm-10/)
[CP-1: Contingency Planning Policy And Procedures](https://csf.tools/reference/nist-sp-800-53/r4/cp/cp-1/)
[CP-2: Contingency Plan](https://csf.tools/reference/nist-sp-800-53/r4/cp/cp-2/)
[CP-3: Contingency Training](https://csf.tools/reference/nist-sp-800-53/r4/cp/cp-3/)
[CP-4: Contingency Plan Testing](https://csf.tools/reference/nist-sp-800-53/r4/cp/cp-4/)
[CP-6: Alternate Storage Site](https://csf.tools/reference/nist-sp-800-53/r4/cp/cp-6/)
[CP-7: Alternate Processing Site](https://csf.tools/reference/nist-sp-800-53/r4/cp/cp-7/)
[CP-9: Information System Backup](https://csf.tools/reference/nist-sp-800-53/r4/cp/cp-9/)
[IR-1: Incident Response Policy And Procedures](https://csf.tools/reference/nist-sp-800-53/r4/ir/ir-1/)
[IR-2: Incident Response Training](https://csf.tools/reference/nist-sp-800-53/r4/ir/ir-2/)
[IR-4: Incident Handling](https://csf.tools/reference/nist-sp-800-53/r4/ir/ir-4/)
[IR-5: Incident Monitoring](https://csf.tools/reference/nist-sp-800-53/r4/ir/ir-5/)
[IR-6: Incident Reporting](https://csf.tools/reference/nist-sp-800-53/r4/ir/ir-6/)
[IR-7: Incident Response Assistance](https://csf.tools/reference/nist-sp-800-53/r4/ir/ir-7/)
[IR-8: Incident Response Plan](https://csf.tools/reference/nist-sp-800-53/r4/ir/ir-8/)
[PL-8: Information Security Architecture](https://csf.tools/reference/nist-sp-800-53/r4/pl/pl-8/)
[RA-2: Security Categorization](https://csf.tools/reference/nist-sp-800-53/r4/ra/ra-2/)
[RA-5: Vulnerability Scanning](https://csf.tools/reference/nist-sp-800-53/r4/ra/ra-5/)
[SA-3: System Development Life Cycle](https://csf.tools/reference/nist-sp-800-53/r4/sa/sa-3/)
[SA-4: Acquisition Process](https://csf.tools/reference/nist-sp-800-53/r4/sa/sa-4/)
[SA-5: Information System Documentation](https://csf.tools/reference/nist-sp-800-53/r4/sa/sa-5/)
[SA-10: Developer Configuration Management](https://csf.tools/reference/nist-sp-800-53/r4/sa/sa-10/)
[SA-11: Developer Security Testing And Evaluation](https://csf.tools/reference/nist-sp-800-53/r4/sa/sa-11/)
[SC-7: Boundary Protection](https://csf.tools/reference/nist-sp-800-53/r4/sc/sc-7/)
[SI-2: Flaw Remediation](https://csf.tools/reference/nist-sp-800-53/r4/si/si-2/)
[SI-3: Malicious Code Protection](https://csf.tools/reference/nist-sp-800-53/r4/si/si-3/)
[SI-4: Information System Monitoring](https://csf.tools/reference/nist-sp-800-53/r4/si/si-4/)
[SI-5: Security Alerts, Advisories, And Directives](https://csf.tools/reference/nist-sp-800-53/r4/si/si-5/)
[SI-7: Software, Firmware, And Information Integrity](https://csf.tools/reference/nist-sp-800-53/r4/si/si-7/)
[SI-11: Error Handling](https://csf.tools/reference/nist-sp-800-53/r4/si/si-11/)
[SI-12: Information Handling And Retention](https://csf.tools/reference/nist-sp-800-53/r4/si/si-12/)

### Acceptance Criteria
- [ ] Make the necessary updates to the SSP and Asset Inventory, Catalog of Control in Appendix X for the first release of the static site.

**Comment by EOKENAVA** [comment]
From Jake: Alright, here's the breakdown of where I'm at as it relates to the Simpler Appendix X.
If a row is yellow it still needs love. If it's green it's good.
I have about 100 controls that need to be re-reviewed (yellow). The controls that are stuck in yellow with the status of Pending are going in the POAM list until I get confirmation from the Simpler team on it.
[Simpler_Grants_POAM_List.xlsx](https://microhealth.sharepoint.com/:x:/t/SimplerSecurity-SecurityDocuments/EaTlqfrZ4ltMoGcX1W0YUUEB84DNFdCrUfg-RvRv3kl8Uw?e=An8vRa&isSPOFile=1)

**Comment by jldroid19** [comment]
@acouch @coilysiren A good number of controls require a Monitoring and Logging SOP.  We are leaning on the grants.gov side to get their current SOP so we can utilize it.

**Comment by jldroid19** [comment]
The Appendix X and POA&M list has been completed 1st Pass 12JAN2024. These documents can be reviewed from within SharePoint.

**Comment by acouch** [comment]
The updated Appendix X has been sent to HHS. Closing!
