### ISSUE TITLE
[Task]: Update Configuration Management Plan (CMP)

### ISSUE THREAD

**Issue by sumiat** [HHS/simpler-grants-gov#465]
### Summary 
There is a Configuration Management Plan (CMP) that needs to be updated for the security portion of the #70 . This issue is to create the updates and for them to be accepted by the current Grant.gov team. Presenting to HHS will be captured elsewhere.

### Acceptance Criteria
- [x] Draft sent to MH for review
- [x] Changes reviewed and accepted by MH

**Comment by acouch** [comment]
Plan has been shared with MH, so moving to "In Review."

**Comment by acouch** [comment]
The CMP has been updated and reviewed with MH, but still in a draft state. Next step is to #890
