### ISSUE TITLE
[10k]: Communication planning

### ISSUE THREAD

**Issue by widal001** [HHS/simpler-grants-gov#47]
### Description

Create ADRs and complete ATO or FedRAMP for chat, wiki, ticket tracking, calendar, email listservs, and email inboxes in a way that's accessible for all team members and the public.

### Dependencies

- [x] #53 

### Sub-Tasks

- [x] #22 
- [x] #98 
- [x] #105 
- [x] #99 
- [x] #30 
- [x] #378 
- [x] #682 

### Definition of Done

- [x] ADRs are completed and approved for the tools below
- [x] #98 
- [x] #105 
- [x] #99 
- [x] #30 
- [x] #378

**Comment by sarahknoppA6** [comment]
Move ADRs for public comms tool and feedback mechanism to static site improvement milestone

**Comment by sumiat** [comment]
@widal001 - i moved shared calendar and document sharing out of this and added to #61. i will close this out!
