### ISSUE TITLE
[Task]: Securing HHS email for A6 team

### ISSUE THREAD

**Issue by widal001** [HHS/simpler-grants-gov#476]

**Comment by widal001** [comment]
Waiting for next steps from MH. We've provided all of the details requested. 

**Next Step:** Send follow-up email. Ask Athena to follow up while Sarah is out.

**Comment by sarahknoppA6** [comment]
Lucas is currently helping with following up on this because we haven't made any traction on it.

**Comment by sarahknoppA6** [comment]
It looks like the path for action is that Marc is going to get T2 access so he can submit our onboarding. This might take a long time.
