### ISSUE TITLE
[Task]: Create DMS Event Subscriptions

### ISSUE THREAD

**Issue by SammySteiner** [HHS/simpler-grants-gov#504]
### Summary

DMS requires event subscriptions to keep the replica database in sync with the source database.
Create 2 event subscriptions, including one for the replication instance and one for the replication task, in both dev environments.
Reference: https://docs.aws.amazon.com/dms/latest/userguide/CHAP_Events.html

### Acceptance criteria

- [ ] non prod event subscription for replication instance created
- [ ] non prod event subscription for replication task created
- [ ] staging event subscription for replication instance created
- [ ] staging event subscription for replication task created
- [ ] prod event subscription for replication instance created
- [ ] prod event subscription for replication task created

**Comment by SammySteiner** [comment]
https://docs.aws.amazon.com/dms/latest/userguide/CHAP_Task.CDC.html

**Comment by SammySteiner** [comment]
https://github.com/terraform-aws-modules/terraform-aws-dms/blob/v2.0.0/examples/complete/README.md

**Comment by acouch** [comment]
Closing this as we are no longer using DMS.
