### ISSUE TITLE
[Task]: Setup VPC Peering for DMS

### ISSUE THREAD

**Issue by SammySteiner** [HHS/simpler-grants-gov#505]
### Summary

In order to replicate a database in another VPC, we must configure VPC peering so data can be transferred between VPCs. Additionally, we want to ensure our database resides in the same az as the source database to significantly reduce costs. 

We will need to work closely with Microhealth to configure VPC Peering.
Reference: https://docs.aws.amazon.com/dms/latest/userguide/CHAP_ReplicationInstance.VPC.html#CHAP_ReplicationInstance.VPC.Configurations.ScenarioVPCPeer

### Acceptance criteria

- [x] Microhealth opened up their VPC for peering
- [ ] We configured vpc peering in terraform

**Comment by acouch** [comment]
The VPC peering has been [setup in dev](https://us-east-2.console.aws.amazon.com/vpcconsole/home?region=us-east-2#PeeringConnections). The configuration needs to be added to terraform.

**Comment by daphnegold** [comment]
We need to redo the VPC peering connection from us-east-1 where our infra lives, and remove the last peering connection.

**Comment by daphnegold** [comment]
Blocked on acceptance of peering request and communication from MicroHealth

**Comment by daphnegold** [comment]
Copypasta from pull request for documentation purposes.

Note for posterity: After discussions with MicroHealth, we acknowledged the potential need to adopt a custom route table with explicit subnet associations to enhance network segmentation and control. Currently, we're utilizing the default route table, which is implicitly associated with all subnets within the VPC.
