### ISSUE TITLE
[Task]: Load Frontend Dev TLS secret and cert to AWS SSM

### ISSUE THREAD

**Issue by SammySteiner** [HHS/simpler-grants-gov#533]
### Summary

Load the front end dev private key from the csr request and the certificate provided by HHS or ITS to a secret in AWS SSM with the name of `/lb/frontend-dev/tls-private-key` and `/lb/frontend-dev/tls-certificate`.
Blocked by getting the certificate from HHS or ITS.

### Acceptance criteria

Secret exists in AWS SSM as encrypted strings

**Comment by SammySteiner** [comment]
Created secret and added the private key. waiting on the certificate from Terrence.

**Comment by daphnegold** [comment]
Using ssm was causing issues with an invalid cert. I ripped out any ssm stuff and just imported cert into ACM, consumed in service layer via `data` block. This is a fine solution and don't think it warrants any adjustment. There's more info and opinions in this thread:

https://nava.slack.com/archives/C03G1SWD9H7/p1695409704510329
