### ISSUE TITLE
Draft v2 content for beta site

### ISSUE THREAD

**Issue by sumiat** [HHS/simpler-grants-gov#541]
### Description

We want to update the content on the beta site to include: what we've worked on, what we're working on, what's coming next. 

### Acceptance Criteria

- [ ] Outline of the content changes

### Notes
- highlighting aspects of the past research
- more non-technical CTA
- Got ideas vs Questions section
- Google group
- switching to simpler.grants.gov
- survey

**Comment by andycochran** [comment]
This ticket spread across multiple sprints. Went thru v5, actually. Making a new ticket to track v6.
