### ISSUE TITLE
[Task]: Update static site for move to simpler.grants.gov

### ISSUE THREAD

**Issue by acouch** [HHS/simpler-grants-gov#550]
### Summary

The static site uses "beta.grants.gov" as the header logo text and references "beta" in several other places (hero section, beta alert, and the "Ways to get involved" section), e.g.: 

https://github.com/HHS/grants-equity/blob/582b9dd8d3110b65e05ed51d08fa7b23238b0026/frontend/public/locales/en/common.json#L3 

Additionally, the "Ways to get involved" section contains references to "Grants Equity" as the repo name and name of the project. 

This project is being rebranded with the name "Simpler Grants.gov" which should replace all of the instances of beta. 

---

**_NOTE: The timing of deploying of this content change will need to be coordinated with the timing of any URL change._** 

---

### Acceptance criteria

- [x] the move from beta.grants.gov to simpler.grants.gov has been confirmed
- [x] content changes have been approved
- [ ] static site updated for change "beta" to "Simpler Grants.gov"

**Comment by andycochran** [comment]
Approved content: https://app.gitbook.com/o/cFcvhi6d0nlLyH2VzVgn/s/v1V0jIH7mb7Yb3jlNrgk/design/content-approval/fy23-q4/content-review-change-beta-to-simpler
