### ISSUE TITLE
CloudFront - CDN for Static Site

### ISSUE THREAD

**Issue by acouch** [HHS/simpler-grants-gov#555]
### Description

A CDN would increase the ability to respond to traffic by orders of magnitude, as well as deliver the page faster for regions not near the data center we use.

This ADR is to decide on a CDN and note any implementation issues or considerations. Since we are using AWS, [CloudFront](https://aws.amazon.com/cloudfront/) seems like the best choice since we are already using AWS, we can store the configuration in terraform, and we would not need a separate account or workflow to manage it. The implementer could ask HHS, MH, or internally if there is a clearly better alternative.

This ADR does not need to go into too much detail if there is we are not realistically considering alternatives.

### Open Questions
- Will the CDN have long-term value once/if the site is more than static?
- Will the CDN be impacted or influenced by the future CMS?

### Approvers

@acouch @daphnegold @SammySteiner @sumiat 

### Options

* [CloudFront](https://aws.amazon.com/cloudfront/)
* [CloudFlare](https://www.cloudflare.com/)
* [F5](https://f5.com)

### Decision Criteria

* Low LOE to operate
* Can us IaC
* Fedramp moderate approved
* Provides features of a CDN

### Definition of Done

- [ ] The approvers for this decision have been identified (ideally before work on the ADR starts)
- [ ] The ADR is created and stored in `documentation/decisions/adr` with status "Accepted"
- [ ] The ADR has been reviewed and approved by the approvers listed above
- [ ] The ADR satisfies requirements that are outlined in the ADR template
- [ ] Any follow-up tickets have been created (if necessary)

**Comment by sumiat** [comment]
not needed
