### ISSUE TITLE
[Task]: Review existing data standards and models

### ISSUE THREAD

**Issue by acouch** [HHS/simpler-grants-gov#570]
### Summary

As part of the GaaP inquiry, and the data modeling required for the project in general, and specifically the opportunities API, we should perform an initial review of the relevant data standards and models, including but not limited to:

- [x] DAIMS
- [x] Federal Integrated Business Framework (FIBF) GRM
- [x] OpenGrants
- [x] Standard interface file definition used by the [TAGGS](https://taggs.hhs.gov/)
- [x] grants.gov current web services definitions
- common data fields identified by TagTech and others (removed as more relevant for the apply stage)

The overview should contextualize the standards and models for grants.gov and identify opportunities and common fields for a data model and api.

### Acceptance criteria

- [x] Review is published in internal wiki
- [ ] Review is reviewed with team

**Comment by acouch** [comment]
Initial work is started [here](https://docs.google.com/document/d/1hqA83_vXbrFp2Zd_i4ar0negbR1kOWwP7YqrmQ2ikO4/edit).

**Comment by acouch** [comment]
This has been shared on the [internal wiki](https://app.gitbook.com/o/cFcvhi6d0nlLyH2VzVgn/s/v1V0jIH7mb7Yb3jlNrgk/planning/grants-as-a-platform/common-data-model-review)

**Comment by sumiat** [comment]
Thanks @acouch! I reviewed and made some edits and comments. Looks good!
