### ISSUE TITLE
[Task]: Get copy of development version of the filesystem

### ISSUE THREAD

**Issue by acouch** [HHS/simpler-grants-gov#584]
### Summary

We've discussed receiving a development copy of the file system that would be placed in s3. This issue is to track that progress.

### Acceptance criteria

- [x] Copy of dev filesystem available to team.

**Comment by EOKENAVA** [comment]
Micro Health has agreed to create a bucket in our account and share the dev version of their file system. We need to follow up with Curtis.

**Comment by EOKENAVA** [comment]
@acouch - I just verified with MH ITS staff that "a copy of development version of the filesystem" has already been replicated into an S3 bucket in the same VPC in which our team would be accessing the replica database, i.e. it has already been done.

**Comment by acouch** [comment]
This has been completed
