### ISSUE TITLE
[Spike]: Initial Data modeling for opportunities

### ISSUE THREAD

**Issue by acouch** [HHS/simpler-grants-gov#618]
### Summary

The current opportunity API fields:

* opportunity_id
* opportunity_number
* opportunity_title
* agency
* category (D, M, C, E or O)
* is_draft
* created_at
* updated_at

This ticket is to review the database for possible opportunity API data.

- [ ] Confirm current API fields match data from `topportunity` table
- [ ] Rough diagram of database for the tables that would return the

**Comment by chouinar** [comment]
I've got a rough document written up on https://app.gitbook.com/o/cFcvhi6d0nlLyH2VzVgn/s/v1V0jIH7mb7Yb3jlNrgk/engineering/learnings/opportunity-endpoint-data-model

Includes mapping of most values that appear on the existing search results back to values in the database. There are a few open questions still, but nothing that prevents an initial limited scope launch. We'll continue updating the documentation as we go, but it should be at a good place for now.
