### ISSUE TITLE
[Spike] Review current API Authentication and make a recommendation for short-term strategy

### ISSUE THREAD

**Issue by sumiat** [HHS/simpler-grants-gov#624]
## Summary

How do 3rd party systems connect to the API? Do we need auth for the basic get opportunities?

This ticket  is to review current [API Authentication through certificates](https://grants.gov/system-to-system/applicant-system-to-system/certificates) and make a recommendation for short-term and long-term auth strategy.

* Could we use the existing certificate system? Not a requirement. Certificates are not necessary. We need a method to verify that people are who they say they are. Certificate management puts extra work on our own operations and the consumer of the API. 
* Is there another option that would make sense for the near term?
  * Can allow users to sign up through an API, so that we don't have to create a UI initially?
* What would the LOE be to allow users to create a basic sign-up page? 
* Since this is all public data, should we just cache the API responses and let people use them in an-limited fashion?
* Would it make sense to use a tool like [API Gateway](https://aws.amazon.com/api-gateway/) to rate limit a public API or  handle auth?
* Consider when we need to evaluate a longer term solution. For example, we may want to have a more robust authn or authz before we release Search?

## Out of scope
- long-term strategy

## Acceptance Criteria

- [ ] Research spike document that is available in github or internal wiki
- [ ] Review with Lucas and/or Billy for approval
- [ ] Add comment in the ticket with spike findings

## Notes / open questions
- Once we publicly launch the API, how are we handling rate-limiting? 
- Is rate-limiting something we want for the initial alpha launch? If there are thousands of opportunities returned, we would want to think about approach. 
- GET opp does not need to be authn since the information is public. Consider what GSA has done for open GSA APIs. GET opp should be open to the public. 
- Rate-limiting / controlling load - it's not a hard requirement for this first release but something we want to plan for. As we continue to develop, we want to plan to have the capability to support load.
- Authn - we definitely need it for Apply or posting opportunities. Posting opps come from a system UI. 
- Ask for an access key - user gets one so we have something basic so we know who our callers are. This will help will load balancing and rate-limiting.

**Comment by mxk0** [comment]
Closing in favor of #2313.
