### ISSUE TITLE
Design research for Search experience

### ISSUE THREAD

**Issue by sumiat** [HHS/simpler-grants-gov#625]
### Summary

Understand the current Grants search experience so that we can improve it. The long-term goal is to create a more user-friendly, scalable search feature that aligns with the users' needs. The scope of this issue is knowledge gathering and exploring previous design work in preparation for creating new design deliverables (mockups, wireframes, prototypes) and an understanding of how search might be built iteratively (what's MVP, what patterns can be established). 

### Acceptance criteria

- [x] Review existing research on the Grants search experience, identifying pain points, and areas for improvement
- [x] Review existing user flow and any existing design artifacts for a new experience 
- [x] Add follow up tickets (such as Figma mockups, etc) 
  - https://github.com/HHS/simpler-grants-gov/issues/1001

#### Out of scope (to be handled thru separate tickets): 
- Figma mockups for the new Search experience, including the homepage, search page, opportunity listing page (that links to grants.gov)
- Figma mockups for potential design improvements for the Search feature
- Information architecture planning: propose an information architecture for the site to ensure that it's structured logically; with a stretch goal to consider future iterations that accommodate growth and development.

**Comment by andycochran** [comment]
Note: This will likely roll over into Sprint 15. There's a lot of previous design work that's been reviewed/explored. But we need to schedule time for some scoping conversations to determine scope of "MVP" (what's the least we can build).
