### ISSUE TITLE
[Task]: Listserv Implementation

### ISSUE THREAD

**Issue by sumiat** [HHS/simpler-grants-gov#631]
### Summary

We selected Google Groups as the listserv tool of choice in the #378. This work is to set up an onboarding process so that users can easily join our listserv, start using it, and navigate the tool easily. 

### Acceptance criteria
- [x] update wiki page on how we're using it and what the purpose is
- [x] update google groups messaging
  - [x] Onboarding instructions for new users are clearly and accessibly documented in a public place.
  - [x] Instructions for the internal team that assists with onboarding new users are clearly and accessibly documented in a public place.
  - [x] At least 5 members of contractor teams (employed by HHS) have been onboarded.
  - [x] New users can be onboarded to the tool for no cost to the user in a process that takes less than 2 days.
  - [x] Services are accessible to all people on the HHS network, public internet, and *preferably* the White House network and most or all agency networks

**Comment by sarahknoppA6** [comment]
@sumiat Could you confirm that the acceptance criteria of this ticket has been met? I'm not aware of any of these changes.

**Comment by sumiat** [comment]
Wiki: https://app.gitbook.com/o/cFcvhi6d0nlLyH2VzVgn/s/v1V0jIH7mb7Yb3jlNrgk/collaborating/communication-channels/google-groups-listserv
- update wiki page on how we're using it and what the purpose is 
- update google groups messaging
- Onboarding instructions for new users are clearly and accessibly documented in a public place.
- Instructions for the internal team that assists with onboarding new users are clearly and accessibly documented in a public place.

https://groups.google.com/g/simplergrantsgov
Services are accessible to all people on the HHS network, public internet, and preferably the White House network and most or all agency networks


What was not considered in this ticket: When we are ready to share this out with the public, we still need to think about our policies - how people can post, what posts might not be approved, groups we want to create, etc.
