### ISSUE TITLE
Procurement for communication tools

### ISSUE THREAD

**Issue by sumiat** [HHS/simpler-grants-gov#634]
### Summary

Complete the procurement process for the following communication tools: 

- Design/research and feedback tool
- Video conference tool: #99 

### Acceptance Criteria
- [ ] Tools above are added to the ODC and plan for procurement is finalized.

**Comment by EOKENAVA** [comment]
Removing "Design/research and feedback tool" as an AC.

**Comment by EOKENAVA** [comment]
stuck on MH. Waiting for procurement approval

**Comment by sumiat** [comment]
should we move this to blocked?

**Comment by EOKENAVA** [comment]
Stuck with MH. Waiting for funding approval

**Comment by margaretspring** [comment]
Covered by separate ticket for Ethnio & Zoom acquisition
