### ISSUE TITLE
[Task]: Artillery.io for performance testing

### ISSUE THREAD

**Issue by sumiat** [HHS/simpler-grants-gov#647]
### Summary

Set up performance testing

### Acceptance criteria

- [ ] Use artillery.io for back-end performance testing
- [ ] Publish documentation on the setup in github or internal wiki

### Open Notes / Questions
- We're using Artillery.io for the front-end and we could use it for back-end
- 1000 concurrent users, # of simultaneous requests are in the 20s
- Script is in the front-end folder and can just copy it to the back-end

**Comment by coilysiren** [comment]
I'm going to try out this one 👋🏼
