### ISSUE TITLE
[Task]: Setup Additional DMS Task Rules for Additional Tables for Mapping Values from Test Database to Simpler database

### ISSUE THREAD

**Issue by acouch** [HHS/simpler-grants-gov#652]
### Summary

This is a continuation of #649 . The first task is to do the `opportunity` table. This is to do any additional tables.

The [DMS service uses a mapping between values](https://docs.aws.amazon.com/dms/latest/userguide/CHAP_Tasks.CustomizingTasks.TableMapping.SelectionTransformation.Transformations.html) betweeen databases. This issue is to setup mapping for the opportunity that is not in the `topportunity` table.

The actual steps and implementation for this can be determined while working on this.

### Acceptance criteria

- [ ] DMS mapping for non-`opportunity` tables are implemented

**Comment by acouch** [comment]
Moving this to `blocked` based on the convo @chouinar noted.

**Comment by chouinar** [comment]
We aren't using DMS anymore.
