### ISSUE TITLE
[Task]: Upgrade PIP to 23.3

### ISSUE THREAD

**Issue by acouch** [HHS/simpler-grants-gov#654]
### Summary

The API deploy is blocked on a security vulnerability that was triggered by a necessary update of pip:

https://github.com/HHS/simpler-grants-gov/actions/runs/6772977806/job/18406859756#step:5:25

### Acceptance criteria

- [ ] Upgrade pip so that security vulnerability is no longer present or add to vulnerability whitelist

**Comment by chouinar** [comment]
@acouch - I added an ignore to https://github.com/HHS/simpler-grants-gov/pull/653 - it's an issue in the docker image for Python, but nothing I think we need to be concerned with
