### ISSUE TITLE
Implement CloudFront CDN for Static Site

### ISSUE THREAD

**Issue by acouch** [HHS/simpler-grants-gov#680]
### Summary

We are moving forward with CloudFront as a CDN tool. This work is set up CloudFront for the static site.

### Acceptance criteria

- [ ] CloudFront CDN added to static site
- [ ] Update team documentation

**Comment by lorenyu** [comment]
@acouch this is [on the backlog for the infra template too](https://github.com/navapbc/template-infra/issues/459). have you thought about the technical design for this? i was thinking that we could do something like:

- add a new terraform module `infra/modules/cdn`
- call the new cdn module from the `infra/frontend/service` module

the infra template version would look similar but would be more customizable:

- add a `has_cdn` to [app-config](https://github.com/HHS/simpler-grants-gov/blob/main/infra/frontend/app-config/main.tf)
- add a new terraform module `infra/modules/cdn`
- call the new cdn module from the `infra/frontend/service` module if `app_config.has_cdn` is true

thoughts?

**Comment by mxk0** [comment]
To be broken down into implementation tickets during 12/11 refinement.
