### ISSUE TITLE
[30k]: GET opportunities endpoint

### ISSUE THREAD

**Issue by widal001** [HHS/simpler-grants-gov#70]
> [View Simpler Grants.gov full roadmap](https://github.com/orgs/HHS/projects/12)

### Description

[GET opportunities full deliverable specification](https://github.com/HHS/simpler-grants-gov/blob/main/documentation/deliverables/individual_deliverables/get_opportunities.md)

- **What:** Deploy a public API endpoint that allows system-to-system users to access basic information about each opportunity currently listed on grants.gov
- **Why:** Build iteratively, validate connection to the database, and set the groundwork to continue to enhance the API.
- **Who**
  - Internal development team
  - _Subset_ of system-to-system users

### Business Goals

- Build the backend infrastructure for the Simpler Grants.gov API
- Prove our ability to ensure data consistency between grants.gov and simpler.grants.gov
- Begin to develop new data standards for Simpler Grants.gov
- Establish a public-facing foothold for future API updates and releases

### Functionality

- [x] #48 
- [x] #42 
- [x] #50
- [x] #51 
- [x] #57 
- [x] #125 
- [x] #55 
- [x] #54 
- [x] #66 
- [x] #71 
- [x] #131
- [x] #971  

### Definition of Done

- [ ] The following infrastructure requirements are satisfied:
  - [x] The code needed to build and deploy the site is merged to `main`
  - [x] The site is built and hosted with the tools selected in the API Planning and DB Planning deliverables
  - [x] All code quality checks set up in the Developer Tools deliverable are passing
  - [x] The resources required to deploy and host the API are provisioned programmatically using the Infrastructure-as-Code deliverable framework
  - [x] Code changes are deployed using the CI/CD pipeline set up in the Back-end CI/CD deliverable
  - [x] DB migrations are automatically configured through scripts that enable upgrading/downgrading database quickly and easily (e.g., by using Alembic https://github.com/sqlalchemy/alembic)
  - [x] The API has been load tested using the framework established in the Peformance Testing Framework deliverable to ensure that it remains performant under heavy user traffic
  - [x] Logging/monitoring is configured, and it both records the metrics defined below and alerts the development team when the API is down or other key monitoring thresholds are met (e.g. frequency of 4xx requests, response times, etc.)
  - [x] An incident response protocol is in place and the on-call team have followed that protocol in at least one training or simulation
  - [ ] The chosen API URL sub-domain has been secured for future deployment of the API and we've contacted the teams working on the existing service (if any) that is currently accessed through this sub-domain
- [x] The following developer experience (DX) requirements are satisfied:
  - [x] The API is live at the chosen URL
  - [x] Developers can learn how to interact with the API by referencing the API documentation
  - [x] The endpoint path indicates which major version of the API the developer is consuming
  - [x] Breaking changes to the API follow a predictable protocol that is documented within the API Versioning deliverable
  - [x] The endpoint is available when legacy grants.gov experiences planned or unplanned downtime, maintenance, and upgrades
  - [x] Test data is scripted to provide consistent and reliable test fixtures for integration tests and local development per the Test Data and Schema deliverable
  - [x] All developers (including open source contributors) are able to spin up either database replica or test fixture data so that they can conduct local development.
- [x] The following data requirements are satisfied:
  - [x] The endpoint returns all of the grant opportunities that are available on grants.gov
  - [x] The endpoint returns at least one (1) field per opportunity
  - [x] Updates to the data in legacy Grants.gov are propagated to the new endpoint within 1 hour
  - [ ] Our desired project metrics are captured and displayed in a public place

**Comment by sumiat** [comment]
- The API has been load tested using the framework established in the Peformance Testing Framework deliverable to ensure that it remains performant under heavy user traffic will be completed in this effort: https://github.com/HHS/simpler-grants-gov/issues/647
-  Logging/monitoring is configured, and it both records the metrics defined below and alerts the development team when the API is down or other key monitoring thresholds are met (e.g. frequency of 4xx requests, response times, etc.) - will be completed through security work #878  and #1033 
- @acouch working on prod URL

**Comment by EOKENAVA** [comment]
**Weekly Update** 

**What has been done?**

- SIA approved 
- Approval from MH to access prod
- We now have production data flowing all the way to API prod

**Status**
2/20/24 for connection to prod data (due to unexpected roadblocks it was decided that the 2/20 date for Get Opportunities is not achievable.)
Updated Date - **March 5th (On Track)**

**Risk**
None

**Deliverable Date**
March 5th

**What will be done?**
Fast follow tasks as we march towards the March 5th date

**Comment by coilysiren** [comment]
https://github.com/HHS/simpler-grants-gov/issues/906#issuecomment-1977291657 is the last remaining ticket here

**Comment by EOKENAVA** [comment]
**Weekly Update**

**What has been done?**
- Completed 99% of the GET Opportunities Endpoint 30K on time.
- Completed back-end performance testing

**Status**
Blocked | Updated Date: TBD (Blocked on needing a DNS change and production certificate from HHS)

**Risk**
Outside (HHS) dependency

**Deliverable Date**
March 5th (Delayed)

**What will be done?**
- Need DNS change and production certificate from HHS.
- Getting production URL

**Comment by acouch** [comment]
@sarahknoppA6 Tuesday afternoon.

**Comment by coilysiren** [comment]
https://github.com/HHS/simpler-grants-gov/issues/906 is now unblocked, and is now in progress

**Comment by coilysiren** [comment]
https://github.com/HHS/simpler-grants-gov/issues/906 is now done, I believe this completes the 30k

**Comment by acouch** [comment]
## Weekly Update

### What has been done?

### Status
Completed

### Risk
None

### Deliverable Date
March 5th

**Comment by sarahknoppA6** [comment]
@EOKENAVA @margaretspring @acouch The GET Opportunities endpoint 30k cannot be considered completed until the metrics are captured and published in a public place. Suggest the 30k page for GET Opps on the public wiki. cc @lucasmbrown-usds

**Comment by coilysiren** [comment]
@sarahknoppA6 apologies, we never made tickets for that. It looks like the 30k isn't done yet, we'll continue working on it.

**Comment by coilysiren** [comment]
Here is the metrics ticket: https://github.com/HHS/simpler-grants-gov/issues/1484

**Comment by margaretspring** [comment]
**Weekly Update**

**What has been done?**
- Met and confirmed plan for completing GET Opportunities Metrics  #1484 which is included in Sprint 20 which commenced March 20. This will complete the GET Opportunities Endpoint 30K

**Status**
In progress

**Risk**
None

**Deliverable Date**
April 2(Delayed)

**What will be done?**
- https://github.com/HHS/simpler-grants-gov/issues/1484

**Comment by margaretspring** [comment]
**Weekly Update - IN DRAFT**

**What has been done?**
-df


**Status**


**Risk**


**Deliverable Date**


**What will be done?**
-  r

**Comment by sarahknoppA6** [comment]
Can we confirm where the metrics will be shared?

**Comment by sumiat** [comment]
yeah, we'll make sure to update in #1484 and share it in our next updates

**Comment by sarahknoppA6** [comment]
Is this still on track for completion tomorrow? I checked the ticket referenced above and I was a little unclear about the status. cc @lucasmbrown-usds

**Comment by acouch** [comment]
**Weekly Update**

Work has been completed.

**What has been done?**

#1484 has been completed

**Status**
Completed

**Risk**
None

**Deliverable Date**
4/2

**Comment by margaretspring** [comment]
@sarahknoppA6 @widal001 - Is there a review process for closing this 30K? Please advise where/when this is done. Thank you!

**Comment by sarahknoppA6** [comment]
@margaretspring we typically schedule a meeting for 30k closeout. Could we use the first 5 mins of our 30k review meeting tomorrow to do this?

**Comment by widal001** [comment]
This was closed in the 30k review session on 4/11, with the following [update to the deliverable spec](https://github.com/HHS/simpler-grants-gov/commit/d3de3f6f38153b7502844bfb17ef11b15b3a5c45) marking it as "Done"

**Comment by widal001** [comment]
Updated the format of this ticket to reduce discrepancies between the GitHub issue and the deliverable spec.
