### ISSUE TITLE
[Task]: Incident Response Exercise

### ISSUE THREAD

**Issue by sumiat** [HHS/simpler-grants-gov#700]
### Summary

Review and update the incident response plan 

### Acceptance criteria

- [x] practice run with whole team / tabletop exercise: https://app.gitbook.com/o/cFcvhi6d0nlLyH2VzVgn/s/v1V0jIH7mb7Yb3jlNrgk/security/internal-contingency-and-indecent-response-plan

**Comment by EOKENAVA** [comment]
We should maybe just include this as a Launch checklist Item.
