### ISSUE TITLE
[Task]: Add menu component to site header

### ISSUE THREAD

**Issue by sumiat** [HHS/simpler-grants-gov#703]
[Figma prototype](https://www.figma.com/proto/lpKPdyTyLJB5JArxhGjJnE/beta.grants.gov?type=design&node-id=918-1623&t=nFLaS0HsocPUQI8k-0&scaling=scale-down-width&page-id=918%3A1622&starting-point-node-id=918%3A1623)

![image](https://github.com/HHS/simpler-grants-gov/assets/409279/6608adf9-2ecc-4be6-996f-9f511a4bede8)

May already exist in TRUSS and does exist in USDWS. We may just need to pass the object header. 

### Acceptance Criteria
- [ ] Add menu component to site header 
- [ ] tests pass and set up with storybook

~@andycochran will confirm what the mobile view looks like~

**Comment by andycochran** [comment]
The trussworks header component is responsive OOTB: https://trussworks.github.io/react-uswds/iframe.html?id=components-header--basic-header&viewMode=story

We should get the USWDS mobile header for free.
