### ISSUE TITLE
[Task]: Ensure Audit Log Storage Capacity and Retention Time Meets Requirement

### ISSUE THREAD

**Issue by acouch** [HHS/simpler-grants-gov#738]
### Summary

[AU-4: Audit Log Storage Capacity](https://csf.tools/reference/nist-sp-800-53/r5/au/au-4/) requires "Allocate audit log storage capacity to accommodate [Assignment: organization-defined audit log retention requirements]."

[AU-11: Audit Record Retention](https://csf.tools/reference/nist-sp-800-53/r4/au/au-11/) requires "The organization retains audit records for [Assignment: organization-defined time period consistent with records retention policy] to provide support for after-the-fact investigations of security incidents and to meet regulatory and organizational information retention requirements."

The internal storage capacity and retention time requirements are documented in the existing security documentation. The log retention time is 15 months.

Cloudwatch also has a [check for this that should pass](https://us-east-1.console.aws.amazon.com/securityhub/home?region=us-east-1#/standards/nist-800-53-5.0.0/CloudWatch.16), however there is [documentation on how to fix this](https://docs.aws.amazon.com/securityhub/latest/userguide/cloudwatch-controls.html#cloudwatch-16).

This task could be broken down into a spike / discovery issue if desired.

### Steps

- [ ] Determine which logs in AWS need to meet log retention policy
- [ ] Set log retention time for 15 months for required logs

"service/api-prod" and "service/api-front-end" are two that need to be retained. 

### Acceptance criteria

- [ ] Ensure correct storage requirements are met
- [ ] SecurityHub NIST-800 check passes

### Open questions / notes
- Check with @jldroid19 to determine how we want to handle retaining logs. 
- Need to understand what logs need to be captured. The control itself in SH, if the control continues to pop up, we're accepting the risk. 
- What logs do we need to retain?

**Comment by coilysiren** [comment]
Security Hub is failing the Cloudwatch retention check for a bunch of the ECS container performance insights logs groups. It's a little complicated in the case of those logs, as you can't modify their logs retention directly.

Here's how they are configurat: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ecs_cluster#setting, its just that setting, and it auto-creates a log group.

These cloudwatch performance logs create a TON of noise in the scans. So we may need to solve for this for them or mute this control for them.

**Comment by coilysiren** [comment]
All of the `service/*` logs are already being retained for 5 years
<img width="1244" alt="image" src="https://github.com/HHS/simpler-grants-gov/assets/5768468/378b3263-8d9c-4db7-8ea8-75d5471e4bf0">

**Comment by aplybeah** [comment]
All of the container insights logs are being retained for 1 day

**Comment by aplybeah** [comment]
update: I still think we should mute the rule, but there is a way to mass modify retention settings in the console
