### ISSUE TITLE
[Task]: Create Acceptance Criteria and DoD for Stories and Tasks

### ISSUE THREAD

**Issue by acouch** [HHS/simpler-grants-gov#766]
### Summary

This issue is to create the base acceptance criteria for tasks and stories, with these distinct types:

* front-end
* backend
* infrastructure
* spike

This should be documented in Gitbook and reviewed with the team.

### Acceptance criteria

- [ ] Base acceptance criteria for noted types documented in Gitbook
- [ ] Reviewed by team members

**Comment by mxk0** [comment]
No longer relevant.
