### ISSUE TITLE
[Task]: Add Synthetic Canary in User Interface

### ISSUE THREAD

**Issue by acouch** [HHS/simpler-grants-gov#771]
### Summary

This task is to create a synthetic canary in the AWS UI. 

## Steps to implementation

* Select "Heartbeat Monitoring" type Synthetic Canary 
* Use "https://simpler.grants.gov" for the "Application or endpoint URL" and `grantsalerts@navapbc.com` for the email
* Use "syn-python-selenium-2.0" (or other if desired)
  * Use  "https://simpler.grants.gov" for `url` variable
* Select defaults for "Schedule" (every 5 mins + screenshot)
* Select defaults for "Data Retention"
* Create new S3 bucket in "Data Storage"
* Select default for "Acces Permissions" to create a new IAM role
* Select existing VPC
* Determine if "CloudWatch alarm" should be added. I would default to "no" but this is up to the implementer.
* Select `frontend-prod-monitoring` for the sns topic

This will be added to terraform in #562 

### Acceptance criteria

- [ ] Synthetic canary created in UI

**Comment by aplybeah** [comment]
@acouch Created `launch-monitoring` canary in the UI along with necessary resources.
<img width="596" alt="Screen Shot 2023-12-04 at 11 08 33 AM" src="https://github.com/HHS/simpler-grants-gov/assets/37313082/47d26cad-9865-4fba-9c02-bcf67057d785">
<img width="844" alt="Screen Shot 2023-12-04 at 11 09 56 AM" src="https://github.com/HHS/simpler-grants-gov/assets/37313082/5ad47034-154e-47d2-bf87-bfc2590a6455">

**Comment by acouch** [comment]
LGTM!
