### ISSUE TITLE
[Task]: Sync the Codebase to the Latest Infra-Template Update

### ISSUE THREAD

**Issue by aplybeah** [HHS/simpler-grants-gov#784]
### Summary

The infra-template released v0.4.0 fairly recently. We need to sync these changes to our codebase. The breaking change for the database `Use secrets manager to manage db master password` should already be synched. Double-check this by comparing the git SHA in `.template-version` to the `main` branch in the [infrastructure template](https://github.com/navapbc/template-infra/) 

Release Notes: https://github.com/navapbc/template-infra/releases/tag/v0.4.0 

### Acceptance criteria

- [ ] CI/CD pipelines continue to function as expected
- [ ] Database functionality works as expected
- [ ] terraform `plan` and `apply` should run without terraform throwing any errors
- [ ] terraform `apply` shouldn't add any new resources 
- [ ] the git SHA in `.template-version` should be updated

### Notes
- This tends to be a manual process. 
- We should consider how often we want to be making these updates - should not go more than a month before making a sync. 
- There is an update script and the platform team is working on it and we may be able to run a script.

**Comment by coilysiren** [comment]
👍🏽! Changing the default master password is one of our required security changes, so this fits in well

**Comment by coilysiren** [comment]
Citation for my previous comment: https://github.com/HHS/simpler-grants-gov/issues/965

We should add both the master password and the master username into secrets manager, in my opinion. Make them both random strings.

**Comment by coilysiren** [comment]
The latest template version has some networking changes that we need for security work!

**Comment by aplybeah** [comment]
@coilysiren Do you have any recommendations for a regular cadence for this?

**Comment by coilysiren** [comment]
@aplybeah I think syncing from this kind of template into this kind of project is uncharted territory. But! Syncing approximately quarterly sounds like a good goal.

**Comment by coilysiren** [comment]
Noting my new opinion for the record: we've diverged from the template for too long for it the be viable to update directly. From here on out, we're going to have to cherry-pick our changes from the template.

**Comment by acouch** [comment]
> From here on out, we're going to have to cherry-pick our changes from the template.

Closing :)
