### ISSUE TITLE
[Task]: HTML form and validation on newsletter subscribe page

### ISSUE THREAD

**Issue by sumiat** [HHS/simpler-grants-gov#802]
### Summary

Add the HTML form code to the subscribe page and add email validation 

### Acceptance criteria

- [x] Add the HTML code for the subscribe form on the /newsletter-subscribe page
- [x] Add email validation error message from #787 

### Notes and Open Questions

- Signup page = https://www.figma.com/proto/lpKPdyTyLJB5JArxhGjJnE/beta.grants.gov?type=design&node-id=1774-318&t=toolnnawPgXHR27J-0&scaling=scale-down-width&page-id=918%3A1622&starting-point-node-id=918%3A1623 
- Confirmation page = https://www.figma.com/proto/lpKPdyTyLJB5JArxhGjJnE/beta.grants.gov?type=design&node-id=1811-1983&t=toolnnawPgXHR27J-0&scaling=scale-down-width&page-id=918%3A1622&starting-point-node-id=918%3A1623
- Unsubscribe page = https://www.figma.com/proto/lpKPdyTyLJB5JArxhGjJnE/be
- Unsub = https://www.figma.com/proto/lpKPdyTyLJB5JArxhGjJnE/beta.grants.gov?type=design&node-id=1812-2131&t=toolnnawPgXHR27J-0&scaling=scale-down-width&page-id=918%3A1622&starting-point-node-id=918%3A1623

**Comment by acouch** [comment]
This has been completed. The newsletter form requires First Name and Email:

![image](https://github.com/HHS/simpler-grants-gov/assets/512243/26d67bd0-3f84-4f77-aa66-924871531f24)

and the email field validates that the input is an email address:

![image](https://github.com/HHS/simpler-grants-gov/assets/512243/63857909-0d7e-4d43-8414-25bfa7a3ceeb)
