### ISSUE TITLE
Define severity level for CVE's for container vulnerabilities

### ISSUE THREAD

**Issue by acouch** [HHS/simpler-grants-gov#808]
In order to properly respond to the vulnerability scans, we need to know the minimum severity level for CVE's that need to be addressed, and any other security criteria to be applied to containers.

**Comment by jldroid19** [comment]
The security levels for the CVEs and future findings. Along with resolution requirements are as follows:

CRITICAL: 7 days from reporting
HIGH: 7 days from reporting if possible (PO&AM possible)
MEDIUM: Unidentified timeline (Still need to resolve within a reasonable timeframe)
LOW: Unidentified timeline (Still need to resolve within a reasonable timeframe)

The standard that will be followed is NIST 800-53 Revision 4 or 5
