### ISSUE TITLE
[Task]: Combine Process and Research sections on Home

### ISSUE THREAD

**Issue by andycochran** [HHS/simpler-grants-gov#828]
### Summary

- Combine the sections into 1
- Nix the github links
- Nix the archetypes
- Just link to the subpages
- Update the paragraphs 
  - new content
  - smaller sans font

[Figma Prototype v8](https://www.figma.com/proto/lpKPdyTyLJB5JArxhGjJnE/beta.grants.gov?type=design&node-id=1877-3227&t=13AiUSvfuNjbU5Lg-0&scaling=scale-down-width&page-id=1877%3A3226&starting-point-node-id=1877%3A3227&hide-ui=1)

<img width="1236" alt="image" src="https://github.com/HHS/simpler-grants-gov/assets/409279/ac02484e-e9f0-436f-b77c-a5ef27381e77">

**Comment by acouch** [comment]
Completed in https://github.com/HHS/simpler-grants-gov/pull/846
