### ISSUE TITLE
[Task]: Add "High-level roadmap" section to process page

### ISSUE THREAD

**Issue by andycochran** [HHS/simpler-grants-gov#829]
### Summary

- Nix the heading before the milestones 
- Add new section to the Process page above the milestones.
- Use the USWDS icons: `search`, `assessment`, `content_copy`
- We might use USWDS `IconList` component here? 

[Figma Prototype v8](https://www.figma.com/proto/lpKPdyTyLJB5JArxhGjJnE/beta.grants.gov?type=design&node-id=1877-3299&t=13AiUSvfuNjbU5Lg-0&scaling=scale-down-width&page-id=1877%3A3226&starting-point-node-id=1877%3A3227&hide-ui=1)

<img width="1193" alt="image" src="https://github.com/HHS/simpler-grants-gov/assets/409279/e7491b7c-c981-4db3-9dd2-2458532f2663">

**Comment by andycochran** [comment]
Design note: This currently does not have grey borders between each section on the grey background. But it could. Before this section was added, it was intended to look like 1 big section. Now it's kinda 3. Whichever way is easier to do, w/ or w/o the borders, that's fine.

**Comment by acouch** [comment]
Closed in https://github.com/HHS/simpler-grants-gov/pull/839
