### ISSUE TITLE
[Task]: Update Milestone 1 text

### ISSUE THREAD

**Issue by andycochran** [HHS/simpler-grants-gov#830]
### Summary

Update the intro paragraph in the Milestone 1 section of the Process page

[Figma Prototype v8](https://www.figma.com/proto/lpKPdyTyLJB5JArxhGjJnE/beta.grants.gov?type=design&node-id=1877-3299&t=13AiUSvfuNjbU5Lg-0&scaling=scale-down-width&page-id=1877%3A3226&starting-point-node-id=1877%3A3227&hide-ui=1)

<img width="691" alt="image" src="https://github.com/HHS/simpler-grants-gov/assets/409279/18876c96-a788-4ece-ad46-f2c635b7326b">

**Comment by acouch** [comment]
Closed in https://github.com/HHS/simpler-grants-gov/pull/839
