### ISSUE TITLE
[Task]: Update Novice text

### ISSUE THREAD

**Issue by andycochran** [HHS/simpler-grants-gov#833]
### Summary

Update the text in the Novice archetype

[Figma Prototype v8](https://www.figma.com/proto/lpKPdyTyLJB5JArxhGjJnE/beta.grants.gov?type=design&node-id=1877-3370&t=13AiUSvfuNjbU5Lg-0&scaling=scale-down-width&page-id=1877%3A3226&starting-point-node-id=1877%3A3227&hide-ui=1)

<img width="663" alt="image" src="https://github.com/HHS/simpler-grants-gov/assets/409279/5263a8d0-a55c-4fbd-84bf-b690e1706f12">

**Comment by acouch** [comment]
This was done in #852
