### ISSUE TITLE
Analytics - Set up alternative auth flow to export project data

### ISSUE THREAD

**Issue by widal001** [HHS/simpler-grants-gov#837]
### Summary

Because exporting project data requires the `project:read` scope which is not available by default with the `github.token` provisioned automatically within a GitHub action workflow, we needed to set up a Personal Access Token (PAT). 

This is okay for a temporary solution but medium-term we should find another way to authenticate the gh action and provide it with the scopes needed to export project data.

### Acceptance criteria

- [ ] The "Run analytics report" export data from HHS projects without relying on a Personal Access Token
- [ ] This token (or alternative auth mechanism) supports additional linting and workflows

**Comment by coilysiren** [comment]
This is something we should solve before deploying the analytics ELT application to AWS

**Comment by coilysiren** [comment]
The only sure-fire way I can think of to solve this is to create a bot user and use it's personal access token.

A custom Github application might also work, but I'm not sure about that.

**Comment by acouch** [comment]
Some very limited digging suggests bot user + PAT or github app are options I'm seeing. I would typically not want to do the latter, but it is only read access for a project that is already open. I'm not tracking any other users for a github app. Not sure the LOE on that, but I'm guessing that the former would be a lot lower.

**Comment by coilysiren** [comment]
I've setup both before - bot user is easier / faster to setup.

Both options require some degree of admin access to setup. The bot option requires someone with admin access to this repository, whereas (IIRC) the application option requires someone with admin access to the organization.

**Comment by acouch** [comment]
Let's go creating a bot user for now. Steps:

* create new group bot email address `grants-github-bot@navapbc.com`
* create github user
* create PAC token
* add into password storage identified in #1035

**Comment by widal001** [comment]
FWIW I don't think creating [a GitHub app](https://docs.github.com/en/apps/creating-github-apps/registering-a-github-app/registering-a-github-app#registering-a-github-app) and [installing it in this repo](https://docs.github.com/en/apps/using-github-apps/installing-your-own-github-app#installing-your-own-github-app) would be terribly complicated if we could work with one of the HHS org admins to set this up.

But I like having a bot user as a backup for the time being!

**Comment by widal001** [comment]
@acouch quick note on this point:

> I'm not tracking any other users for a github app.

We'd also benefit from having an app to manage some of the linting steps that we're setting up in `.github/linters/` which will likely support writes to our project as well. The bot user could meet this need as well though at least for the time being.

**Comment by coilysiren** [comment]
FYI I added my own personal access token for the dev / staging / prod step functions, as a part of https://github.com/HHS/simpler-grants-gov/pull/1624/.
