### ISSUE TITLE
[10k]: User research incentives

### ISSUE THREAD

**Issue by widal001** [HHS/simpler-grants-gov#84]
### Description

Investigate potentially setting up a system for incentives user research participants, modeled after the incentives system developed by USDS at the White House.

This will promote fairness, as well as increasing the quality and diversity of our pool of user research participants, by compensating participants for sharing their lived experience and expertise.

### Sub-Tasks

- [x] #117  

### Definition of Done
 
- [ ] [ADR]: Research operation

**Comment by acouch** [comment]
This wasn't scoped for the "Search UI 30K", moving to "Search 2.0" for now.

**Comment by widal001** [comment]
Replacing our old 10k ft deliverable issues with a new Epic format

**Comment by widal001** [comment]
Reopening for review during sprint planning
