### ISSUE TITLE
[Task]: Analytics - Create `SprintReport` class

### ISSUE THREAD

**Issue by widal001** [HHS/simpler-grants-gov#840]
### Summary

Create a `SprintReport` class that allows us to combine `SprintBurndown`, `SprintBurnup` and other `BaseMetric` subclasses in a single report.

### Context

Currently each chart produced by the `analytics` package has its own `BaseMetric` subclass, which allows us to easily export this chart and post it to Slack. However, as we add more metrics, the reporting channel in slack will get very crowded. Plus it's often nice to have multiple metrics grouped together or to calculate statistics that cut across metrics. Being able to combine multiple metrics into a single report would help solve many of these needs.

### Acceptance criteria

- [ ] A `SprintReport` class has been created in the `analytics` package that allows us to combine:
  - [ ] `SprintBurndown`
  - [ ] `SprintBurnup`
  - [ ] `SprintPercentComplete`
- [ ] When we export this report to Slack, it creates an initial thread and each metric is posted as a comment in the thread.
- [ ] It's relatively easy to add new metrics to this class as they are developed
- [ ] It's relatively easy to combine different sets of metrics into other reports that share the same capabilities as `SprintReport`

**Comment by acouch** [comment]
Closing for now as we are tracking doing the calculation required for this work within the BI tool.
