### ISSUE TITLE
[ADR]: Strategy for reporting on 30k deliverables

### ISSUE THREAD

**Issue by widal001** [HHS/simpler-grants-gov#854]
### Description

We want to be able to connect 30k deliverables to the issues needed to complete them, so that we can report on things like percentage complete, burndown, etc. We also want to limit the deliverables we're reporting on to ones that are sufficiently scoped and are ready to be worked on. 

This ADR should document our approach to: 
- Associating issues with their "parent" 30k deliverable
- Filtering the list of deliverables and issues we're reporting on

### Approvers

- @lucasmbrown-usds 
- @sumiat 
- @EOKENAVA 
- @sarahknoppA6 

#### Connecting 30k deliverables to issues

- Adding tickets to a milestone and tagging the 30k in the milestone description
- Adding the same `30k: ...` ticket to the issue and the deliverable

#### Filtering the list of deliverables we're reporting on

- Using a `reporting` label applied to the 30k deliverables
- Using the `status` column in the provisional roadmap to include/exclude deliverables

### Decision Criteria

- Reporting strategy is clear and explicit to external stakeholders
- Reporting strategy also enables easy filtering in GitHub projects
- Including issues in a report involves updating as few issues and fields as possible
- We can change the logic for including/excluding issues from reporting without updating the code

### Definition of Done

- [x] The approvers for this decision have been identified (ideally before work on the ADR starts)
- [x] The ADR is created and stored in `documentation/decisions/adr` with status "Accepted"
- [ ] The ADR has been reviewed and approved by the approvers listed above
- [x] The ADR satisfies requirements that are outlined in the ADR template
- [ ] Any follow-up tickets have been created (if necessary)

**Comment by acouch** [comment]
> We want to be able to connect 30k deliverables to the issues needed to complete them, so that we can report on things like percentage complete, burndown, etc.

Burndown charts and percentage complete metrics are typically applied to sprints or short-term deliverables. However the 30K milestones we have engaged in are long-term deliverables. 

Is the expectation that every task is created for a 30K before starting it? Do 30K milestones need to be broken down to be small enough to allow us to create every task? Do we need another abstraction for estimating long-term deliverables like 30Ks?

**Comment by widal001** [comment]
@acouch We'll talk about this a bit further in the leads meeting on Thursday, but we _are_ interested in calculating metrics at the 30k level.

@sumiat and I did talk yesterday about working to downscope some of the 30k deliverables a bit if it felt like they were too large or combined too many discrete features. We can talk through some examples on Thursday to help us rightsize the 30k deliverables as we draft the deliverable spec and scope them.
