### ISSUE TITLE
[Task] Quality Assurance for public launch (Design/Product review)

### ISSUE THREAD

**Issue by andycochran** [HHS/simpler-grants-gov#855]
## Small tasks

- [x] The newsletter pages don't have a correct meta title :
![image](https://github.com/HHS/simpler-grants-gov/assets/512243/c62b5533-1a96-40ee-b652-78b262ca9796)

- [x] First name and email is required, last name is optional on the newsletter page. Consider adding optional and required notations: 
![image](https://github.com/HHS/simpler-grants-gov/assets/111455374/5d54823b-7aa3-4aa4-8960-062744b1ddac)

**Comment by andycochran** [comment]
Are ^these still relevant?

**Comment by sumiat** [comment]
It looks like they are fixed!
