### ISSUE TITLE
[Task]: Newsletter Routing Refactor

### ISSUE THREAD

**Issue by SammySteiner** [HHS/simpler-grants-gov#858]
### Summary

Newsletter pages are currently routed as `/newsletter`, `/newsletter-confirmation`, and `/newsletter-unsubscribe`. 
They should be organized as `/newsletter`, `/newsletter/confirmation`, and `/newsletter/unsubscribe`.
This will also require a ticket to microhealth to update the sendy redirects for form submission

### Acceptance criteria

- Updated newsletter routing
- Updated redirects from microhealth

**Comment by acouch** [comment]
@sumiat to request routes changes to @marwanabufadel

**Comment by sumiat** [comment]
@SammySteiner - Carley did make the updates to the url so this is ready to be updated!
