### ISSUE TITLE
Implement Automated Accessibility Tool

### ISSUE THREAD

**Issue by acouch** [HHS/simpler-grants-gov#871]
### Summary

Implement tool decided in #764

### Acceptance criteria

- [ ] Add Github Action for automated tool
- [ ] Document automated tool in github *.md file
- [ ] Add to Makefile

**Comment by EOKENAVA** [comment]
Per @acouch "It is just unclear when we would do this and what we tool we would use."

**Comment by acouch** [comment]
This is blocked as it is still not decided which tool we would use and when we would use it.

**Comment by mxk0** [comment]
This already happened in #2077.
