### ISSUE TITLE
 Branding and communications strategy alignment and planning

### ISSUE THREAD

**Issue by sumiat** [HHS/simpler-grants-gov#875]
### Summary

We are planning to develop a unified brand and comms identity with the Office of Grants for the grants.gov vision. We need to start coordinations and kickoff for this effort.

We will focus on alignment across teams, understanding responsibilities, goals, deliverables, what to expect for the comms and branding effort so that we can break the work down further.

**Comment by sumiat** [comment]
- Updated the 30k ticket: https://github.com/HHS/simpler-grants-gov/issues/88
- Created milestones for the next chunks of work that will take us through February. 
- Still need to create tickets under the milestones

**Comment by CarleyKimball** [comment]
@sumiat Since branding is closely aligned to comms, can we add that label?
