### ISSUE TITLE
[Task] Respond to log failures

### ISSUE THREAD

**Issue by acouch** [HHS/simpler-grants-gov#878]
## Description

[AU-5: Response To Audit Processing Failures](https://csf.tools/reference/nist-sp-800-53/r4/au/au-5/) requires that "Alerts [Assignment: organization-defined personnel or roles] in the event of an audit processing failure."

This task is to respond to that control. 

## Acceptance Criteria

- [ ] Alert is created if logs from front-end and API containers are not running
- [ ] Alert is documented internally
- [ ] Control implementation statement is updated

## Notes
- Don't really need an s3 approach because we have these in CloudWatch. 
- Send in a batch to about 10, rather than per line
- To check @coilysiren and @acouch - Errors with processing the log themselves not errors within the logs

**Comment by coilysiren** [comment]
We can satisfy this condition via something that posts to slack if it finds an error log, right? To the alerts channel

**Comment by coilysiren** [comment]
This is an important task! [I just realized that the prod API has been down for nearly a week, and we had no idea](https://betagrantsgov.slack.com/archives/C05TSL64VUH/p1708457353233389?thread_ts=1708454903.541039&cid=C05TSL64VUH). This task would help us be actively aware of those kinds of issues.

**Comment by aplybeah** [comment]
@coilysiren I think the fact that there were no alerts for the prod api being down for so long should be a higher priority alerts-wise. If the whole error logs not alerting us isn't a ticket yet I can make one

**Comment by coilysiren** [comment]
@aplybeah this is the gitbook page where all the logging and monitoring stuff is mentioned:

https://app.gitbook.com/o/cFcvhi6d0nlLyH2VzVgn/s/v1V0jIH7mb7Yb3jlNrgk/engineering/security/logging-and-monitoring-sop

**Comment by aplybeah** [comment]
Update:
- Draft PR, still testing in Terraform

**Comment by aplybeah** [comment]
Update: 
- Still working on draft PR, wanted to tweak a few settings on the alarm

**Comment by aplybeah** [comment]
Update: 
Alarm created and tested PR ready for final review
