### ISSUE TITLE
[Task]: Run Fortify WebInspect on Simpler Assets

### ISSUE THREAD

**Issue by acouch** [HHS/simpler-grants-gov#882]
### Summary

"Fortify WebInspect" has been identified as a "Dynamic WAPT Testing" tool. This task is to setup and run this tool on the Simpler environment and share the results.

### Acceptance criteria

- [ ] "Fortify WebInspect" run and results shared

**Comment by coilysiren** [comment]
https://www.microfocus.com/en-us/cyberres/application-security/webinspect

**Comment by coilysiren** [comment]
It seems like this is a SASS product that we would have to buy, which means we would need to go through a procurement process. Unless it's something MicroHealth has already purchased and configured for us? Unfortunately I can't find any information to confirm or deny that!

**Comment by acouch** [comment]
This would be run on a quarterly basis, unlike the Nesses / ECR / Security Hub which are run weekly. Moving to the next milestone.

**Comment by acouch** [comment]
Closing as we don't need to track this long-term task in GitHub and it is unclear if this specific tool will be required.
