### ISSUE TITLE
[Task] Update milestone button links

### ISSUE THREAD

**Issue by andycochran** [HHS/simpler-grants-gov#910]
- [x] Confirm where the "View milestone" buttons on the `/process` page should go 
- [x] Update the links

### Open Question:

Do we want to link directly to the specific 30Ks instead of to the GitHub Projects board? 
1. https://github.com/HHS/simpler-grants-gov/issues/70 (Get Opportunities)
2. https://github.com/HHS/simpler-grants-gov/issues/89 (Search MV)

Or should we link to the deliverable spec?
1. https://github.com/HHS/simpler-grants-gov/blob/main/documentation/deliverables/individual_deliverables/get_opportunities.md (GET Opportunities Endpoint)
2. https://github.com/HHS/simpler-grants-gov/blob/main/documentation/deliverables/individual_deliverables/search_mvp.md (Search MVP)

### Decision 

Based on discussion in Slack, we decided that we'll from the milestones on the website to the GitHub issue for the following reasons:

- Issue link is stable (i.e. won't break if we rename these deliverables)
- It represents the most up-to-date status of the deliverable
- We can use that issue to link to other supporting documentation, including:
  - the full deliverable spec
  - the GitHub product roadmap project

**Comment by andycochran** [comment]
Assigning this to Product for now. Please reassign once a decision has been made and we can update the links.

**Comment by widal001** [comment]
### Decision 

We'll from the milestones on the website to the GitHub issue for the following reasons:

- Issue link is stable (i.e. won't break if we rename these deliverables)
- It represents the most up-to-date status of the deliverable
- We can use that issue to link to other supporting documentation, including:
  - the full deliverable spec
  - the GitHub product roadmap project

Reassigning to the eng/design team.

**Comment by widal001** [comment]
@sumiat also helped us update the links on the following milestones:

- We've linked all of the ones that we have completed deliverable specs for, namely:
- [[30k]: Soft Launch: Static Site](https://github.com/HHS/simpler-grants-gov/issues/62)
- [[30k]: Static site public launch](https://github.com/HHS/simpler-grants-gov/issues/692)
- [[30k]: GET opportunities endpoint](https://github.com/HHS/simpler-grants-gov/issues/70)
- [[30k]: Search MVP](https://github.com/HHS/simpler-grants-gov/issues/89)
