### ISSUE TITLE
[Task]: Gather historical data from various sources

### ISSUE THREAD

**Issue by sumiat** [HHS/simpler-grants-gov#937]
### Summary

MicroHealth to compile raw data from various sources into a shared folder. 
**Audit list:**

**Brand Identity Standards and Guidelines**
- branding and style-guide docs (including legacy docs inherited from prior contractors)
- All versions of all identities ever used
- All signatures, marks, logotypes, etc 
- HHS brand identity docs (including how subbrands should be treated)
- All taglines
- Image banks, illustration libraries, etc
- Voice and Tone guidelines

**Collateral**

- Letterhead
- Proposal covers
- Forms, envelopes, stationery
- Business Cards
- Swag (T-shirts, water bottles, pens, etc.)
- Leadership comms materials
- Annual reports
- Powerpoints, slide decks, PDFs

**Marketing Materials**

- Relevant product literature, flyers, conference handouts
- Newsletters and emails (screenshots)
- Advertising campaign material 
- Blog Posts (links)

**Social media**

- Video (links and screenshots of branded/relevant points)
- Social Media screenshots and links (posts and profile pages)
- grants mascot (history, graphic assets, etc)

**Data**

- Youtube traffic data
- Chatbot data (frequently asked questions, other relevant data)
- Help desk data
- CMS data
- UAT findings from CMS

**Market Research**

- Competitive audits
- Key message frameworks
- Primary and Secondary audience profiles, archetypes, etc (if larger than the work in the Huge documentation)

### Acceptance criteria

- [ ] Collect data from the various sources and place the data in the SharePoint folder designated for the team to work within.

**Comment by CarleyKimball** [comment]
We provided access to BPS SharePoint to the Nava team, our respository for all assets / template for Grants.gov Comms.

**Comment by sumiat** [comment]
@senongo - is it ok to move this to done?
