### ISSUE TITLE
[10k]: API static site content updates

### ISSUE THREAD

**Issue by sumiat** [HHS/simpler-grants-gov#940]
### Definition

As we approach the release of the initial version of our GET Opportunities API, we aim to update the simpler.grants.gov to align with the release. This may involve reevaluating the site architecture, considering options such as creating a distinct roadmap page separate from the process page, or incorporating a clear call-to-action to guide audience engagement.

### Business Goals

- Update the content on the simpler.grants.gov site to include information about the API release and ways to get involved. 

### In scope

- Update the site content

### Out of scope

- Open source CTA - that will be covered under #72 

### Tasks

Sub-tasks can be found in [this milestone](https://github.com/HHS/simpler-grants-gov/milestone/113)

### Definition of Done

- [ ] {Condition that must be satisfied by this deliverable}

**Comment by widal001** [comment]
Replacing our old 10k ft deliverable issues with a new Epic format

**Comment by widal001** [comment]
Reopening for review during sprint planning
