### ISSUE TITLE
[Task]: Add Deletion Detection for ELBs

### ISSUE THREAD

**Issue by acouch** [HHS/simpler-grants-gov#960]
### Summary

NIST-800 53 requires that [Application Load Balancer deletion protection should be enabled](https://us-east-1.console.aws.amazon.com/securityhub/home?region=us-east-1#/standards/nist-800-53-5.0.0/ELB.6). This ticket is to enable deletion protection so this control passes.

### Acceptance criteria

- [ ] ELB.6 check passes

**Comment by coilysiren** [comment]
slight typo in the issue title, I don't think this has anything to do with "Redirects"

**Comment by SammySteiner** [comment]
blocked by #1041
