### ISSUE TITLE
[Task]: Enable HTTPs Redirect for API

### ISSUE THREAD

**Issue by acouch** [HHS/simpler-grants-gov#961]
### Summary

This might be close once we implement #906.

NIST-800 53 requires [Application Load Balancer should be configured to redirect all HTTP requests to HTTPS](https://us-east-1.console.aws.amazon.com/securityhub/home?region=us-east-1#/standards/nist-800-53-5.0.0/ELB.1). The current API in dev does not have HTTPS enabled.

### Acceptance criteria

- [ ] ELB.1 check passes

**Comment by coilysiren** [comment]
I'm +1 on letting this wait until we get the proper API URLs, eg. https://github.com/HHS/simpler-grants-gov/issues/906

**Comment by coilysiren** [comment]
POAM:

- add "no index" and related functionality to our dev build, so the general public doesn't stumble onto our dev site [link](https://betagrantsgov.slack.com/archives/C05TSL64VUH/p1704220276036419)
- add a DNS CNAME that points to our dev load balancers, like beta.grants.gov used to
- configure TLS for that dev site, either a CA cert or a self signed one
- configure the load balancer to redirect HTTP to HTTPS

**Comment by coilysiren** [comment]
This is blocked because we need a HTTPS URL to redirect to.

**Comment by coilysiren** [comment]
Blocked by https://github.com/HHS/simpler-grants-gov/issues/906

**Comment by acouch** [comment]
This is done: 

```sh
$curl http://api.simpler.grants.gov/ -I
HTTP/1.1 301 Moved Permanently
Server: awselb/2.0
Date: Tue, 19 Mar 2024 18:22:21 GMT
Content-Type: text/html
Content-Length: 134
Connection: keep-alive
Location: https://api.simpler.grants.gov:443/
```
