### ISSUE TITLE
[Task]: VPC Security: Pass Security Hub Checks

### ISSUE THREAD

**Issue by acouch** [HHS/simpler-grants-gov#962]
### Summary

EC2 is being used to host nessus and burpsuite scanning tools. A number of EC2 checks in Security Hub are not passing. The suggested steps should be taken to remediate this to the checks pass. The checks are:

- [ ] [Amazon EC2 should be configured to use VPC endpoints that are created for the Amazon EC2 service](https://us-east-1.console.aws.amazon.com/securityhub/home?region=us-east-1#/standards/nist-800-53-5.0.0/EC2.10)
- [ ] [VPC flow logging should be enabled in all VPCs](https://us-east-1.console.aws.amazon.com/securityhub/home?region=us-east-1#/standards/nist-800-53-5.0.0/EC2.6)

### Acceptance criteria

- [ ] EC2 checks passing

**Comment by coilysiren** [comment]
This is quite large! Some of this subtasks will take multiple steps. Should definitely break this up into sub tickets

**Comment by acouch** [comment]
@coilysiren thanks for noting. Are there any you would group together or do you think they should all be sub-tickets?

**Comment by coilysiren** [comment]
Here's my proposed grouping:

VPC Security
- Amazon EC2 should be configured to use VPC endpoints that are created for the Amazon EC2 service
- VPC default security groups should not allow inbound or outbound traffic
- Network ACLs should not allow ingress from 0.0.0.0/0 to port 22 or port 3389 
- VPC flow logging should be enabled in all VPCs

EC2 Security
- EBS default encryption should be enabled
- Attached EBS volumes should be encrypted at-rest
- EC2 instances should be managed by AWS Systems Manager

(etc)
- EC2 subnets should not automatically assign public IP addresses

**Comment by sumiat** [comment]
pulled this one into its own ticket: [VPC default security groups should not allow inbound or outbound traffic](https://us-east-1.console.aws.amazon.com/securityhub/home?region=us-east-1#/standards/nist-800-53-5.0.0/EC2.2)

**Comment by sumiat** [comment]
split these up based on @coilysiren's recommendation. Other ticket is here: https://github.com/HHS/simpler-grants-gov/issues/987

**Comment by coilysiren** [comment]
linking the VPC default security groups ticket: https://github.com/HHS/simpler-grants-gov/issues/986

**Comment by coilysiren** [comment]
Assigning to myself since it overlaps with my current VPC work
