### ISSUE TITLE
[Task]: Update ECS Settings so That ECS.2 Check Passes

### ISSUE THREAD

**Issue by acouch** [HHS/simpler-grants-gov#963]
### Summary

NIST-800 53 requires [ECS services should not have public IP addresses assigned to them automatically](https://us-east-1.console.aws.amazon.com/securityhub/home?region=us-east-1#/standards/nist-800-53-5.0.0/ECS.2). This issue is to update ECS so that this check passes.

### Acceptance criteria

- [ ] ECS.2 Check passes

### Notes
- We want to set this up so you have to go through the load balancer

**Comment by jldroid19** [comment]
The ECS Containers are deployed in a Public Subnet. The public IP can be DISABLED via awscli or the containers can be deployed within a private subnet.

**Comment by coilysiren** [comment]
> or the containers can be deployed within a private subnet

I think this is the best move

**Comment by coilysiren** [comment]
We only have one private subnet... I'll need to make more
