### ISSUE TITLE
[Task]: Address Macie.1 "Amazon Macie should be enabled" Security Check

### ISSUE THREAD

**Issue by acouch** [HHS/simpler-grants-gov#964]
### Summary

Security Hub recommends [Amazon Macie should be enabled](https://us-east-1.console.aws.amazon.com/securityhub/home?region=us-east-1#/standards/nist-800-53-5.0.0/Macie.1). This ticket is to either turn off that recommendation or enable Macie.

### Steps

- [ ] Discuss with @jldroid19 
- [ ] Disable control check or enable Macie

### Acceptance criteria

- [ ] Macie.1 check no longer fails

### Notes
- if there are any PHI or PII data captured then this ticket needs to be considered. 
- do we need to do this in terraform or is the console sufficient? console is sufficient

**Comment by jldroid19** [comment]
Amazon Macie discovers sensitive data using machine learning and pattern matching, provides visibility into data security risks, and enables automated protection against those risks. Macie automatically and continually evaluates your Amazon Simple Storage Service (Amazon S3) buckets for security and access control, and generates findings to notify you of potential issues with the security or privacy of your Amazon S3 data. Macie also automates discovery and reporting of sensitive data, such as personally identifiable information (PII), to provide you with a better understanding of the data that you store in Amazon S3.

**Comment by coilysiren** [comment]
Do we actually use S3 in a sensitive data capacity? That's the only way Macie would be useful.

**Comment by coilysiren** [comment]
I just checked s3. Basically everything in there is access logs. Given that, I see setting up Macie is "nice to have" but ultimately low priority. I would push it into https://github.com/HHS/simpler-grants-gov/milestone/95

**Comment by coilysiren** [comment]
Just enabled this. It was a single click and took seconds
