### ISSUE TITLE
[Task]: Configure RDS to Pass Security Hub Checks 

### ISSUE THREAD

**Issue by acouch** [HHS/simpler-grants-gov#965]
### Summary

Security Hub notes the following for NIST-800 53 that need to be remediated:

- [ ] [RDS instances should have automatic backups enabled](https://us-east-1.console.aws.amazon.com/securityhub/home?region=us-east-1#/standards/nist-800-53-5.0.0/RDS.11)
- [ ] [RDS DB clusters should be configured for multiple Availability Zones](https://us-east-1.console.aws.amazon.com/securityhub/home?region=us-east-1#/standards/nist-800-53-5.0.0/RDS.15)
- [ ] [RDS Database Clusters should use a custom administrator username](https://us-east-1.console.aws.amazon.com/securityhub/home?region=us-east-1#/standards/nist-800-53-5.0.0/RDS.24)
- [ ] [RDS database instances should use a custom administrator username](https://us-east-1.console.aws.amazon.com/securityhub/home?region=us-east-1#/standards/nist-800-53-5.0.0/RDS.25)

This ticket is to fix those or identify ones that do not apply to our environment.  This issue can be broken up into smaller tasks if desired by the implementer.

### Acceptance criteria

- [ ] RDS.11, RDS.15, RDS.24, RDS.25 checks pass or are disabled

### Notes
- if the engineer working on this ticket needs to know info on how users set up or data migrations work, connect with @chouinar

**Comment by coilysiren** [comment]
small FYI: I'm quite confident that doing this will require us to redeploy the RDS instance(s)

**Comment by aplybeah** [comment]
DB password can't include these characters `: ;+%`

**Comment by coilysiren** [comment]
^ If we want to use the master username and password for the DMS
