### ISSUE TITLE
[Task]: Configure S3 to Pass Security Hub Checks

### ISSUE THREAD

**Issue by acouch** [HHS/simpler-grants-gov#966]
### Summary

Security Hub notes the following for NIST-800 53 that need to be remediated:

- [ ] [S3 Block Public Access setting should be enabled](https://us-east-1.console.aws.amazon.com/securityhub/home?region=us-east-1#/standards/nist-800-53-5.0.0/S3.1)
- [ ] [S3 buckets with versioning enabled should have lifecycle policies configured](https://us-east-1.console.aws.amazon.com/securityhub/home?region=us-east-1#/standards/nist-800-53-5.0.0/S3.10)
- [ ] [S3 buckets should have event notifications enabled](https://us-east-1.console.aws.amazon.com/securityhub/home?region=us-east-1#/standards/nist-800-53-5.0.0/S3.11)
- [ ] [S3 buckets should be configured to use Object Lock](https://us-east-1.console.aws.amazon.com/securityhub/home?region=us-east-1#/standards/nist-800-53-5.0.0/S3.15)
- [ ] [S3 buckets should be encrypted at rest with AWS KMS keys](https://us-east-1.console.aws.amazon.com/securityhub/home?region=us-east-1#/standards/nist-800-53-5.0.0/S3.17)
- [ ] [S3 buckets should require requests to use Secure Socket Layer](https://us-east-1.console.aws.amazon.com/securityhub/home?region=us-east-1#/standards/nist-800-53-5.0.0/S3.5)
- [ ] [S3 bucket server access logging should be enabled](https://us-east-1.console.aws.amazon.com/securityhub/home?region=us-east-1#/standards/nist-800-53-5.0.0/S3.9)

This ticket is to fix those or identify ones that do not apply to our environment. This issue can be broken up into smaller tasks if desired by the implementer.

### Acceptance criteria

- [  ] S3.1, S3.5, S3.9, S3.10, S3.11, S3.15, S3.17 checks pass or are disabled

**Comment by coilysiren** [comment]
> [S3 buckets should have event notifications enabled](https://us-east-1.console.aws.amazon.com/securityhub/home?region=us-east-1#/standards/nist-800-53-5.0.0/S3.11)

I'm not sure we need / want this one ☝🏼

**Comment by jamesbursa** [comment]
### Current failures

| Buckets                                 | S3.5 | S3.9 | S3.10 | S3.17 |
| ---------------------------- | ----- | ----- | ----- | ----- |
| api-prod-access-logs-...      | ❌      |          |          |           |
| aws-cloudtrail-logs-...          |           | ❌     | ❌      | ❌      |
| cf-templates-...                     |           |         |           | ❌      |
| config-bucket-...                   | ❌      |          |          | ❌      |
| frontend-...-access-logs-...  |           | ❌     |          |          |
| grants-equity-...tf-logs         |          | ❌     | ❌      |          |
| ...-rtd                                     |          |          | ❌      | ❌      |
| simpler-grants-gov...tf          |          |          | ❌      |          |
| simpler-grants-gov...tf-logs |          | ❌      |          |          |
| t-...                                         | ❌      | ❌     |          |          |

### Failed for all buckets

S3.11 S3 buckets should have event notifications enabled
S3.15 S3 buckets should be configured to use Object Lock

**Comment by jamesbursa** [comment]
Obsolete `grants-equity-...` buckets deleted. Updated status:

### Current failures

| Buckets                                 | S3.5 | S3.9 | S3.10 | S3.17 |
| ---------------------------- | ----- | ----- | ----- | ----- |
| api-prod-access-logs-...      | ❌      |          |          |           |
| aws-cloudtrail-logs-...          |           | ❌     | ❌      | ❌      |
| cf-templates-...                     |           |         |           | ❌      |
| config-bucket-...                   | ❌      |          |          | ❌      |
| frontend-...-access-logs-...  |           | ❌     |          |          |
| ~~grants-equity-...tf-logs~~ |          | 🏳     | 🏳      |          |
| ...-rtd                                     |          |          | ❌      | ❌      |
| simpler-grants-gov...tf          |          |          | ❌      |          |
| simpler-grants-gov...tf-logs |          | ❌      |          |          |
| t-...                                         | ❌      | ❌     |          |          |

### Failed for all buckets

S3.11 S3 buckets should have event notifications enabled
S3.15 S3 buckets should be configured to use Object Lock

**Comment by jamesbursa** [comment]
For S3.17 (S3 buckets should be encrypted at rest with AWS KMS keys):

- Manually edited bucket encryption for: `cf-templates-...`, `aws-cloudtrail-logs...`, `config-bucket-...`, `...-rtd`

**Comment by jamesbursa** [comment]
Latest status:

| ID       | Name          | Status        |
| ------ | ----------- | ----------- |
| S3.5    | S3 buckets should require requests to use Secure Socket Layer        | Fixed for all buckets (pending deploys) |
| S3.9    | S3 bucket server access logging should be enabled         | Failed for most buckets; most buckets are access logs, no value in access logging for access logs         |
| S3.10  | S3 buckets with versioning enabled should have lifecycle policies configured   | Failed for 4 buckets, unclear value         |
| S3.11   | S3 buckets should have event notifications enabled         | Failed for all buckets; no reasonable destination for event notifications to go to         |
| S3.15  | S3 buckets should be configured to use Object Lock       | Failed for 15 buckets; can not be used for LB access logs (not compatible)          |
| S3.17  | S3 buckets should be encrypted at rest with AWS KMS keys   | Fixed for all buckets         |

**Comment by sarahknoppA6** [comment]
Was this ticket completed? I'm looking through the status updates and trying to understand if it just needs to be closed out or if there's more work to do on it.

**Comment by jamesbursa** [comment]
@sarahknoppA6 I think we've done everything that's reasonable to do here, but defer to @acouch to decide.
