### ISSUE TITLE
[Task]: Configure SNS to Pass Security Hub Checks

### ISSUE THREAD

**Issue by acouch** [HHS/simpler-grants-gov#968]
### Summary

Security Hub notes the following for NIST-800 53 that need to be remediated:

- [ ] [SNS topics should be encrypted at-rest using AWS KMS](https://us-east-1.console.aws.amazon.com/securityhub/home?region=us-east-1#/standards/nist-800-53-5.0.0/SNS.1)
- [ ] [Logging of delivery status should be enabled for notification messages sent to a topic](https://us-east-1.console.aws.amazon.com/securityhub/home?region=us-east-1#/standards/nist-800-53-5.0.0/SNS.2)

This ticket is to fix those or identify ones that do not apply to our environment.  This issue can be broken up into smaller tasks if desired by the implementer.

### Acceptance criteria

- [ ] SNS.1, SNS.2 checks pass or are disabled

**Comment by aplybeah** [comment]
A primary look around reveals that we have `# checkov:skip=CKV_AWS_26:SNS encryption for alerts is unnecessary` in `infra/modules/monitoring/main`

I'm inclined to agree because the SNS topics are tied to cloudwatch 5xx error alarms which I don't anticipate containing any content that would require encryption. That being said, it looks like all of the SNS topics are still `pending confirmation` which means the events aren't being sent to begin with

**Comment by coilysiren** [comment]
> I don't anticipate containing any content that would require encryption.

That makes sense to me!

**Comment by aplybeah** [comment]
So, it looks like I can't actually disable the individual checks. Maybe a permission issue?

```
Security Hub can't process the request right now because of an issue with the server. Try again later.: Account [ID] is managed by a configuration policy. You must disassociate the account from this policy to access this operation.
```

cc @acouch @coilysiren

**Comment by coilysiren** [comment]
@aplybeah my understanding is that MicroHealth doesn't want us to disable the individual checks. Instead we are supposed to document then ignore them, like James has been doing in slack here:

https://betagrantsgov.slack.com/archives/C0647CQ3A66/p1706720913477489

**Comment by aplybeah** [comment]
@coilysiren gotcha! I missed that part of the process 😅

**Comment by coilysiren** [comment]
No worries! Stuff has been moving fast lately
