### ISSUE TITLE
[30k]: Search API

### ISSUE THREAD

**Issue by widal001** [HHS/simpler-grants-gov#972]
### Key links

- [Deliverable specification](https://simpler-grants.gitbook.io/wiki/product/deliverables/specifications/search-api)
- [Simpler Grants.gov full roadmap](https://github.com/orgs/HHS/projects/12)
- [10k milestones](https://github.com/orgs/HHS/projects/13/views/11?sliceBy%5Bvalue%5D=Search+API)

### Description

- **What:** Publicly launch the API and communicate it to our stakeholders.
- **Why:** Enables us to begin collecting feedback from system-to-system users (S2S) and planning new API features.
- **Who**
  - Federal S2S users
  - External S2S users

> [!NOTE]
> For more information about this deliverable, please refer to the deliverable specification linked above.

**Comment by EOKENAVA** [comment]
**Weekly Update**

What has been done?

Access to codebase
- Walkthrough of codebase is still pending
Strategy session with HHS and Nava

Status
On Track

Risk
None

Deliverable Date
May 14th

What will be done?

Walkthrough of codebase is still pending
Move forward with the Search work using Michael's defined approach
Run the logic of the data in prod
Start SIA for the non-public, PII, and other data that we'll need in the next 12 month roadmap

**Comment by lucasmbrown-usds** [comment]
Could we clarify what this update means: "Run the logic of the data in prod"? Thanks. I'm guessing it's basically, compare opportunity listings we have in grants.gov PROD to the opportunity listings we have in simpler.grants.gov PROD, and make sure they're the same which will confirm the logic in Simpler. But I'm not 100% sure if that's what it means?

**Comment by chouinar** [comment]
@lucasmbrown-usds I think that is what it was referring to - just the additional set of data validations to confirm our understanding of the data as what we have access to in dev right now might not be representative of real data.

**Comment by EOKENAVA** [comment]
**Weekly Update**

**What has been done?**
Setup & create tests for the copy-oracle-data command
Develop strategy and plan for data modeling
Completed research/discussion around data model session with stakeholders like Narmada, Lucas, and Julius

**Risk**
None

**Deliverable Date**
May 14th

**What will be done?**
Adjust of the database schema of the opportunity tables
Adjust search API model to use the new schema & fields

**Comment by EOKENAVA** [comment]
**Weekly Update**

**What has been done?**
- Adjusted the database schema of the opportunity tables

**Risk**
None

**Deliverable Date**
May 14th

**What will be done?**
- Add filtering and update the request model of the search endpoint
- Adjust search API model to use the new schema & fields
- Modify gunicorn config to use recommended number of workers and threads

**Comment by margaretspring** [comment]
**Weekly Update**

**What has been done?**
- Adjusted the database schema of the opportunity tables
- Adjusted the API schema to match the database schema
- Added filtering to the API for all faceted fields (eg. opportunity status, funding instrument, agency, etc.)
- Modify gunicorn config to use recommended number of workers and threads

**Risk**
None

**Deliverable Date**
May 14th

**What will be done?**
- Implement support in the search endpoint to use the query box
- Updates for query param logging formatting (to be easily parsed by New Relic when implemented)
- Begin script that will populate current opportunity information once imported from Oracle DB

**Comment by margaretspring** [comment]
**Weekly Update - IN DRAFT**

**What has been done?**
-
-

**Status**


**Risk**


**Deliverable Date**


**What will be done?**
-

**Comment by margaretspring** [comment]
**Weekly Update 4/11**
 
**What has been done**


**Status**
In progress

**Risk**
SIA acceptance for Security / PII & Non-Public data in Simpler.grants.gov (Non-Public Data is critical, PII is nice to have at this point)

**Deliverable Date**
May 14th

**What will be done?**
- Transformation: Desk research against evaluation criteria: dbt, evaluate pushing from Oracle to Postgres, specify and documenting a list of evaluation criteria for Transform technology, and research a shortlist of Transform technology solutions
- Security: will continue the SIA documentation
- API: some fixes to current db structure but will complete that

**Comment by widal001** [comment]
Updated ticket format to reduce discrepancies with deliverable spec.

**Comment by margaretspring** [comment]
**Weekly Update 4/17**

**What has been done?**


**Status**


**Risk**
  

**Deliverable Date**


**What will be done?**

**Comment by lucasmbrown-usds** [comment]
Small nitpick here: the comment above says "Final draft of Slack SIA", but I think you actually mean "Final draft of Search SIA". There have been two SIAs floating around recently (Slack and Search).

**Comment by margaretspring** [comment]
**Weekly Update 5/1**

**What has been done?**
- 

**Status**
In Progress

**Risk**
 

**Deliverable Date**


**What will be done?**

**Comment by sarahknoppA6** [comment]
Development team has updated anticipated delivery date to 5/28 given additional work to improve the data model. https://betagrantsgov.slack.com/archives/C06F55BKLKX/p1714684814304889

**Comment by acouch** [comment]
**Weekly Update 5/8**

**What has been done?**
- Loading from legacy to staging database 
- Transformation code created for opportunity, summary, listing created but still in development

**Status**
- In Progress

**Risk**
- Transformation work

**Deliverable Date**
- Sprint 24 - May 28

**What will be done?**
- Finishing last table #1749 
- Testing loaded data
- Running load and transform steps in stage

**Comment by widal001** [comment]
Replacing our old deliverable tickets with a new ticket format
