### ISSUE TITLE
Update Sendy List ID

### ISSUE THREAD

**Issue by SammySteiner** [HHS/simpler-grants-gov#976]
### Summary

Sendy recommended hardcoding our sendy url, api key, and list id directly in the html of the application. 
While we already removed that from the codebase and from the client browser, the url and list id are still in our github history. While the url likely cannot be changed, we should update the list id to prevent any possible malicious use.

### Acceptance criteria

- [ ] Sendy list id present in git history is no longer used by the application
- [ ] Sendy list id present in git history is no longer valid in Sendy's system

**Note** that this ticket previously called for rewriting the git history to remove any Sendy secret data. As this was deemed too risky and complex, the AC was updated.

**Comment by margaretspring** [comment]
@doug-s-nava - Given this has been an open ticket since last Jan. Do you have any objections to pushing it out past the 12/10 deadlines? At that point we'll have a bit of bandwidth to explore rebuilding the account profile to invalidate the one with published data.

**Comment by doug-s-nava** [comment]
That works for me. I don't think this is particularly pressing. Moving back to the icebox for now.

**Comment by mxk0** [comment]
Noting for posterity that there are a bunch of details from Doug's investigation [here](https://betagrantsgov.slack.com/archives/C05TSL64VUH/p1731704996678969).

**Comment by mxk0** [comment]
We're likely moving off of Sending in the next quad or so; marking this as won't fix.
