### ISSUE TITLE
[Spike]: Methods to filter out internal traffic in GA4

### ISSUE THREAD

**Issue by sumiat** [HHS/simpler-grants-gov#978]
### Summary

We are currently tracking all traffic in our GA instance for simpler.grants.gov. We do not have a way of delineating the internal and public traffic. In this spike, we want to understand if there is a favorable mechanism for filtering out internal traffic and the level of effort of the different approaches. 
- Approach 1: Filter out the internal traffic from Nava, MicroHealth, or Agile6 in the google analytics dashboard. This may be able to be done if we collect all the IPs
- Approach 2: Set up our GA instance to automatically filter out internal traffic
- Approach 3: do nothing; the traffic is not that significant. 

### Acceptance criteria

- [ ] Document the different approaches possible and LOE for each. Give a recommendation on the path forward.

**Comment by mxk0** [comment]
> Approach 3: do nothing; the traffic is not that significant.

Going with Approach 3.
