### ISSUE TITLE
[Task]: Enable and Configure CloudTrail

### ISSUE THREAD

**Issue by acouch** [HHS/simpler-grants-gov#979]
### Summary

This task it to remediate [CloudTrail should be enabled and configured with at least one multi-Region trail that includes read and write management events](https://us-east-1.console.aws.amazon.com/securityhub/home?region=us-east-1#/standards/nist-800-53-5.0.0/CloudTrail.1). The implementer can turn or and configure cloud trail or provide evidence that this doesn't apply to our system.

### Acceptance criteria

- [ ] CloudTrail.1 check is no longer failing.

**Comment by coilysiren** [comment]
done!
