### ISSUE TITLE
[Task]: VPC default security groups should not allow inbound or outbound traffic

### ISSUE THREAD

**Issue by sumiat** [HHS/simpler-grants-gov#986]
### Summary

address high security risk: [VPC default security groups should not allow inbound or outbound traffic](https://us-east-1.console.aws.amazon.com/securityhub/home?region=us-east-1#/standards/nist-800-53-5.0.0/EC2.2)

### Acceptance criteria

- [x] VPC `vpc-0d732ba4691054b48` in `us-east-1` default security groups should not allow inbound or outbound traffic
- [x] VPC `vpc-0e374e8372c980737` in `us-east-2` default security groups should not allow inbound or outbound traffic
- [x] VPC `vpc-00450fd8b18888d45` in `us-east-2` default security groups should not allow inbound or outbound traffic

### Notes
- investigate if we should use the default security group. if we are, then it needs to be replaced

**Comment by coilysiren** [comment]
This one is a little difficult, because you first have to check if anything is using / relying on the default security groups. So this task could take 30 minutes, or it could take 8 hours. It's a real dice roll.

**Comment by coilysiren** [comment]
This is done 😎
