### ISSUE TITLE
[10k]: Search API - Data transformation

### ISSUE THREAD

**Issue by sumiat** [HHS/simpler-grants-gov#990]
### Definition
Set up a data transformation process and tool that transforms the data from the current grants.gov live data model into the new data model for simpler.grants.gov.

### Business Goals

- Create a process that translates data between the current and future data model

### In scope

- ADR to determine the technology for the ETL 
- Infrastructure set up for running the ETL job(s)
- Setup logic for converting data

### Tasks

Work will be completed under these two milestones: 
- [ELT decision](https://github.com/HHS/simpler-grants-gov/milestone/119)
- [ELT implementation](https://github.com/HHS/simpler-grants-gov/milestone/141)

### Definition of Done

- [ ] There is a service in place which transforms data from the old data model from Grants.gov live to a new, intuitive, easier-to-use data model. 
- [ ] Changes made to data on grants.gov live are propagated to the new simpler.grants.gov data model within 1 hour

**Comment by widal001** [comment]
Replacing our old 10k ft deliverable issues with a new Epic format

**Comment by widal001** [comment]
Reopening for review during sprint planning
