### ISSUE TITLE
[Task]: Automated labelling of pull requests

### ISSUE THREAD

**Issue by jamesbursa** [HHS/simpler-grants-gov#994]
### Summary

Configure the Pull Request Labeler https://github.com/marketplace/actions/labeler to label PRs with appropriate labels as soon as they are opened:
- Component of the system (infra, frontend, api, etc.)
- Programming language (python, terraform, javascript, etc.)

### Acceptance criteria

- A GitHub action `.github/workflows/pull-request-labeler.yml` is added to run Labeler https://github.com/marketplace/actions/labeler
- A configuration file `.github/labeler.yml` is added to configure appropriate labels

**Comment by mdragon** [comment]
This is done
